/*

 BlooPJS
 Copyright (c) 2011 Tim Ryan
 Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/
BFloop=function(){function l(a){throw Error("Error: Line "+(m-c.split("\n").length)+":\n"+a);}function i(a){r("Warning: Line "+(m-c.split("\n").length)+":\n"+a)}function e(){g=null;a:for(;;){var a=[/^''/,/^<=/,/^[+*!=<>(){}":;,.-]/,/^\[/,/^\]/,/^DEFINE\b/,/^PROCEDURE\b/,/^BLOCK\b/,/^LOOP\b/,/^AT\b/,/^MOST\b/,/^TIMES\b/,/^MU_LOOP\b/,/^CELL\b/,/^OUTPUT\b/,/^YES\b/,/^NO\b/,/^QUIT\b/,/^ABORT\b/,/^IF\b/,/^THEN\b/,/^AND\b/,/^OR\b/,/^PRINT\b/];if(c.match(/^$/))return false;if(c.match(/^\/\*.*?\*\//)){c=
c.replace(/^\/\*.*\*\//,"");continue a}if(c.match(/^BLOCK\s+(\d+)\s*:\s*BEGIN/)){d="BEGIN";g=c.match(/^BLOCK\s+(\d+)\s*:\s*BEGIN/)[1];c=c.replace(/^BLOCK\s+(\d+)\s*:\s*BEGIN/,"");break a}if(c.match(/^BLOCK\s+(\d+)\s*:\s*END/)){d="END";g=c.match(/^BLOCK\s+(\d+)\s*:\s*END/)[1];c=c.replace(/^BLOCK\s+(\d+)\s*:\s*END/,"");break a}for(var b=0,e=a.length;b<e;b++)if(c.match(a[b])){d=c.match(a[b])[0];c=c.replace(a[b],"");break a}if(c.match(/^\s+/)){c=c.replace(/^\s+/,"");continue a}if(c.match(/^[A-Z]\w*/)){d=
"ID";g=c.match(/^[A-Z]\w*/)[0];c=c.replace(/^[A-Z]\w*/,"");break a}if(c.match(/^\d+/)){d="NUMBER";g=c.match(/^\d+/)[0];c=c.replace(/^\d+/,"");break a}if(c.match(/^'/)){for(a="";;){if(c.search(/^'[^']*'/)==-1)break;a+=c.match(/^'[^']*'/)[0];c=c.replace(/^'[^']*'/,"")}d="STRING";g=a.substring(1,a.length-1);break a}invChar=c.match(/^./);invChar=invChar[0];invChar=invChar.replace(/_/g,"-");invChar=invChar.replace(/q/g,"?");l("BlooP: invalid character "+invChar);c=c.replace(/^./,"");break a}}function t(a,
b){return a=="BEGIN"||a=="END"?"BLOCK "+b+": "+a:b==""?a:a+" "+b}function f(a){var b=g;a!=d&&i("expected "+t(a,g)+", got "+t(d,""));e();return b}function n(){if(d=="BEGIN"){var a=g,s="";h[a]==y?(h[a]=z,b+="BLOCK"+a+": {\n"):h[a]==z||h[a]==o?i("BLOCK "+a+" appears twice"):h[a]==u&&(h[a]=o);for(e();d!="END";)n();s=g;a==s&&v("Notice: Line "+(m-c.split("\n").length)+":\n"+("BLOCK "+a+": BEGIN matches with BLOCK "+s+": END"));e();h[a]!=o&&h[a]!=p&&(b+="}\n");d==";"&&e()}else if(d=="LOOP")a="",e(),d=="AT"&&
(e(),f("MOST"),a=1),a&&(b+="BLOCK#: "),b+="for (var counter = 0, ",b+="limit = ",j(),b+="; counter < limit; counter++) {\n",f("TIMES"),f(":"),a&&(d!="BEGIN"&&i("LOOP AT MOST requires following BLOCK"),b=b.replace(/#/,g),h[g]=u),n(),b+="}\n";else if(d=="MU_LOOP")B=="BlooP"&&l("MU-LOOP not supported -- use FlooP"),a=0,e(),f(":"),d!="BEGIN"&&i("LOOP requires following BLOCK"),a=g,b+="BLOCK"+a+": while (true) {\n",h[a]=u,n(),b+="}\n",h[a]!=p&&i("FlooP: MU-LOOP without ABORT LOOP may run forever");else if(d==
"QUIT")a="",e(),f("BLOCK"),a=f("NUMBER"),h[a]==y&&l("QUIT BLOCK refers to non-existent BLOCK"),b+="break BLOCK"+a+";\n",f(";");else if(d=="ABORT")a="",e(),f("LOOP"),a=f("NUMBER"),h[a]!=o&&h[a]!=p&&l("ABORT LOOP on non-abortable loop or non-loop"),b+="break BLOCK"+a+";\n",f(";"),h[a]=p;else if(d=="IF"){b+="if (";e();if(d=="{"){for(e();;)if(j(),d=="AND")b+=" && ",e();else if(d=="OR")b+=" || ",e();else break;f("}")}else j();b+=") {\n";f(",");f("THEN");f(":");n();b+="}\n"}else if(d=="PRINT"){e();f("[");
for(b+="BFloop.printstring(";;){j();if(d!=",")break;e();b+=", "}f("]");b+=");\n";d==";"&&e()}else a:{if(d=="OUTPUT")b+="output",e();else if(d=="CELL")A();else{for(l("invalid syntax");d!=";";)e();e();break a}f("<=");b+=" = ";j();b+=";\n";d==";"&&e()}}function j(){if(d=="STRING")g=g.replace("\\","\\\\"),g=g.replace("'","\\'"),b+="'"+g+"'",e();else if(d=="YES")b+="1",e();else if(d=="NO")b+="0",e();else for(;;){for(;;){for(;;){if(d=="CELL")A();else if(d=="OUTPUT")b+="output",e();else if(d=="ID"){var a=
g;e();if(d=="["){e();for(b+=a+"(";;){j();if(d!=",")break;e();b+=", "}f("]");b+=")"}else{for(var c=0,h=k.length;c<h;c++){if(k[c]==a)break;c==h-1&&(a=a.replace(/q/,"?"),a=a.replace(/_/,"-"),i("unknown variable "+a))}b+=a}}else d=="NUMBER"?b+=g:i("unexpected "+t(d,g)+" found"),e();if(d!="*")break;e();b+=" * "}if(d!="+")break;e();b+=" + "}if(d=="=")b+=" == ";else if(d=="<")b+=" < ";else if(d==">")b+=" > ";else break;e()}}function A(){e();f("(");b+="cell["+f("NUMBER")+"]";f(")")}var B="BlooP",c=null,m=
null,d=null,g=null,b="",w="",k=[],h=[],y=null,z=1,u=2,o=3,p=4,q=function(){},x,r,v;x=errorFunc=r=v=q;return{init:function(a,b,c){x=a||q;r=b||q;v=c||q},compile:function(a){c=m=w=b="";c=a;if(!c)return false;c=c.toUpperCase();c=c.replace(/\?/g,"q");c=c.replace(/-/g,"_");c=c.replace(RegExp(String.fromCharCode(8656),"g"),"<=");c=c.replace(RegExp(String.fromCharCode(215),"g"),"*");for(m=c.split("\n").length+1;!c.match(/^$/);){b="";k=h=[];e();if(d=="DEFINE"){a="";e();f("PROCEDURE");f("''");a=f("ID");b+=
"function "+a;a=a.replace(/q/,"?");a.replace(/_/g,"-");f("''");f("[");for(k=[];;){k.push(f("ID"));if(d!=",")break;e()}b+="("+k.join(", ")+")";f("]");f(":");b+=" {\n";b+="var cell = new Array();\n";b+="var output = 0;\n";n();b+="return output;\n";b+="}\n\n"}else j(),b.match(/q/)&&(b+=' ? "YES" : "NO"'),b+=";\n";d!="."&&i("excess junk at end of function");w+=b}return w},printstring:function(){for(var a=" > ",b=0;b<arguments.length;b++)a+=arguments[b];x(a+"\n")}}}();
