/*


 JS-Forth
 http://www.forthfreak.net/index.cgi?jsforth
 Licensed under th GNU GPL.

 Disclaimer: JS-Forth is delivered as-is. No warranties,
 implicit or explicit, towards its function, usability, fitness
 for any purpose are given. It is distributed for educative
 purposes, you may study it to your hearts delight. Should
 you plan to execute JS-Forth on any computer, you declare
 to not hold the programmer liable in any way for any damage
 JS-Forth may cause, be it to that computer, peripherals, or any
 other object in the range of several thousand kilometers, or
 more. The person initiating execution of JS-Forth is the one
 carrying sole responsibility for all and any damage resulting
 from this action. Also, you do not hold the programmer liable
 for any damage resulting from the study of JS-Forth.  Please
 do not stick your tongue into the power supply of the computer
 which is running JS-Forth.

 By opening JS-Forth for reading or execution, you make a full
 statement that you have read and understood all of the above
 disclaimer, and proceed willingly, volunteerily, and of your
 own choice on your own risk and responsability.

 Having said that, I can assure you that JS-Forth has not been
 written to perform any malicious action on your computer or
 anyone elses. I run Js-Forth frequently, and no damage has
 occured from doing so, though no extensive testing has been
 done on it as a whole yet. Those parts which work do so in a
 pretty stable manner. A major version jump to v0.01 may be imminent.
*/
var version="0",subversion="5200804171342",title="## JS-Forth "+version+"."+subversion+" ##",memend=1048576,maxcookies=25,cookiebasename="jsrepl-jsforth",cookieexpirationdate=Date(Date.now()+15768E7),infolines=1E3,paddistance=512,padsize=512,maxbufs=2,blocktimeout=5E3,backspace=8,tab=9,carriagereturn=13,esc=27,bl=32,suspended=-1,dp=0,catchframe=0,wc=0,inbuf=[],linelen=80,lines=30,linelen2=55,lines2=lines,screensize=lines*linelen,tibsize=linelen+1,dictionaryfull=memend-(paddistance+padsize),usedchunk=
[],freechunk=[],heapend=memend,immediate=1,smudgebit=2,precedencebit=immediate,s=[],r=[],m=[],h=[],hf=[],x=[],t=[],sourceid=[];h[0]="";var f=[],ip,w,sp=0,rp=0,tos,ftos,standard=[],nextvocabulary=1,uncertain=nextvocabulary;standard[uncertain]="   possibly other, need to look that up first";nextvocabulary<<=1;var fig=nextvocabulary;standard[fig]="fig";nextvocabulary<<=1;var f79=nextvocabulary;standard[f79]="f79";nextvocabulary<<=1;var f83=nextvocabulary;standard[f83]="f83";nextvocabulary<<=1;
var ans=nextvocabulary;standard[ans]="dpans94";nextvocabulary<<=1;var foerthchen=nextvocabulary;standard[foerthchen]="FOeRTHchen";nextvocabulary<<=1;var jsf=nextvocabulary;standard[jsf]="JS-Forth";var higheststandard=nextvocabulary,any=ans|f83|f79|fig|jsf;nextvocabulary<<=1;var only=nextvocabulary;nextvocabulary<<=1;var forth=nextvocabulary;nextvocabulary<<=1;var hidden=nextvocabulary;nextvocabulary<<=1;var teststuff=nextvocabulary,lastsystemvocabulary=nextvocabulary,vocstack=[],vocname=[];
function printvocname(a){for(var b=0,c=only;c!=1073741824;c<<=1){if(c==a){type(h[vocname[b]]+" ");break}b++}}function jscomma(a){m[dp++]=a;return dp-1}function jshiallot0(a){for(var b=a;b;b--)m[heapend++]=0;return heapend-a}
for(var casesensitive=jscomma(0),debugging=jscomma(0),warnings=jscomma(-1),compliance=jscomma(jsf),fittype=jscomma(0),outfile=jscomma(-1),blk=jscomma(-1),scr=jscomma(0),context=jscomma(forth),current=jscomma(forth),lastxt=jscomma(0),base=jscomma(10),state=jscomma(0),innerloop=jscomma(0),innercase=jscomma(0),span=jscomma(0),toin=jscomma(0),hashtib=jscomma(0),tib=jshiallot0(tibsize),parsebuf,parsebuflen,nextbuf=0,buf=[],bufdirty=[],bufblk=[],blockstat=[],ds=[],dse=[],lineofspaces="",i=0;i<linelen;i++)lineofspaces+=
" ";function describe(a,b){dse[wc]=a;ds[wc]=0|m[current];b&&(ds[wc]=b|m[current])}function printinfos(){}function info(){}function debug(a){m[debugging]&&info(a)}function _print(a){document.terminal.dialog.value+=a}function type(a){_print(a)}var write=type;function cr(){_print("\n")}function cls(){}function backspaces(){}function emit(a){type(String.fromCharCode(a))}var querytype=type,src=[];function from(){return suspended?-2:m[blk]>=0?m[blk]*1024+m[toin]:-1}
function newheader(a,b){h[++wc]=a;src[wc]=from();hf[wc]=b;x[wc]=dp;m[lastxt]=wc;ds[wc]=any|foerthchen|m[current];dse[wc]="";debug("compiling: "+a)}function nextprimitive(){x[w]()}function nexthilevel(){w=x[w];x[m[w]]()}function nextconstant(){s[++sp]=tos;tos=m[x[w]+1]}function nextvariable(){s[++sp]=tos;tos=x[w]+1}function primitive(a,b,c){newheader(a,c|smudgebit);x[wc]=b;t[wc]=nextprimitive;return wc}function headerless(){h[wc]=""}definitions(hidden);
function pack(a,b){w="";for(var c=b;c;c--)w+=String.fromCharCode(m[a++]);return w}function forthpack(){tos=pack(s[sp--],tos)}var x_pack=primitive("pack",forthpack);describe("a n -- x",jsf);function unpackstring(a,b){for(var c=a.length,d=b+c,e=c;e;m[--d]=a.charCodeAt(--e));return c}function unpack(){var a=s[sp--];w=a.length;tos+=w;for(var b=w;b;m[--tos]=a.charCodeAt(--b));tos=w}var x_unpack=primitive("unpack",unpack);describe("x a -- n",jsf);function definitions(a){m[current]=a}definitions(forth);
function forthstackeffect(){s[++sp]=dp;tos=dse[tos]?unpackstring("( "+dse[tos]+" )",dp):0}primitive("stackeffect",forthstackeffect);describe("xt -- a n",jsf);definitions(hidden);function forthstorestackeffect(){forthpack();dse[m[lastxt]]=tos;tos=s[sp--]}var x_storestackeffect=primitive("stackeffect!",forthstorestackeffect);describe("a n --",jsf);definitions(forth);function forthinfo(){info(pack(s[sp--],tos));tos=m[sp--]}primitive("info",forthinfo);describe("a n --",jsf);var clock;
function forthstartclock(){clock=(new Date).getTime()}primitive("startclock",forthstartclock);describe("--",jsf);function forthelapsed(){w=(new Date).getTime();s[++sp]=tos;tos=w-clock}primitive("elapsed",forthelapsed);describe("-- u",jsf);definitions(forth);function forthfig(){m[compliance]=fig}primitive("fig",forthfig);describe("--",jsf);function forthfoerthchen(){m[compliance]=foerthchen}primitive("foerthchen",forthfoerthchen);describe("--",jsf);function forthf79(){m[compliance]=f79}
primitive("f79",forthf79);describe("--",jsf);function forthf83(){m[compliance]=f83}primitive("f83",forthf83);describe("--",f83|jsf);function forthans(){m[compliance]=ans}primitive("ans",forthans);describe("--",jsf);function forthjsforth(){m[compliance]=jsf}primitive("jsf",forthjsforth);describe("--",any|foerthchen);definitions(hidden);function forthnest(){r[++rp]=ip;ip=++w}var x_nest=primitive("(nest)",forthnest);describe("--",jsf);definitions(forth);function forthunnest(){ip=r[rp--]}
var x_unnest=primitive("exit",forthunnest);describe("--",any);
var customerror=[],systemerror=[,"aborted","aborted","stack overflow","stack underflow","return stack overflow","return stack underflow","do loops nested too deeply","dictionary overflow","invalid memory address","division by zero","result out of range","argument type mismatch","word not found","use only during compilation","invalid forget","attempt to use zero-length string as name","pictured numeric ouput string overflow","pictured numeric ouput string overflow","word name too long","write to a read-only location",
"unsupported operation","unstructured","address alignment exception","invalid numeric argument","return stack imbalance","loop parameters unavailable","invalid recursion","user interrupt","compiler nesting","obsolescent feature",">BODY used on non-CREATEd definition","invalid name argument","Block read exception","Block write exception","Invalid block number","Invalid file position","File I/O exception","File not found"];systemerror[64]="use only while interpreting";systemerror[65]="executed BODY> on a non-body address";
systemerror[66]="unstructured";systemerror[67]="TO must be used on a VALUE";systemerror[68]="JavaScript boo, mostly the result of uninitialized memory access";systemerror[69]="Too many vocabularies";systemerror[70]="No cookie by that name found";systemerror[71]="Can't write to read-only block";systemerror[72]="Invalid memory region specifier, or heap corrupted";
function errordialog(a){return a<0?systemerror[-a]?"error("+a+"): "+systemerror[-a]:"error #"+a:customerror[a]?"error: "+customerror[a]:"error #"+a}function _error(a){info(a)}function exception(a){var b;m[blk]>=0?(b=m[toin]%64,b=pack(parsebuf+m[toin]-b,b)):b=pack(parsebuf,m[toin]);_error(b+": "+errordialog(a));debug("issuing timed event 'warmstart vm in 1 ms'");suspended=warm;setTimeout(function(){virtualmachine(warm)},1);tos=s[sp--]}definitions(hidden);
function forththrow0(){catchframe=r[rp];sp=r[--rp];ip=r[--rp];rp--;tos=0}var brthrow0=dp;m[dp++]=primitive("throw0",forththrow0);definitions(forth);function forthcatch(){r[++rp]=ip;r[++rp]=sp;r[++rp]=catchframe;catchframe=rp;r[++rp]=brthrow0;forthexecute()}var x_catch=primitive("catch",forthcatch);describe("xn ... x0 a -- xn ... x0 n",ans|jsf);function throwerror(a){catchframe?(tos=a,rp=catchframe,catchframe=r[rp--],sp=r[rp--],ip=r[rp--]):exception(a)}
function forththrow(){tos!=0?throwerror(tos):tos=s[sp--]}var x_throw=primitive("throw",forththrow);describe("n --",ans|jsf|f83);function forthnewerror(){tos<0?systemerror[-tos]=pack(s[sp-1],s[sp]):customerror[tos]=pack(s[sp-1],s[sp]);sp-=2;tos=s[sp--]}primitive("newerror",forthnewerror);describe("a n1 n2 --",jsf);definitions(hidden);function forthdolit(){s[++sp]=tos;tos=m[ip++]}var x_lit=primitive("(lit)",forthdolit);function forthbrsquote(){s[++sp]=tos;tos=m[ip++];s[++sp]=ip;ip+=tos}
var x_brsquote=primitive('(s")',forthbrsquote);function forthbrcquote(){s[++sp]=tos;tos=ip++;ip+=m[tos]}var x_brcquote=primitive('(c")',forthbrcquote);function forthbrdotquote(){forthbrsquote();forthpack();type(tos);tos=s[sp--]}var x_brdotquote=primitive('(.")',forthbrdotquote);function forthdovar(){s[++sp]=tos;tos=++w}var x_dovar=primitive("(var)",forthdovar);function forthdoconst(){s[++sp]=tos;tos=m[++w]}var x_doconst=primitive("(const)",forthdoconst),x_dovalue=primitive("(value)",forthdoconst);
function forthdofconst(){f.push(ftos);ftos=m[++w]}var x_dofconst=primitive("(fconst)",forthdofconst);function forthbranch(){ip+=m[ip]}var x_branch=primitive("(branch)",forthbranch);function forth0branch(){tos?ip++:ip+=m[ip];tos=s[sp--]}var x_0branch=primitive("(0branch)",forth0branch);
function forthwarminit(){tos=r[rp];rp=0;r[rp+1]=0;r[rp]=tos;sp=tos=0;s[sp+1]=0;s[sp]=tos;for(ftos=0;f.length;f.pop());catchframe=0;m[state]=0;m[innerloop]=0;m[innercase]=0;m[blk]=-1;for(m[outfile]=-1;inbuf.length;inbuf.pop());}var x_warminit=primitive("warminit",forthwarminit);function forthbrabortquote(){tos?(forthbrsquote(),forthpack(),systemerror[2]=tos,throwerror(-2)):(tos=s[sp--],ip+=m[ip]+1)}var x_brabortquote=primitive('(abort")',forthbrabortquote);
function forthbrto(){m[m[ip++]]=tos;tos=s[sp--]}var x_brto=primitive("(to)",forthbrto);function jsdotquote(){type(m[ip++])}var dotquote=primitive("",jsdotquote);definitions(forth);function forthdup(){s[++sp]=tos}var x_dup=primitive("dup",forthdup);describe("x -- x x",any|foerthchen);function forthqdup(){tos&&(s[++sp]=tos)}var x_qdup=primitive("?dup",forthqdup);describe("x -- 0 | x x",any);function forthdrop(){tos=s[sp--]}var x_drop=primitive("drop",forthdrop);describe("x --",any|foerthchen);
function forthswap(){w=s[sp];s[sp]=tos;tos=w}var x_swap=primitive("swap",forthswap);describe("x1 x2 -- x2 x1",any|foerthchen);function forthover(){s[++sp]=tos;tos=s[sp-1]}var x_over=primitive("over",forthover);describe("x1 x2 -- x1 x2 x1",any);function forthrot(){w=s[sp];s[sp]=tos;tos=s[sp-1];s[sp-1]=w}var x_rot=primitive("rot",forthrot);describe("x1 x2 x3 -- x2 x3 x1",any);function forthminrot(){w=s[sp-1];s[sp-1]=tos;tos=s[sp];s[sp]=w}primitive("-rot",forthminrot);
describe("x1 x2 x3 -- x3 x1 x2",jsf);function forthtuck(){w=s[sp];s[sp]=tos;s[++sp]=w}var x_tuck=primitive("tuck",forthtuck);describe("x1 x2 -- x2 x1 x2",ans|jsf);function forthnip(){sp--}var x_nip=primitive("nip",forthnip);describe("x1 x2 -- x2",ans|jsf);function forth2dup(){s[++sp]=tos;s[++sp]=s[sp-2]}var x_2dup=primitive("2dup",forth2dup);describe("x1 x2 -- x1 x2 x1 x2",any);function forth2drop(){sp--;tos=s[sp--]}var x_2drop=primitive("2drop",forth2drop);describe("x1 x2 --",any);
function forth2swap(){w=s[sp-1];s[sp-1]=tos;tos=w;w=s[sp-2];s[sp-2]=s[sp];s[sp]=w}primitive("2swap",forth2swap);describe("x1 x2 x3 x4 -- x3 x4 x1 x2",any);function forth2over(){s[++sp]=tos;tos=s[sp-3];s[++sp]=tos;tos=s[sp-3]}primitive("2over",forth2over);describe("x1 x2 x3 x4 -- x1 x2 x3 x4 x1 x2",any);function forthmin(){tos=Math.min(s[sp--],tos)}var x_min=primitive("min",forthmin);describe("n1 n2 -- n3",any);function forthmax(){tos=Math.max(s[sp--],tos)}primitive("max",forthmax);
describe("n1 n2 -- n3",any);function forthtor(){r[++rp]=tos;tos=s[sp--]}var x_tor=primitive(">r",forthtor);describe("x --",any|foerthchen);function forthrfrom(){s[++sp]=tos;tos=r[rp--]}var x_rfrom=primitive("r>",forthrfrom);describe("-- x",any|foerthchen);function forthrfetch(){s[++sp]=tos;tos=r[rp]}var x_rfetch=primitive("r@",forthrfetch);describe("-- x",any);function forthrdrop(){rp--}var x_rdrop=primitive("rdrop",forthrdrop);describe("-- x",jsf);
function forth2tor(){r[++rp]=s[sp--];r[++rp]=tos;tos=s[sp--]}var x_2tor=primitive("2>r",forth2tor);describe("x1 x2 --",ans|jsf|uncertain);function forth2rfrom(){s[++sp]=tos;tos=r[rp--];s[++sp]=r[rp--]}var x_2rfrom=primitive("2r>",forth2rfrom);describe("-- x1 x2",ans|jsf|uncertain);function forth2rfetch(){s[++sp]=tos;tos=r[rp];s[++sp]=r[rp-1]}var x_2rfetch=primitive("2r@",forth2rfetch);describe("-- x1 x2",ans|jsf|uncertain);function forthdepth(){s[++sp]=tos;tos=sp-1}var x_depth=primitive("depth",forthdepth);
describe("-- n",ans|f83|jsf|uncertain);function forthpick(){tos=s[sp-tos]}primitive("pick",forthpick);describe("xu ... x1 x0 u -- xu ... x1 x0 xu",any);function forthroll(){for(w=s[sp-tos];tos;--tos)s[sp-tos]=s[sp-tos+1];sp--;tos=w}primitive("roll",forthroll);describe("xu xu-1 ... x0 u -- xu-1 ... x0 xu",any);function forthfetch(){tos=m[tos]}var x_fetch=primitive("@",forthfetch);describe("a -- x",any|foerthchen);function forthstore(){m[tos]=s[sp--];tos=s[sp--]}var x_store=primitive("!",forthstore);
describe("x a --",any|foerthchen);function forth2fetch(){s[++sp]=m[tos+1];tos=m[tos]}var x_2fetch=primitive("2@",forth2fetch);describe("a -- d",any);function forth2store(){m[tos++]=s[sp--];m[tos]=s[sp--];tos=s[sp--]}var x_2store=primitive("2!",forth2store);describe("d a --",any);function forthcfetch(){tos=m[tos]&255}var x_cfetch=primitive("c@",forthcfetch);describe("a -- c",any);function forthcstore(){m[tos]=s[sp--]&255;tos=s[sp--]}var x_cstore=primitive("c!",forthcstore);describe("c a --",any);
function forthcount(){s[++sp]=tos+1;tos=m[tos]&255}var x_count=primitive("count",forthcount);describe("a1 -- a2 c",any);function forthskim(){s[++sp]=tos+1;tos=m[tos]}var x_skim=primitive("skim",forthskim);describe("a1 -- a2 x",jsf);function forthexchange(){w=m[tos];m[tos]=s[sp--];tos=w}var x_exchange=primitive("exchange",forthexchange);describe("x1 a -- x2",jsf);function forthon(){m[tos]=-1;tos=s[sp--]}primitive("on",forthon);describe("a --",jsf);function forthoff(){m[tos]=0;tos=s[sp--]}
var x_off=primitive("off",forthoff);describe("a --",jsf);function forthfill(){i=s[sp--];for(var a=s[sp--];i;i--)m[a++]=tos;tos=s[sp--]}var x_fill=primitive("fill",forthfill);describe("a u c --",any);function fortherase(){s[++sp]=tos;tos=0;forthfill()}primitive("erase",fortherase);describe("a u --",any);function forthslashstring(){w=tos;tos=s[sp--];tos<w&&(w=tos);s[sp]+=w;tos-=w}var x_slashstring=primitive("/string",forthslashstring);describe("a1 n1 u -- a2 n2",ans|jsf|uncertain);
function noop(){}primitive("align",noop|immediate);describe("--",ans|jsf);primitive("aligned",noop|immediate);describe("a1 -- a2",ans|jsf);function forthpad(){s[++sp]=tos;tos=dp+paddistance}primitive("pad",forthpad);describe("-- a",any);var x_cr=primitive("cr",cr);describe("--",any);definitions(forth);function forthspaces(){for(;tos>linelen;tos-=linelen)type(lineofspaces);type(lineofspaces.substring(0,tos));tos=s[sp--]}var x_spaces=primitive("spaces",forthspaces);describe("n --",any);definitions(hidden);
definitions(forth);function forthspace(){type(" ")}var x_space=primitive("space",forthspace);describe("--",any);function forthemit(){emit(tos);tos=s[sp--]}var x_emit=primitive("emit",forthemit);describe("c --",any|foerthchen);function forthtype(){forthpack();type(tos);tos=s[sp--]}var x_type=primitive("type",forthtype);describe("--",any);var x_page=primitive("page",cls);describe("--",ans|f83|jsf);primitive("cls",cls);describe("--",jsf);function _prompt(){}function forthprompt(){_prompt()}
var x_prompt=primitive("prompt",forthprompt);describe("--",any);function forthdots(){s[++sp]=tos;for(var a=1;a<sp;type(s[++a].toString(m[base])+" "));sp--}var x_dots=primitive(".s",forthdots);describe("--",any);function forthparse(){var a=tos;w=m[toin]+parsebuf;var b=parsebuf+parsebuflen,c=m[w];if(a==bl)for(;w<b;){if(c!=a)break;c=m[++w]}for(s[++sp]=w;w<b;){c=m[w];if(c==a)break;w++}tos=w-s[sp];c==a&&w++;m[toin]=w-parsebuf}var x_parse=primitive("parse",forthparse);describe("c -- a n",ans|jsf);definitions(hidden);
function forthkey1(){inbuf.length||(suspended=w,_input(function(){virtualmachine(ip)}))}var x_key1=primitive("key1",forthkey1);describe("--",jsf);function forthkey2(){s[++sp]=tos;tos=inbuf.shift()}var x_key2=primitive("key2",forthkey2);describe("-- c",jsf);function forthkey1query(){inbuf.length||(suspended=w,setTimeout(function(){virtualmachine(ip)},0))}var x_key1query=primitive("key1?",forthkey1query);describe("--",jsf);function forthkey2query(){s[++sp]=tos;tos=0;inbuf.length&&tos--}
var x_key2query=primitive("key2?",forthkey2query);describe("-- f",jsf);function forthacceptprintable(){w=tos;tos=s[sp--];tos>1&&(m[s[sp]]=w,s[sp]++,tos--)}function forthacceptescape(){tos=s[sp--];tos+=s[sp]-s[sp-1];backspaces(s[sp]-s[sp-1]);s[sp]=s[sp-1]}function forthacceptbackspace(){tos=s[sp--];s[sp]>s[sp-1]&&(tos++,s[sp]--,backspaces(1))}function forthacceptreturn(){sp--;tos=0}function forthaccepttab(){tos=bl;forthacceptprintable()}
function forthacceptcontrolchar(a){a==esc?forthacceptescape():a==backspace?forthacceptbackspace():a==17?forthacceptbackspace():a==carriagereturn?forthacceptreturn():a==tab?forthaccepttab():tos=s[sp--]}function forthdecode(){tos<bl?forthacceptcontrolchar(tos):forthacceptprintable(tos);debug(s[sp-1]+" "+s[sp]+" "+tos)}var x_decode=primitive("decode",forthdecode);describe("a1 a2 n1 c -- a1 a3 n2 f",jsf);definitions(forth);function forthfast(){m[outfile]=-1}primitive("fast",forthfast);describe("--",jsf);
function forthslow(){m[outfile]=-2}primitive("slow",forthslow);describe("--",jsf);function forthsource(){s[++sp]=tos;s[++sp]=parsebuf;tos=parsebuflen}var x_source=primitive("source",forthsource);describe("-- a n",any);function forthstoresource(){parsebuflen=tos;parsebuf=s[sp--];tos=s[sp--]}var x_storesource=primitive("!source",forthstoresource);describe("a n --",jsf);definitions(hidden);function forthpushsource(){sourceid.push(m[toin],parsebuf,parsebuflen)}
var x_pushsource=primitive("pushsource",forthpushsource);function forthpopsource(){parsebuflen=sourceid.pop();parsebuf=sourceid.pop();m[toin]=sourceid.pop()}for(var x_popsource=primitive("popsource",forthpopsource),translatedchar=[],i=0;i<256;i++)translatedchar[i]="";translatedchar[0]="A";translatedchar[9]="B";translatedchar[10]="C";translatedchar[13]="D";translatedchar[32]="E";translatedchar[37]="F";translatedchar[59]="G";var translatechar=[0,9,10,13,32,37,59];
function encoded(a){var b="",c;for(i=0;i<a.length;i++)c=a.charCodeAt(i),b+=translatedchar[c]?"%"+translatedchar[c]:a.charAt(i);return b}function decoded(a){var b="",c;for(i=0;i<a.length;i++)c=a.charAt(i),c=="%"&&(c=String.fromCharCode(translatechar[a.charCodeAt(++i)-65])),b+=c;return b}function setcookie(a,b,c,d,e,g){a=a+"="+encoded(b.substr(0,2048));a+=c?"; domain="+c:"";a+=d?"; expires="+d:"";a+=e?"; path="+c:"";a+=g?"; secure="+c:"";document.cookie=a}
function readcookie(a){var b=document.cookie.indexOf(a+"=");if(b==-1)return null;a=document.cookie.substr(b+a.length+1);b=a.indexOf(";");return b!=-1?decoded(a.substr(0,b)):decoded(a)}definitions(forth);function forthsetcookie(){setcookie(pack(s[sp-2],s[sp-1]),pack(s[sp],tos));sp-=3;tos=s[sp--]}primitive("cookie!",forthsetcookie);describe("a1 n1 a2 n2 --",jsf);function forthreadcookie(){(w=readcookie(pack(s[sp-1],s[sp])))?(s[--sp]=w,unpack()):throwerror(-70)}primitive("cookie@",forthreadcookie);
describe("a1 n1 a2 -- n2",jsf);definitions(forth);function forth1plus(){tos++}var x_1plus=primitive("1+",forth1plus);describe("x -- x+1",ans|f83|jsf);primitive("cell+",forth1plus);describe("x -- x+cell",ans|f83|jsf);primitive("char+",forth1plus);describe("x -- x+char",ans|jsf);function forth1minus(){tos--}var x_1minus=primitive("1-",forth1minus);describe("x -- x-1",any);primitive("cell-",forth1minus);describe("x -- x-cell",ans|f83|jsf);function forth2mul(){tos<<=1}var x_2mul=primitive("2*",forth2mul);
describe("x1 -- x2",any);function forth2div(){tos>>=1}var x_2div=primitive("2/",forth2div);describe("n1 -- n2",any);function forthplus(){tos+=s[sp--]}var x_plus=primitive("+",forthplus);describe("x1 x2 -- x1+x2",any|foerthchen);function forthminus(){tos=s[sp--]-tos}var x_minus=primitive("-",forthminus);describe("x1 x2 -- x1-x2",any);function forthmul(){tos=tos*s[sp--]&4294967295}var x_mul=primitive("*",forthmul);describe("x1 x2 -- x1*x2",any|foerthchen);var floorfix=1-1.0E-16;
function forthdiv(){tos?(tos=s[sp--]/tos,tos<0&&(tos+=floorfix),tos=Math.floor(tos)):throwerror(-10)}var x_div=primitive("/",forthdiv);describe("x1 x2 -- x1/x2",any);function forthstarslash(){tos?(tos=s[sp--]*s[sp--]/tos,tos<0&&(tos+=floorfix),tos=Math.floor(tos)):throwerror(-10)}var x_starslash=primitive("*/",forthstarslash);describe("x1 x2 x3 -- x1*x2/x3",any);function forthmod(){tos?tos=s[sp--]%tos:throwerror(-10)}var x_mod=primitive("mod",forthmod);describe("x1 x2 -- x3",any);
function forthslashmod(){tos?(w=s[sp]%tos,tos=s[sp]/tos,tos<0&&(tos+=floorfix),tos=Math.floor(tos),s[sp]=w):throwerror(-10)}var x_slashmod=primitive("/mod",forthslashmod);describe("x1 x2 -- x3 x4",any|foerthchen);function forthstarslashmod(){tos?(w=s[sp--]*s[sp],s[sp]=w%tos,tos=w/tos,tos<0&&(tos+=floorfix),tos=Math.floor(tos)):throwerror(-10)}var x_starslashmod=primitive("*/mod",forthstarslashmod);describe("x1 x2 x3 -- x4 x5",any);function forthnegate(){tos=-tos}var x_negate=primitive("negate",forthnegate);
describe("n -- -n",any);function forthabs(){tos=Math.abs(tos)}var x_abs=primitive("abs",forthabs);describe("n -- u",any);function forthlshift(){tos>31?(tos=0,sp--):tos=s[sp--]<<tos}var x_lshift=primitive("lshift",forthlshift);describe("x1 u --x2",ans|f83|jsf);primitive("<<",forthlshift);describe("x1 u -- x2",jsf);function forthrshift(){tos>31?(tos=0,sp--):tos=s[sp--]>>>tos}var x_rshift=primitive("rshift",forthrshift);describe("u1 u2 -- x3",ans|f83|jsf);primitive(">>",forthrshift);
describe("u1 u2 -- u3",jsf);function forthplusstore(){m[tos]+=s[sp--];tos=s[sp--]}var x_plusstore=primitive("+!",forthplusstore);describe("x a --",any);primitive("cells",noop,immediate);describe("x1 -- x2",ans|f83|jsf);primitive("chars",noop,immediate);describe("x1 -- x2",ans|jsf);function forthrange(){var a=tos;tos=s[sp];s[sp]+=a}var x_range=primitive("range",forthrange);describe("x n -- x+n x",ans|jsf|f83);function forthstod(){s[++sp]=tos;tos&=2147483648;tos&&(tos=-1)}
var x_stod=primitive("s>d",forthstod);describe("x -- d",any);function forthdnegate(){tos=-tos;s[sp]=-s[sp];s[sp]&&tos--}primitive("dnegate",forthdnegate);describe("d1 -- -d1",any);function forthdabs(){tos<0&&(tos=-tos,s[sp]=-s[sp],s[sp]&&tos--)}var x_dabs=primitive("dabs",forthdabs);describe("d -- ud",any);
function forthdplus(){tos<0&&(tos+=4294967296);var a=s[sp--];a<0&&(a+=4294967296);var b=s[sp--];b<0&&(b+=4294967296);var c=s[sp];c<0&&(c+=4294967296);tos+=b;w=c+a;w>4294967296&&(w&=4294967295,tos++);s[sp]=w;tos&=4294967295}var x_dplus=primitive("d+",forthdplus);describe("d1 d2 -- d1+d2",any);function forthummul(){for(var a=0,b=0,c=s[sp],d=32;d;--d)b<<=1,a&2147483648&&b++,a<<=1,tos&2147483648&&(a+c>4294967295&&b++,a+=c),tos<<=1;s[sp]=a;tos=b}var x_ummul=primitive("um*",forthummul);
describe("n1 n2 -- ud",any);function forthmmul(){var a=tos<0^s[sp]<0;tos=Math.abs(tos);s[sp]=Math.abs(s[sp]);forthummul();a&&forthdnegate()}var x_mmul=primitive("m*",forthmmul);describe("n1 n2 -- d",any);function forthdless(){w=tos;tos=0;s[sp-1]<w?tos=-1:s[sp-1]==w&&s[sp-2]<s[sp]&&(tos=-1);sp-=3}primitive("d<",forthdless);describe("d1 d2 -- f",any);function forthdequ(){tos=-(tos==s[sp-1]&s[sp]==s[sp-2]);sp-=3}primitive("d=",forthdequ);describe("d1 d2 -- f",any);
function forthumslashmod(){var a=0,b=0,c=0;if(tos)for(c=2147483648;c;c>>>=1)if((tos&c)==0)break;for(var d=2;d;d--){for(var e=s[sp--];c;c>>>=1)b<<=1,e&c&&b++,a<<=1,b>=tos&&(b-=tos,a++);c=2147483648}tos=a;s[++sp]=b}primitive("um/mod",forthumslashmod);describe("d u1 -- u2 u3",any);function forthudslashmod(){w=tos;s[++sp]=0;forthumslashmod();s[++sp]=w;w=tos;tos=s[sp--];forthumslashmod();s[++sp]=tos;tos=w}var x_udslashmod=primitive("ud/mod",forthudslashmod);describe("d1 u1 -- u2 d2",jsf);definitions(forth);
function forthor(){tos|=s[sp--]}var x_or=primitive("or",forthor);describe("x1 x2 -- x3",any|foerthchen);function forthand(){tos&=s[sp--]}var x_and=primitive("and",forthand);describe("x1 x2 -- x3",any|foerthchen);function forthxor(){tos^=s[sp--]}primitive("xor",forthxor);describe("x1 x2 -- x3",any|foerthchen);function forthinvert(){tos^=-1}primitive("invert",forthinvert);describe("x1 -- x2",ans|jsf);primitive("not",forthinvert);describe("x1 -- x2",fig|f79);function forthequ(){tos=-(tos==s[sp--])}
var x_equ=primitive("=",forthequ);describe("x1 x2 -- f",any);function forthnequ(){tos=-(tos!=s[sp--])}var x_nequ=primitive("<>",forthnequ);describe("x1 x2 -- f",any);function forthmore(){tos=-(tos<s[sp--])}var x_more=primitive(">",forthmore);describe("n1 n2 -- f",any);function forthless(){tos=-(tos>s[sp--])}var x_less=primitive("<",forthless);describe("n1 n2 -- f",any);function forth0equ(){tos=-(tos==0)}var x_0equ=primitive("0=",forth0equ);describe("x -- f",any);
function forth0nequ(){tos=-(tos!=0)}primitive("0<>",forth0nequ);describe("x -- f",any);function forth0less(){tos=-(tos<0)}var x_0less=primitive("0<",forth0less);describe("n -- f",any);function forth0greater(){tos=-(tos>0)}var x_0greater=primitive("0>",forth0greater);describe("n -- f",any);function forthuless(){w=s[sp--];tos<0&&(tos+=4294967296);w<0&&(w+=4294967296);tos=-(w<tos)}primitive("u<",forthuless);describe("u1 u2 -- f",any);
function forthumore(){w=s[sp--];tos<0&&(tos+=4294967296);w<0&&(w+=4294967296);tos=-(w>tos)}primitive("u>",forthumore);describe("u1 u2 -- f",any);function forthwithin(){w=s[sp--];var a=s[sp--],b=tos;tos=-1;if(!(w<b&&w<=a&&a<b)){if(w>b){if(w<=a)return;if(a<b)return}tos++}}primitive("within",forthwithin);describe("x1 x2 x3 -- f",any);var picturedoutpos,picturedoutlen;function forthlesshash(){picturedoutpos=dp+paddistance;picturedoutlen=0}var x_lesshash=primitive("<#",forthlesshash);describe("--",any);
function forthhold(){m[--picturedoutpos]=tos;picturedoutlen++;tos=s[sp--]}var x_hold=primitive("hold",forthhold);describe("c --",any);function forthsign(){tos<0&&(m[--picturedoutpos]=45,picturedoutlen++);tos=s[sp--]}var x_sign=primitive("sign",forthsign);describe("n --",any);function forthhashmore(){s[sp]=picturedoutpos;tos=picturedoutlen}var x_hashmore=primitive("#>",forthhashmore);describe("-- a n",any);definitions(hidden);
function dodoes(){s[++sp]=tos;tos=x[w];r[++rp]=ip;ip=m[tos++];w=m[ip++];t[w]()}function setdoes(){m[x[wc]]=ip+1;t[wc]=dodoes}var x_setdoes=primitive("setdoes",setdoes);definitions(hidden);function forthbrfor(){r[++rp]=tos;r[++rp]=tos;ip++;tos=s[sp--]}var x_brfor=primitive("(for)",forthbrfor);function forthbrnext(){r[rp]--;r[rp]?ip+=m[ip]:(ip++,rp-=2)}var x_brnext=primitive("(next)",forthbrnext);function forthbrdo(){r[++rp]=s[sp--];r[++rp]=tos;ip++;tos=s[sp--]}var x_brdo=primitive("(do)",forthbrdo);
function forthbrqdo(){tos==s[sp]?(sp--,ip+=m[ip]):(r[++rp]=s[sp--],r[++rp]=tos,ip++);tos=s[sp--]}var x_brqdo=primitive("(?do)",forthbrqdo);function forthbrleave79(){r[rp]=r[rp-1]-1}var x_brleave79=primitive("(leave)",forthbrleave79);function forthbrleave(){rp-=2;ip=m[ip];ip+=m[ip]}var x_brleave=primitive("(leave)",forthbrleave);function forthbrqleave(){tos?(rp-=2,ip=m[ip],ip+=m[ip]):ip++;tos=s[sp--]}var x_brqleave=primitive("(?leave)",forthbrqleave);
function forthbrloop(){r[rp]++;r[rp]!=r[rp-1]?ip+=m[ip]:(ip++,rp-=2)}var x_brloop=primitive("(loop)",forthbrloop);describe("--",jsf);function forthbrplusloop(){w=r[rp]-r[rp-1];r[rp]+=tos;tos=s[sp--];(r[rp]-r[rp-1]^w)>0?ip+=m[ip]:(ip++,rp-=2)}var x_brplusloop=primitive("(+loop)",forthbrplusloop);describe("n --",jsf);function forthbrunloop(){rp-=2}var x_brunloop=primitive("(unloop)",forthbrunloop);describe("--",jsf);function forthbrof(){w=tos;tos=s[sp--];w==tos?(tos=s[sp--],ip++):ip+=m[ip]}
var x_brof=primitive("(of)",forthbrof);describe("x1 x2 -- x1 |",jsf);definitions(forth);function forthexecute(){w=tos;tos=s[sp--];t[w]()}var x_execute=primitive("execute",forthexecute);describe("xt --",any);function forthperform(){w=m[tos];tos=s[sp--];t[w]()}var x_perform=primitive("perform",forthperform);describe("a --",jsf);function forthi(){s[++sp]=tos;tos=r[rp]}var x_i=primitive("i",forthi);describe("-- x",any);function forthj(){s[++sp]=tos;tos=r[rp-2]}var x_j=primitive("j",forthj);
describe("-- x",any);definitions(hidden);var controlflow=",if,,begin,while,do or ?do,for,case,of".split(","),controlflowwant=";else or then;then;while,until or again;repeat;loop or +loop;next;endcase;endof".split(";");function forthunstructured(){systemerror[66]="unstructured, missing "+controlflow[tos]+", expected "+controlflowwant[s[sp]];throwerror(-66)}var x_unstructured=primitive("unstructured",forthunstructured);definitions(forth);
function forthmove(){if(s[sp]>s[sp+1]){a=s[sp--]+tos;for(b=s[sp--]+tos;tos;tos--)m[--a]=m[--b]}else for(var a=s[sp--],b=s[sp--];tos;tos--)m[a++]=m[b++];tos=s[sp--]}var x_move=primitive("move",forthmove);describe("a1 a2 u --",any);primitive("cmove",forthmove);describe("a1 a2 u",any);definitions(hidden);function forthmovestr(){w=s[sp];m[tos++]=w;s[sp]=tos;tos=w;forthmove()}var x_movestr=primitive("move$",forthmovestr);describe("a1 n a2 --",jsf);definitions(forth);
function forthmintrailing(){var a=s[sp]+tos;for(i=tos;i;i--){if(m[--a]!=32)break;tos--}}var x_mintrailing=primitive("-trailing",forthmintrailing);describe("a1 u1 -- a2 u2",any);function forthdigit(){tos-=48;tos>9&&(tos<17&&(tos=-1),tos-=7);tos>41&&(tos-=32);tos>=0&&tos<m[base]||(tos=-1)}var x_digit=primitive("digit",forthdigit);describe("c -- u|-1",jsf);definitions(hidden);
function forthqsinglenumber(){var a,b=0,c=m[base],d=tos;tos=-1;w=s[sp];s[sp]=0;m[w]==45&&(b=-1,w++,d--);for(var d;d;d--){a=m[w++]-48;a==-2&&exception("no input support for floating point numbers yet");if(a>9){if(a<17){tos=0;break}a-=7}a>41&&(a-=32);if(a<0){tos=0;break}if(a>=c){tos=0;break}s[sp]*=c;s[sp]+=a}tos?(b&&(s[sp]=-s[sp]),s[sp]&=4294967295):sp--}function forthqnumber(){m[s[sp]+tos-1]==46?(exception("no input support for double length numbers yet"),sp--,tos=0):forthqsinglenumber()}
var x_qnumber=primitive("?number",forthqnumber);function forthinterpretnumber(){forthqnumber();tos&&m[state]&&(m[dp++]=x_lit,m[dp++]=s[sp--],tos=-1)}var x_interpretnumber=primitive("interpretnumber",forthinterpretnumber);definitions(forth);function forthwords(){for(var a=wc;a;a--)h[a]&&m[context]&ds[a]&&m[compliance]&ds[a]&&querytype(h[a]+" ")}var x_words=primitive("words",forthwords);describe("--",f83|ans|jsf|foerthchen|only);function forthvlist(){forthwords()}primitive("vlist",forthvlist);
describe("--",f79|fig);function forthhere(){s[++sp]=tos;tos=dp}var x_here=primitive("here",forthhere);describe("-- a",any);function forthallot(){dp+tos>dictionaryfull?throwerror(-8):(dp+=tos,tos=s[sp--])}var x_allot=primitive("allot",forthallot);describe("n --",any);function forthhide(){hf[wc]&=!smudgebit}var x_hide=primitive("hide",forthhide);describe("--",f83);function forthreveal(){hf[wc]|=smudgebit}var x_reveal=primitive("reveal",forthreveal);describe("--",f83);
function comma(a){dp+1>=dictionaryfull?throwerror(-8):m[dp++]=a}function forthcomma(){comma(tos);tos=s[sp--]}var x_comma=primitive(",",forthcomma);describe("x --",any);var x_ccomma=primitive("c,",forthcomma);describe("c --",any);function compile(){for(var a=0;a<arguments.length;jscomma(arguments[a++]));}definitions(hidden);
function forthsearch1(){for(var a=wc;a;a--)if((w=h[a])&&m[context]&ds[a]&&hf[a]&smudgebit)if(m[casesensitive]||(w=w.toLowerCase()),w==tos&&m[compliance]&ds[a]){tos=a;return}tos=0}function forthsearch(){forthpack();m[casesensitive]||(tos=tos.toLowerCase());var a=tos,b=m[context];forthsearch1();if(!tos)for(var c=vocstack.length;c;)if(tos=0,c--,m[context]!=vocstack[c]&&(m[context]=vocstack[c],tos=a,forthsearch1()),tos)break;m[context]=b}var x_search=primitive("search",forthsearch);definitions(forth);
function forthfind(){s[++sp]=tos;s[++sp]=tos+1;tos=m[tos]&255;forthsearch();tos&&(s[sp]=tos,tos=hf[tos]&precedencebit?1:-1)}var x_find=primitive("find",forthfind);describe("a1 -- a2 0 | a2 xt",ans|f83|jsf);function forthtobody(){tos<=primitives&&throwerror(-31);tos=x[tos]+1}var x_tobody=primitive(">body",forthtobody);describe("a1 -- a2",any);function forthbodyfrom(){tos--;for(var a=wc;a;a--)if(h[a]&&x[a]==tos){tos=a;return}throwerror(-65)}primitive("body>",forthbodyfrom);describe("a1 -- a2",jsf);
definitions(hidden);function forthqimm(){tos=-(hf[tos]&precedencebit)}var x_qimm=primitive("?immediate",forthqimm);function forthcompiling(){s[++sp]=tos;tos=m[state]}var x_compiling=primitive("compiling",forthcompiling);definitions(forth);function forthimmediate(){hf[wc]|=precedencebit}primitive("immediate",forthimmediate);describe("--",any);function forthbrclose(){m[state]=true}var x_brclose=primitive("]",forthbrclose);describe("--",any);function forthbropen(){m[state]=false}
var x_bropen=primitive("[",forthbropen,immediate);describe("--",any);definitions(hidden);function forthnewheader(){forthpack();newheader(tos);tos=s[sp--]}var x_newheader=primitive("newheader",forthnewheader);definitions(forth);function forthdotname(){type(h[tos]);tos=s[sp--]}var x_dotname=primitive(".name",forthdotname);describe("xt --",jsf);function forthname(){sp++;s[++sp]=h[tos];tos=dp;s[sp-1]=tos;unpack()}primitive("name",forthname);describe("x1 -- a u",jsf);definitions(hidden);
function forthcreateheader(){s[++sp]=tos;tos=bl;forthparse();forthnewheader()}var x_createheader=primitive("createheader",forthcreateheader);function forthuse(){forthcreateheader();forthcomma();t[wc]=nexthilevel}var x_use=primitive("use",forthuse);definitions(forth);function forthcolonnoname(){s[++sp]=tos;newheader("");tos=wc;comma(x_nest);m[state]=-1;t[wc]=nexthilevel}primitive(":noname",forthcolonnoname);describe("-- a",ans|jsf);function forthunused(){s[++sp]=tos;tos=dictionaryfull-dp}
primitive("unused",forthunused);describe("-- u",ans|jsf);function forthheap(){s[++sp]=tos;tos=heapend}primitive("heap",forthheap);describe("-- a",jsf);function forthbrmarker(){dp=tos;wc=s[sp--];m[lastxt]=wc;tos=s[sp--]}primitive("(marker)",forthbrmarker);describe("wc dp heap --",jsf);var ramblock=[],screenline;function saveblock(){for(i=screenline.length;i<16;i++)screenline.push("");for(i=screenline.length;i>16;i--)screenline.pop();ramblock.push(screenline)}screenline=[];screenline.push("( ramdrive block 0 - essential block words      -load- )");
screenline.push(": copy (s u1 u2 -- ) swap block swap buffer c/s move update ;");screenline.push(": clear (s u -- ) buffer c/s blank update ;");screenline.push(": index1 (s u -- )  dup scr ! 2 .r space 0 .line ;");screenline.push(": index (s u1 u2 -- ) 1+ swap ?do cr i index1 loop ;");screenline.push(": ls (s -- ) 0 capacity 1- index ;");screenline.push(": w (s -- ) last @ 1+ 1 do i name dup if ");screenline.push('      2dup info s"   " ...info  i stackeffect ...info');screenline.push("   then 2drop loop ;");
screenline.push(": --\>  (s -- ) blk @ 1+ block c/s !source >in off ; immediate");screenline.push(": uppercase dup char a char z 1+ within 32 and - ;");screenline.push(": p  (s -- )  scr @ 1-  0 max  scr ! ;");screenline.push(": n  (s -- )  scr @ 1+ capacity 1- min scr ! ;");screenline.push(": view (s -- ) begin key dup esc <> while uppercase");screenline.push("  dup char N = if n else dup char P = if p then then");screenline.push("  drop cls l repeat drop ;");saveblock();screenline=[];screenline.push("( ramdrive block 1 - MARKER + info screen words -load- )");
screenline.push(": marker here last @ create , ,");screenline.push("         does> skim swap @ (marker) ;");screenline.push("");screenline.push(': cr2  (s -- ) s" " info ;');screenline.push("");screenline.push(": .line2 (s u -- ) c/l * screen + c/l -trailing info ;");screenline.push("");screenline.push("( list screen on info window )");screenline.push(": list2 (s u -- ) scr ! l/s 0 do i .line2 loop ;");screenline.push("");screenline.push("( list all screens on info, enable backscroll )");screenline.push(": sources (s -- )  capacity 0 do i list2 loop all ;");
saveblock();screenline=[];screenline.push("( ramdrive block 2 - hex dump                   -load- )");screenline.push("hidden definitions  6 constant dumps/line");screenline.push(": safe-emit (s c -- ) dup bl 128 within 0=");screenline.push("      if drop char . then emit ;");screenline.push(": ######## (s u -- ) 0 <# 8 for # next #> type ;");screenline.push(": .cell (s u -- ) 16 base exchange swap ######## space base ! ;");screenline.push(": .addr (s u -- ) .cell ;");screenline.push(": pad_dump1 (s n -- ) 4 swap - 3 * spaces ;");
screenline.push(": dump_cells (s a n -- ) for skim .cell next drop ;");screenline.push(": dump_chars (s a n -- ) for count safe-emit next drop ;");screenline.push(": dump1line (s a n -- ) dumps/line min dup if over .addr");screenline.push("     2 spaces 2dup dump_cells dup pad_dump1 2 spaces");screenline.push("   2dup dump_chars then 2drop ;");screenline.push("forth definitions hidden");screenline.push(": dump (s a n -- ) begin ?dup while 2dup cr dump1line");screenline.push("  dumps/line /string repeat drop ; forth");
saveblock();screenline=[];screenline.push("( ramdrive block 3 - modified retro editor )");screenline.push(": line (s u -- a )  c/l * screen + ;");screenline.push(": s    (s u -- )    scr ! ;");screenline.push(": ia (s a u -- )    line + >r 0 parse r> swap cmove ;");screenline.push(": r  (s u -- )      0 swap ia ;");screenline.push(": d  (s u -- )      line c/l blank ;");screenline.push(": x (s -- )         clear ;");screenline.push(": v (s -- )         l ;");screenline.push("( extensions: bubble up and down lines )");
screenline.push(": >pad (s a n -- )  pad swap move ;");screenline.push(": pad> (s a n -- )  pad -rot move ;");screenline.push(": lines (s u1 u2 -- a1 a2 ) line swap line swap ;");screenline.push(": xchg lines over >r dup c/l >pad c/l move r> c/l pad> ;");screenline.push(": bu (s u1 -- )    ?dup if dup 1- xchg then ;");screenline.push(": bd (s u1 -- )    dup l/s 1- < if dup 1+ bu then drop ;");saveblock();screenline=["( ramdrive block 4 - empty )"];saveblock();screenline=["( ramdrive block 5 - empty )"];
saveblock();screenline=["( ramdrive block 6 - empty )"];saveblock();screenline=["( ramdrive block 7 - empty )"];saveblock();screenline=["( ramdrive block 8 - empty )"];saveblock();screenline=["( ramdrive block 9 - empty )"];saveblock();screenline=["( ramdrive block 10 - empty )"];saveblock();screenline=["( ramdrive block 11 - empty )"];saveblock();
function loadblockfromram(a,b){debug("ram drive: block "+a+" to addr "+b);var c=b;for(i=0;i<16;i++)s[++sp]=lineofspaces.substr(0,64),tos=c,unpack(),s[++sp]=ramblock[a][i].substr(0,64),tos=c,unpack(),c+=64;return b}function savebuftoram(a,b){debug("ram drive: from "+a+" to ramblock "+b);for(i=0;i<16;i++)ramblock[b][i]=pack(a,64),a+=64}function ramdrivecapacity(){return ramblock.length}var cookiesectorsize=1024;
function loadblockfromcookie(a,b){debug("cookie drive: block "+a+" to addr "+b);for(var c=0;c<1024;c+=cookiesectorsize){var d=readcookie(cookiebasename+a+"_"+c,b+c);if(d)unpackstring(d.substr(0,cookiesectorsize),b+c);else for(var d=b+c,e=0;e<cookiesectorsize;e++)m[d++]=bl}return b}function savebuftocookie(a,b){debug("cookie drive: from "+a+" to block "+b);for(var c=0;c<1024;c+=cookiesectorsize)setcookie(cookiebasename+b+"_"+c,pack(a+c,cookiesectorsize),null,cookieexpirationdate)}
function cookiedrivecapacity(){return maxcookies}function localcapacity(){return ramdrivecapacity()+cookiedrivecapacity()}function capacity(){return localcapacity()}function forthcapacity(){s[++sp]=tos;tos=capacity()}primitive("capacity",forthcapacity);describe("-- u",jsf);function forthlocalcapacity(){s[++sp]=tos;tos=localcapacity()}primitive("localcapacity",forthlocalcapacity);describe("-- u",jsf);
function savebuf(a){var b=(new Date).getTime(),c=buf[a],d=bufblk[a];d<maxcookies?savebuftocookie(c,d):(localcapacity(),savebuftoram(c,d-maxcookies));bufdirty[a]=0;a=(new Date).getTime();debug("block "+d+" write took "+(a-b)+"ms")}function loadblock(a,b){var c=(new Date).getTime();if(a<maxcookies)var d=loadblockfromcookie(a,b);else localcapacity(),d=loadblockfromram(a-maxcookies,b);var e=(new Date).getTime();debug("block "+a+" read took "+(e-c)+"ms");return d}var hotbuffer;
function forthblockorbuffer(a){(tos>=capacity()||tos<0)&&throwerror(-35);if(blockstat[tos]>=0)hotbuffer=blockstat[tos],tos=buf[hotbuffer];else{nextbuf++;nextbuf%=maxbufs;bufblk[nextbuf]>=0&&(bufdirty[nextbuf]&&savebuf(nextbuf),blockstat[bufblk[nextbuf]]=-1);var b=tos;tos=a?loadblock(tos,buf[nextbuf]):buf[nextbuf];hotbuffer=nextbuf;bufblk[nextbuf]=b;blockstat[b]=nextbuf}}function forthbuffer(){forthblockorbuffer(false)}var x_buffer=primitive("buffer",forthbuffer);describe("u -- a",any);
function forthblock(){forthblockorbuffer(true)}var x_block=primitive("block",forthblock);describe("u -- a",any);function forthupdate(){bufdirty[hotbuffer]=-1}primitive("update",forthupdate);describe("--",any);function forthsavebuffers(){for(var a=0;a<maxbufs;a++)bufdirty[a]&&savebuf(a),blockstat[bufblk[a]]=-1}primitive("save-buffers",forthsavebuffers);describe("--",any);function forthemptybuffers(){for(var a=0;a<maxbufs;a++)bufblk[a]>=0&&(blockstat[bufblk[a]]=-1,bufblk[a]=-1,bufdirty[a]=0)}
primitive("empty-buffers",forthemptybuffers);describe("--",any);function forthblockstats(){cr();type("checking blocks:");for(var a=capacity(),b=0;b<a;b++)blockstat[b]!=-1&&(cr(),type("   blk #"+b+": buf "+blockstat[b]))}function forthbufstats(){cr();type("checking buffers:");for(i=0;i<maxbufs;i++)cr(),type("   buf #"+i+":"),bufblk[i]<0?type(" empty"):type(" blk "+bufblk[i]),bufdirty[i]&&type(" dirty");forthblockstats()}primitive("bufstats",forthbufstats);describe("--",jsf);definitions(forth);
function dovocabulary(){w=x[w];m[context]=m[w];standard=standard&(higheststandard<<1)-1|m[context]}function forthvocabulary(){nextvocabulary>=536870912?throwerror(-69):(forthcreateheader(),vocname.push(wc),t[wc]=dovocabulary,nextvocabulary<<=1,m[dp++]=nextvocabulary,forthreveal())}primitive("vocabulary",forthvocabulary);describe("<new vocabulary name> --",any);function forthonly(){for(var a=vocstack.length;a;a--)vocstack.pop();m[context]=only;vocstack.push(only)}primitive("only",forthonly);
describe("--",any);vocname.push(wc);function forthforth(){m[context]=forth}primitive("forth",forthforth);describe("--",any|only);vocname.push(wc);function forthhidden(){m[context]=hidden}primitive("hidden",forthhidden);describe("--",jsf|f83|ans);vocname.push(wc);function forthteststuff(){m[context]=teststuff}primitive("teststuff",forthteststuff);describe("--",jsf);vocname.push(wc);function forthdefinitions(){m[current]=m[context]}primitive("definitions",forthdefinitions);describe("--",any);
function forthorder(){printvocname(m[context]);for(var a=vocstack.length;a;a--)printvocname(vocstack[a-1]);type("      ");printvocname(m[current])}primitive("order",forthorder);describe("--",ans|jsf|only);function forthalso(){vocstack.push(m[context])}primitive("also",forthalso);describe("--",ans|jsf);function forthprevious(){m[context]=vocstack.pop()}primitive("previous",forthprevious);describe("--",ans|jsf);function forthvocs(){for(i=vocname.length;i;type(h[vocname[--i]]+" "));}
primitive("vocs",forthvocs);describe("--",fig|f79|f83|jsf);definitions(teststuff);function forth1point5(){f.push(ftos);ftos=1.5}primitive("1.5",forth1point5);function forthmin1point5(){f.push(ftos);ftos=-1.5}primitive("-1.5",forthmin1point5);function forth2point8(){f.push(ftos);ftos=2.8}primitive("2.8",forth2point8);function forthmin2point8(){f.push(ftos);ftos=-2.8}primitive("-2.8",forthmin2point8);definitions(forth);
function forthfdots(){f.push(ftos);for(var a=1;a<f.length;type(f[a++]+" "));ftos=f.pop()}primitive("f.s",forthfdots);describe("--",any);function forthfdrop(){ftos=f.pop()}primitive("fdrop",forthfdrop);describe("r --",any);function forthfdup(){f.push(ftos)}primitive("fdup",forthfdup);describe("r -- r r",any);function forthfswap(){w=f.pop();f.push(ftos);ftos=w}primitive("fswap",forthfswap);describe("r1 r2 -- r2 r1",any);function forthfover(){f.push(ftos);ftos=f[f.length-2]}primitive("fover",forthfover);
describe("r1 r2 -- r1 r2 r1",any);function forthffetch(){f.push(ftos);ftos=m[tos];tos=s[sp--]}primitive("f@",forthffetch);describe("a -- r",any);function forthfstore(){m[tos]=ftos;ftos=f.pop();tos=s[sp--]}primitive("f!",forthfstore);describe("r a --",any);function forthfequ(){s[++sp]=tos;tos=-(ftos==f.pop())}primitive("f=",forthfequ);describe("r1 r2 -- f",any);function forthfnequ(){s[++sp]=tos;tos=-(ftos!=f.pop())}primitive("f<>",forthfnequ);describe("r1 r2 -- f",any);
function forthfmore(){s[++sp]=tos;tos=-(f.pop()>ftos)}primitive("f>",forthfmore);describe("r1 r2 -- f",any);function forthfless(){s[++sp]=tos;tos=-(f.pop()<ftos)}primitive("f<",forthfless);describe("r1 r2 -- f",any);function forthf0equ(){s[++sp]=tos;tos=-(ftos==0);ftos=f.pop()}primitive("f0=",forthf0equ);describe("r -- f",any);function forthf0nequ(){s[++sp]=tos;tos=-(ftos!=0);ftos=f.pop()}primitive("f0<>",forthf0nequ);describe("r -- f",any);
function forthf0less(){s[++sp]=tos;tos=-(ftos<0);ftos=f.pop()}primitive("f0<",forthf0less);describe("r -- f",any);function forthf0greater(){s[++sp]=tos;tos=-(ftos>0);ftos=f.pop()}primitive("f0>",forthf0greater);describe("r -- f",any);function forthfnegate(){ftos=-ftos}primitive("fnegate",forthfnegate);describe("r1 -- r2",any);function forthfabs(){ftos=Math.abs(ftos)}primitive("fabs",forthfabs);describe("r1 -- r2",any);function forthfround(){ftos=Math.round(ftos)}primitive("fround",forthfround);
describe("r1 -- r2",any);function forthfdepth(){s[sp++]=tos;tos=f.length}primitive("fdepth",forthfdepth);describe(" -- u",any);function forthdtof(){f.push(ftos);ftos=tos*4294967296+s[sp--];tos=s[sp--]}primitive("d>f",forthdtof);describe("d --",jsf|ans);function forthftod(){s[++sp]=tos;tos=ftos;ftos=f.pop();s[++sp]=tos&4294967295;tos/=4294967296;tos<0&&(tos+=floorfix);tos=Math.floor(tos)}primitive("f>d",forthftod);describe("r -- d",jsf|ans);function forthstof(){f.push(ftos);ftos=tos;tos=s[sp--]}
primitive("s>f",forthstof);describe("x --",jsf);function forthfplus(){ftos+=f.pop()}primitive("f+",forthfplus);describe("r1 r2 -- r3",jsf|ans);function forthfminus(){ftos=f.pop()-ftos}primitive("f-",forthfminus);describe("r1 r2 -- r3",jsf|ans);function forthfmul(){ftos*=f.pop()}primitive("f*",forthfmul);describe("r1 r2 -- r3",jsf|ans);function forthfdiv(){ftos=f.pop()/ftos}primitive("f/",forthfdiv);describe("r1 r2 -- r3",jsf|ans);function forthfsin(){ftos=Math.sin(ftos)}primitive("fsin",forthfsin);
describe("r1 -- r2",jsf|ans);function forthfcos(){ftos=Math.cos(ftos)}primitive("fcos",forthfcos);describe("r1 -- r2",jsf|ans);function forthftan(){ftos=Math.tan(ftos)}primitive("ftan",forthftan);describe("r1 -- r2",jsf|ans);function forthfasin(){ftos=Math.asin(ftos)}primitive("fasin",forthfasin);describe("r1 -- r2",jsf|ans);function forthfatan(){ftos=Math.atan(ftos)}primitive("fatan",forthfatan);describe("r1 -- r2",jsf|ans);function forthfatan2(){ftos=Math.atan2(f.pop(),ftos)}
primitive("fatan2",forthfatan2);describe("r1 r2 -- r3",jsf|ans);function forthfacos(){ftos=Math.acos(ftos)}primitive("facos",forthfacos);describe("r1 -- r2",jsf|ans);function forthfpower(){ftos=Math.pow(f.pop(),ftos)}primitive("f**",forthfpower);describe("r1 r2 -- r3",jsf|ans);function forthfln(){ftos=Math.log(ftos)}primitive("fln",forthfln);describe("r1 -- r2",jsf|ans);function forthfalog(){ftos=Math.pow(10,ftos)}primitive("falog",forthfalog);describe("r1 -- r2",jsf|ans);
function forthfsqrt(){ftos=Math.sqrt(ftos)}primitive("fsqrt",forthfsqrt);describe("r1 -- r2",jsf|ans);function forthfmin(){ftos=Math.min(ftos,f.pop())}primitive("fmin",forthfmin);describe("r1 r2 -- r3",jsf|ans);function forthfmax(){ftos=Math.max(ftos,f.pop())}primitive("fmax",forthfmax);describe("r1 r2 -- r3",jsf|ans);function forthfdot(){type(ftos+" ");ftos=f.pop()}primitive("f.",forthfdot);describe("r --",jsf|ans);function forthpi(){f.push(ftos);ftos=Math.PI}primitive("pi",forthpi);
describe("-- r",jsf|ans);function forthreciproc(){ftos=1/ftos}primitive("1/f",forthreciproc);describe("r1 -- r2",jsf|ans);function forthfcomma(){m[dp++]=ftos;ftos=f.pop()}var x_fcomma=primitive("f,",forthfcomma);describe("r --",any);primitive("falign",noop,immediate);describe("--",ans);primitive("faligned",noop,immediate);describe("--",ans);var nusedchunks=0,nfreechunks=0;function newchunk(a){m[heapend++]=nusedchunks;m[heapend++]=a;a=usedchunk[nusedchunks++]=heapend;heapend+=tos;return a}
function splitchunk(a,b){var c=freechunk[a],d=m[c-1]-(b+2);d>0?(m[c-1]=d++,c+=d,m[c++]=b):(freechunk[a]=freechunk[--nfreechunks],freechunk.pop());m[c-2]=nusedchunks;return usedchunk[nusedchunks++]=c}function searchfit(a){var b=-1;if(nfreechunks)for(var c=4294967295,d=0;d<nfreechunks;d++){var e=m[freechunk[d]-1]-a;if(e==0)return d;if(e>2){if(!fittype)return d;e<c&&(b=d,c=e)}}return b}function forthallocate(){var a=searchfit(tos);a<0?s[++sp]=newchunk(tos):s[++sp]=splitchunk(a,tos);tos=0}
primitive("allocate",forthallocate);describe("u -- a 0 | err",ans|jsf);
function forthfree(){var a=Math.min(m[tos-2],nusedchunks-1),b=usedchunk[a];b!=tos?throwerror(-72):(freechunk[nfreechunks++]=b,nusedchunks--,b=usedchunk.pop(),a<nusedchunks&&(m[b-2]=a,usedchunk[a]=b));freechunk.sort();b=freechunk[0]+m[freechunk[0]-1]+2;for(a=1;a<nfreechunks;a++)if(freechunk[a]==b){chunksize=m[freechunk[a]-1]+2;m[freechunk[a-1]-1]+=chunksize;b+=chunksize;nfreechunks--;for(var c=a;c<nfreechunks;freechunk[c++]=freechunk[c]);freechunk.pop();a--}else b=freechunk[a]+m[freechunk[a]-1]+2;
a=freechunk[nfreechunks-1];a+m[a-1]==heapend&&(nfreechunks--,heapend=freechunk.pop()-2);tos=0}primitive("free",forthfree);describe("a -- 0 | err",ans|jsf);function forthdotallocated(){type("allocated:");for(var a=0;a<nusedchunks;a++)cr(),type(a+"/"+m[usedchunk[a]-2]+": "+usedchunk[a]+" "+m[usedchunk[a]-1]);cr();type("freed:");for(a=0;a<nfreechunks;a++)cr(),type(a+": "+freechunk[a]+" "+m[freechunk[a]-1])}primitive(".allocated",forthdotallocated);describe("--",jsf);definitions(forth);
function forthbye(){forthsavebuffers();window.close()}primitive("bye",forthbye);describe("--",any|foerthchen);function forthdecimal(){m[base]=10}var x_decimal=primitive("decimal",forthdecimal);describe("--",any);function forthhex(){m[base]=16}var x_hex=primitive("hex",forthhex);describe("--",any);function fortheval(){forthpack();eval(tos);tos=s[sp--]}var x_eval=primitive("eval",fortheval);describe("a n --",jsf);function forthalert(){forthpack();alert(tos);tos=s[sp--]}primitive("alert",forthalert);
describe("a n --",jsf);function forthconfirm(){forthpack();tos=-confirm(tos)}primitive("confirm",forthconfirm);describe("a n -- d",jsf);function forthenter(){tos=unpackstring(prompt(pack(s[sp-1],s[sp])),tos);sp-=2}primitive("enter",forthenter);describe("a1 n1 a2 -- n2",jsf);function forthms(){suspended=w;setTimeout(function(){virtualmachine(ip)},tos);tos=s[sp--]}var x_ms=primitive("ms",forthms);describe("u --",jsf);function forthepoch(){s[++sp]=tos;w=(new Date).getTime();tos=Math.floor(w/1E3)}
primitive("epoch",forthepoch);describe("-- u",jsf);function forthrandom(){tos=Math.floor(Math.random()*tos)}primitive("random",forthrandom);describe("u1 -- u2",jsf);definitions(hidden);function forthlocate(){tos=src[tos]}primitive("locate",forthlocate);describe("xt -- n",jsf);function forthwordtype(){tos=tos<=primitives?0:m[x[tos]]}primitive("wordtype",forthwordtype);describe("xt1 -- xt2",jsf);function forthdisassemble(){var a=x[s[sp--]]+" ";tos=unpackstring(a,tos)}primitive("disassemble",forthdisassemble);
describe("xt a -- n",jsf);definitions(forth);function infosall(){}primitive("all",infosall);describe("--",jsf);function infostail(){}primitive("tail",infostail);describe("--",jsf);function setinfoslines(){infolines=tos;info("* buffer size set to "+tos+" lines.");tos=s[sp--]}primitive("infolines",setinfoslines);describe("u --",jsf);function forthloadhelp(){var a="docs/jsforth.html#"+pack(s[sp],tos);window.frames.help.window.location.replace(a.toUpperCase());sp--;tos=s[sp--]}
var x_loadhelp=primitive("loadhelp",forthloadhelp),primitives=wc;function constant(a,b){newheader(a,smudgebit);comma(x_doconst);comma(b);t[wc]=nextconstant;return wc}function variable(a){newheader(a,smudgebit);comma(x_dovar);comma(0);t[wc]=nextvariable;return wc}function colon(a,b){newheader(a,b|smudgebit);comma(x_nest);t[wc]=nexthilevel;return wc}function alias(a,b){newheader(a,b|smudgebit);x[wc]=x[wc-1];t[wc]=t[wc-1];return wc}function semicolon(){jscomma(x_unnest)}
function IF(){m[dp++]=x_0branch;s[++sp]=tos;tos=dp;dp++}function ELSE(){m[dp++]=x_branch;s[++sp]=dp;dp++;m[tos]=dp-tos;tos=s[sp--]}function THEN(){m[tos]=dp-tos;tos=s[sp--]}function BEGIN(){s[++sp]=tos;tos=dp}function UNTIL(){m[dp++]=x_0branch;m[dp]=tos-dp++;tos=s[sp--]}function WHILE(){IF()}function REPEAT(){m[dp++]=x_branch;m[dp]=s[sp--]-dp++;m[tos]=dp-tos;tos=s[sp--]}function AGAIN(){m[dp++]=x_branch;m[dp]=tos-dp++;tos=s[sp--]}
function makeDO(a){m[dp++]=a;s[++sp]=m[innerloop];m[innerloop]=dp;s[++sp]=dp;dp++}function DO(){makeDO(x_brdo)}function QDO(){makeDO(x_brqdo)}function LOOP(){m[dp++]=x_brloop;m[dp++]=s[sp]+2-dp;m[s[sp]]=dp-s[sp--];m[innerloop]=s[sp--]}function LEAVE(){m[dp++]=x_brleave;m[dp++]=m[innerloop]}function QLEAVE(){m[dp++]=x_brqleave;m[dp++]=m[innerloop]}definitions(hidden);var x_innerloop=constant("innerloop",innerloop),x_innercase=constant("innercase",innercase);definitions(forth);
var x_minus1=constant("-1",-1);describe("-- -1",jsf|foerthchen);var x_0=constant("0",0);describe("-- 0",any);var x_1=constant("1",1);describe("-- 1",any);constant("cell",1);describe("-- u",ans|jsf);var x_2=constant("2",2);describe("-- 2",any);var x_bl=constant("bl",bl);describe("-- c",any);var x_esc=constant("esc",esc);describe("-- c",jsf);constant("compliance",compliance);describe("-- a",jsf);constant("true",-1);describe("-- -1",any);constant("false",0);describe("-- 0",any);
constant("casesensitive",casesensitive);describe("-- a",jsf);constant("warnings",warnings);describe("-- a",jsf);constant("debugger",debugging);describe("-- a",jsf);var x_xontext=constant("context",context);describe("-- a",jsf);var x_current=constant("current",current);describe("-- a",jsf);var x_blk=constant("blk",blk);describe("-- a",any);var x_scr=constant("scr",scr);describe("-- a",any);var x_lastxt=constant("last",lastxt);describe("-- a",jsf);var x_base=constant("base",base);describe("-- a",any);
var x_tib=constant("tib",tib);describe("-- a",any);var x_span=constant("span",span);describe("-- a",fig|f79|f83|ans);var x_hashtib=constant("#tib",hashtib);describe("-- a","obsolete, variable containing #chars in tib",fig|f79|f83|ans);var x_in=constant(">in",toin);describe("-- a",any);var x_state=constant("state",state);describe("-- a",any);constant("outfile",outfile);describe("-- a",jsf);constant("fit",fittype);describe("-- a",jsf);constant("c/l",64);describe("-- u",jsf);constant("l/s",16);
describe("-- u",jsf);constant("c/s",1024);describe("-- u",jsf);var x_literal=colon("literal",immediate);compile(x_lit,x_lit,x_comma,x_comma);semicolon();describe("x --",any);definitions(hidden);var x_stackunderflow=colon("underflow");compile(x_lit,-4,x_throw);var x_notfound=colon("notfound");compile(x_lit,-13,x_throw);definitions(hidden);definitions(forth);var x_abort=colon("abort");compile(x_lit,-1,x_throw);describe("--",any);var x_qcomp=colon("?comp");compile(x_compiling,x_0equ);IF();
compile(x_lit,-14,x_throw);THEN();semicolon();describe("--",jsf);var x_qexec=colon("?exec");compile(x_compiling);IF();compile(x_lit,-64,x_throw);THEN();semicolon();describe("--",jsf);var x_compilecomma=colon("compile,",immediate);compile(x_qcomp,x_comma);semicolon();describe("xt --",any);definitions(hidden);var x_commastr=colon(",$");compile(x_here,x_over,x_1plus,x_allot,x_movestr);semicolon();describe("a n --",jsf);definitions(forth);var x_commaquote=colon(',"');compile(x_lit,34,x_parse,x_commastr);
semicolon();describe("--",jsf);var x_commatick=colon(",'");compile(x_lit,39,x_parse,x_commastr);semicolon();describe("--",jsf);function forthscan(){for(var a=s[sp--];a;a--){if(m[s[sp]]==tos)break;s[sp]++}tos=a}primitive("scan",forthscan);describe("a1 n2 c -- a2 n2",any);function forthskip(){for(var a=s[sp--];a;a--){if(m[s[sp]]!=tos)break;s[sp]++}tos=a}primitive("skip",forthskip);describe("a1 n2 c -- a2 n2",any);definitions(hidden);var x_compilestringword=colon('string",');
compile(x_qcomp,x_comma,x_commaquote);semicolon();var x_compiletickstringword=colon("string',");compile(x_qcomp,x_comma,x_commatick);semicolon();definitions(forth);var x_squote=colon('s"',immediate);compile(x_lit,x_brsquote,x_compilestringword);semicolon();describe("--",any);var x_cquote=colon('c"',immediate);compile(x_lit,x_brcquote,x_compilestringword);semicolon();describe("--",ans|jsf);var x_dotquote=colon('."',immediate);compile(x_lit,x_brdotquote,x_compilestringword);semicolon();
describe("--",any|foerthchen);colon("s'",immediate);compile(x_lit,x_brsquote,x_compiletickstringword);semicolon();describe("--",any);colon(".'",immediate);compile(x_lit,x_brdotquote,x_compiletickstringword);semicolon();describe("--",any|foerthchen);var x_dumul=colon("du*");compile(x_tuck,x_2tor,x_ummul,x_0,x_2rfrom,x_mul,x_dplus);semicolon();colon(">number");compile(x_2dup,x_plus,x_tor);compile(x_0);QDO();compile(x_count,x_digit,x_dup,x_0less);IF();compile(x_drop,x_1minus);LEAVE();THEN();
compile(x_swap,x_tor,x_tor);compile(x_base,x_fetch,x_dumul);compile(x_rfrom,x_0,x_dplus);compile(x_rfrom);LOOP();compile(x_rfrom,x_over,x_minus);semicolon();describe("ud1 a1 u1 -- ud2 a2 u2",ans|jsf);var x_abortquote=colon('abort"',immediate);compile(x_lit,x_brabortquote,x_compilestringword);semicolon();describe("--",any);var x_create=colon("create");compile(x_lit,x_dovar,x_use,x_reveal);semicolon();describe("--",any);var x_const=colon("constant");compile(x_lit,x_doconst,x_use,x_comma,x_reveal);semicolon();
describe("x --",any);colon("fconstant");compile(x_lit,x_dofconst,x_use,x_fcomma,x_reveal);semicolon();describe("r -- ) ( -- r )",ans|jsf);colon("value");compile(x_lit,x_dovalue,x_use,x_comma,x_reveal);semicolon();describe("x --",ans|jsf);colon("variable");compile(x_create,x_0,x_comma);semicolon();describe("--",any);alias("fvariable");describe("-- ) ( -- a",any);colon(";",immediate);compile(x_lit,x_unnest,x_comma,x_bropen,x_reveal);semicolon();describe("--",any|foerthchen);colon(":");
compile(x_lit,x_nest,x_use,x_brclose);semicolon();describe("<wordname> --",any|foerthchen);colon("does>",immediate);compile(x_lit,x_setdoes,x_compilecomma);compile(x_lit,x_unnest,x_compilecomma);semicolon();describe("--",any);var x_keyq=colon("key?");compile(x_key1query,x_key2query);semicolon();describe("-- f",jsf);colon("?terminal");compile(x_keyq);semicolon();describe("-- f",fig|f79);var x_key=colon("key");compile(x_key1,x_key2);semicolon();describe("-- c",any);var x_word=colon("word");
compile(x_parse,x_here,x_movestr,x_here);semicolon();describe("c -- a",any|foerthchen);var x_accept=colon("accept");compile(x_over,x_swap,x_1plus);BEGIN();compile(x_qdup);WHILE();compile(x_key,x_decode);REPEAT();compile(x_swap,x_minus);semicolon();describe("a n1 -- n2",ans|jsf);colon("expect");compile(x_accept,x_span,x_store);semicolon();describe("a n --",fig|f79|f83|ans);var x_query=colon("query");compile(x_tib,x_dup,x_lit,tibsize,x_accept);compile(x_dup,x_hashtib,x_store,x_storesource);
compile(x_in,x_off);semicolon();describe("--",any);var x_sbr=colon("s(");compile(x_lit,41,x_parse);semicolon();describe("-- a n",jsf);colon(".(",immediate);compile(x_sbr,x_type);semicolon();describe("<stream> --",ans|jsf);var x_char=colon("char",immediate);compile(x_bl,x_parse,x_drop,x_cfetch);compile(x_compiling);IF();compile(x_literal);THEN();semicolon();describe("<stream> -- c",ans|jsf);alias("[char]",immediate);describe("<stream> -- c",ans|jsf);colon("\\",immediate);compile(x_0,x_parse,x_2drop);
semicolon();describe("<stream> --",any);colon("(",immediate);compile(x_lit,41,x_parse,x_2drop);semicolon();describe("<stream> --",any);colon("(s",immediate);compile(x_lit,41,x_parse,x_mintrailing,x_storestackeffect);semicolon();describe("<stream> --",any);var x_hash=colon("#");compile(x_base,x_fetch,x_udslashmod,x_rot,x_lit,9,x_over,x_less);IF();compile(x_lit,39,x_plus);THEN();compile(x_lit,48,x_plus,x_hold);semicolon();describe("d1 -- d2",any);var x_hashs=colon("#s");BEGIN();
compile(x_hash,x_2dup,x_or,x_0equ);UNTIL();semicolon();describe("d1 -- d2",any);var x_parenddot=colon("(d.)");compile(x_dup,x_tor,x_dabs,x_lesshash,x_hashs,x_rfrom,x_sign,x_hashmore,x_type);semicolon();describe("d --",any);var x_ddot=colon("d.");compile(x_parenddot,x_space);semicolon();describe("d --",any);var x_ddotr=colon("d.r");compile(x_tor);compile(x_dup,x_tor,x_dabs,x_lesshash,x_hashs,x_rfrom,x_sign,x_hashmore);compile(x_rfrom,x_2dup,x_more);IF();BEGIN();compile(x_qdup);WHILE();
compile(x_1minus,x_lit,42,x_emit);REPEAT();compile(x_2drop);ELSE();compile(x_over,x_minus,x_spaces,x_type);THEN();semicolon();describe("d --",any);var x_udot=colon("u.");compile(x_0,x_ddot);semicolon();describe("u --",any);var x_dot=colon(".");compile(x_stod,x_ddot);semicolon();describe("n --",any);colon("(.)");compile(x_stod,x_parenddot);semicolon();describe("n --",foerthchen);colon("u.r");compile(x_0,x_swap,x_ddotr);semicolon();describe("u1 u2 --",any);var x_dotr=colon(".r");
compile(x_tor,x_stod,x_rfrom,x_ddotr);semicolon();describe("n u --",any);definitions(hidden);var x_structured=colon("structured");compile(x_2dup,x_nequ);IF();compile(x_unstructured);THEN();compile(x_2drop);semicolon();var x_resolve=colon("resolve");compile(x_here,x_minus,x_comma);semicolon();var x_resolveback=colon("<resolve");compile(x_here,x_over,x_minus,x_swap,x_store);semicolon();var x_qclause=colon("?clause");compile(x_lit,x_0branch,x_comma);semicolon();var x_clause=colon("clause");
compile(x_lit,x_branch,x_comma);semicolon();var x_mark=colon("mark");compile(x_here,x_0,x_comma);semicolon();definitions(forth);var x_for=colon("for",immediate);compile(x_qcomp,x_lit,x_brfor,x_comma);compile(x_here,x_innerloop,x_exchange);compile(x_here,x_0,x_comma);compile(x_lit,6);semicolon();describe("n --",jsf);var x_next=colon("next",immediate);compile(x_qcomp,x_lit,6,x_structured);compile(x_lit,x_brnext,x_comma);compile(x_dup,x_1plus,x_resolve);compile(x_resolveback,x_innerloop,x_store);semicolon();
describe("--",jsf);var x_if=colon("if",immediate);compile(x_qcomp,x_qclause,x_mark,x_1);semicolon();describe("f --",any);var x_else=colon("else",immediate);compile(x_qcomp,x_1,x_structured,x_clause,x_mark);compile(x_swap,x_resolveback,x_2);semicolon();describe("--",any);var x_then=colon("then",immediate);compile(x_qcomp,x_dup,x_2,x_equ,x_plus);compile(x_1,x_structured,x_resolveback);semicolon();describe("--",any);alias("endif",immediate);describe("-- ) ( --",jsf);var x_begin=colon("begin",immediate);
compile(x_qcomp,x_here,x_lit,3);semicolon();describe("--",any);var x_while=colon("while",immediate);compile(x_qcomp,x_lit,3,x_structured);compile(x_qclause,x_mark,x_lit,4);semicolon();describe("f --",any);var x_repeat=colon("repeat",immediate);compile(x_qcomp,x_lit,4,x_structured);compile(x_swap,x_clause,x_resolve);compile(x_resolveback);semicolon();describe("--",any);var x_again=colon("again",immediate);compile(x_qcomp,x_lit,3,x_structured,x_clause,x_resolve);semicolon();describe("--",any);
var x_until=colon("until",immediate);compile(x_qcomp,x_lit,3,x_structured,x_qclause,x_resolve);semicolon();describe("f --",any);var x_do=colon("do",immediate);compile(x_qcomp,x_lit,x_brdo,x_comma);compile(x_here,x_innerloop,x_exchange);compile(x_here,x_0,x_comma);compile(x_lit,5);semicolon();describe("x1 x2 --",any);var x_qdo=colon("?do",immediate);compile(x_qcomp,x_lit,x_brqdo,x_comma);compile(x_here,x_innerloop,x_exchange);compile(x_here,x_0,x_comma);compile(x_lit,5);semicolon();
describe("x1 x2 --",any);var x_loop=colon("loop",immediate);compile(x_qcomp,x_lit,5,x_structured);compile(x_lit,x_brloop,x_comma);compile(x_dup,x_1plus,x_resolve);compile(x_resolveback);compile(x_innerloop,x_store);semicolon();describe("--",any);var x_plusloop=colon("+loop",immediate);compile(x_qcomp,x_lit,5,x_structured);compile(x_lit,x_brplusloop,x_comma);compile(x_dup,x_1plus,x_resolve);compile(x_resolveback);compile(x_innerloop,x_store);semicolon();describe("n --",any);definitions(hidden);
var x_leavecomma=colon("leave,");compile(x_qcomp,x_innerloop,x_fetch,x_qdup,x_0equ);IF();compile(x_lit,-26,x_throw);THEN();compile(x_swap,x_comma,x_comma);semicolon();describe("xt --",any);definitions(forth);colon("leave",immediate);compile(x_lit,x_brleave79,x_comma);semicolon();describe("--",f79|fig);var x_leave=colon("leave",immediate);compile(x_lit,x_brleave,x_leavecomma);semicolon();describe("--",ans|f83|jsf);var x_qleave=colon("?leave",immediate);compile(x_lit,x_brqleave,x_leavecomma);semicolon();
describe("f --",jsf);colon("unloop",immediate);compile(x_qcomp,x_innerloop,x_fetch,x_0equ);IF();compile(x_lit,-26,x_throw);THEN();compile(x_lit,x_brunloop,x_comma,x_unnest);semicolon();describe("--",ans|f83|jsf);colon("case",immediate);compile(x_qcomp);compile(x_0,x_innercase,x_exchange);compile(x_lit,7);semicolon();describe("--",ans|f83|jsf);colon("of",immediate);compile(x_qcomp);compile(x_lit,x_brof,x_comma,x_mark);compile(x_1,x_innercase,x_plusstore);compile(x_lit,8);semicolon();
describe("--",ans|f83|jsf);colon("endof",immediate);compile(x_qcomp,x_lit,8,x_structured);compile(x_clause,x_mark);compile(x_swap,x_resolveback);semicolon();describe("--",ans|f83|jsf);colon("endcase",immediate);compile(x_qcomp);compile(x_lit,x_drop,x_comma);compile(x_innercase,x_fetch);BEGIN();compile(x_qdup);WHILE();compile(x_1minus,x_swap,x_resolveback);REPEAT();compile(x_lit,7,x_structured);compile(x_innercase,x_store);semicolon();describe("--",ans|f83|jsf);definitions(forth);var x_tick=colon("'");
compile(x_bl,x_parse,x_search,x_qdup,x_0equ);IF();compile(x_notfound);THEN();semicolon();describe("<stream> -- xt",ans|f83|jsf);colon("'");compile(x_tick,x_tobody);semicolon();describe("<stream> -- a",fig|f79);var x_brtick=colon("[']",immediate);compile(x_tick,x_literal);semicolon();describe("-- a",any);colon("[compile]",immediate);compile(x_tick,x_comma);semicolon();describe("--",any);colon("recurse",immediate);compile(x_lastxt,x_fetch,x_comma);semicolon();describe("--",ans|f83|jsf);colon("to",immediate);
compile(x_tick,x_tobody,x_dup,x_1minus,x_fetch,x_lit,x_dovalue,x_nequ,x_lit,-67,x_and,x_throw);compile(x_compiling);IF();compile(x_lit,x_brto,x_comma,x_comma);ELSE();compile(x_store);THEN();semicolon();describe("<stream> x --",ans|jsf);definitions(hidden);var x_interpret=colon("interpret");BEGIN();compile(x_bl,x_parse,x_dup);WHILE();compile(x_2dup,x_search,x_qdup);IF();compile(x_nip,x_nip,x_dup,x_qimm);IF();compile(x_execute);ELSE();compile(x_compiling);IF();compile(x_comma);ELSE();compile(x_execute);
THEN();THEN();compile(x_depth,x_0less);IF();compile(x_stackunderflow);THEN();ELSE();compile(x_interpretnumber,x_0equ);IF();compile(x_notfound);THEN();THEN();REPEAT();compile(x_2drop);semicolon();describe("--",jsf);definitions(forth);var x_evaluate=colon("evaluate");compile(x_pushsource);compile(x_in,x_off);compile(x_storesource);compile(x_interpret);compile(x_popsource);semicolon();describe("a n --",ans|jsf);var x_load=colon("load");compile(x_dup,x_blk,x_exchange,x_tor);
compile(x_block,x_lit,1024,x_evaluate);compile(x_rfrom,x_dup,x_blk,x_store);compile(x_dup,x_0less,x_0equ);IF();compile(x_dup,x_block,x_lit,1024,x_storesource);THEN();compile(x_drop);semicolon();describe("u --",any);var x_screen=colon("screen");compile(x_scr,x_fetch,x_block);semicolon();describe("-- a",jsf);var x_dotline=colon(".line");compile(x_lit,64,x_mul,x_screen,x_plus,x_lit,64,x_mintrailing,x_type);semicolon();describe("u --",jsf);var x_plusload=colon("+load");compile(x_blk,x_fetch,x_plus,x_load);
semicolon();describe("u --",any);colon("thru");compile(x_1plus,x_swap);QDO();compile(x_i,x_load);LOOP();semicolon();describe("u1 u2 --",any);colon("+thru");compile(x_1plus,x_swap);QDO();compile(x_i,x_plusload);LOOP();semicolon();describe("u1 u2 --",any);var x_l=colon("l");compile(x_lit,16,x_0);DO();compile(x_cr,x_i,x_2,x_dotr,x_lit,124,x_emit,x_i,x_dotline);LOOP();semicolon();describe("--",jsf);colon("list");compile(x_scr,x_store,x_l);semicolon();describe("u --",any);colon("blank");compile(x_bl,x_fill);
semicolon();describe("a u --",any);colon("help");compile(x_bl,x_parse,x_loadhelp);semicolon();definitions(teststuff);var x_x=colon("x");compile(x_0,x_parse,x_eval);semicolon();describe("<stream> --",jsf);var x_jsconsole=colon("");BEGIN();compile(x_cr,x_lit,62,x_emit,x_query,x_x);AGAIN();semicolon();colon("js");BEGIN();compile(x_lit,x_jsconsole,x_catch,x_drop);AGAIN();semicolon();describe("--",jsf);definitions(forth);var x_quit=colon("quit");BEGIN();compile(x_query,x_source,x_qdup);IF();compile(x_evaluate);
compile(x_0);THEN();compile(x_drop,x_prompt);AGAIN();describe("??? --",any);semicolon();var x_warm=colon("warm");compile(x_warminit,x_quit);describe("??? --",jsf);definitions(hidden);var x_error=colon("error");compile(x_throw);describe("??? n --",jsf);definitions(forth);var warm=dp;comma(x_warm);var error=dp;comma(x_error);function virtualmachine(a){suspended=0;ip=a;do w=m[ip++],t[w]();while(!suspended)}function _init(){virtualmachine(warm)}
function _run(a){for(var b=0;b<a.length;b++){var c=a.charCodeAt(b);inbuf.push(c===10?13:c)}inbuf.push(carriagereturn);virtualmachine(ip)}function _stacktop(a){var b=[];s[++sp]=tos;for(var c=1;c<sp&&c<=a;c++)b.push(s[sp-c+1].toString(m[base]));sp--;return b.reverse()}function _input(){}definitions(forth);function _finish(){console.log("finished.")}primitive("_finish",function(){_finish()});describe("--",jsf);
