/*

 Copyright Joyent, Inc. and other Node contributors.

 Permission is hereby granted, free of charge, to any person obtaining a
 copy of this software and associated documentation files (the
 "Software"), to deal in the Software without restriction, including
 without limitation the rights to use, copy, modify, merge, publish,
 distribute, sublicense, and/or sell copies of the Software, and to permit
 persons to whom the Software is furnished to do so, subject to the
 following conditions:

 The above copyright notice and this permission notice shall be included
 in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
 NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
 USE OR OTHER DEALINGS IN THE SOFTWARE.

 Original at: https://github.com/joyent/node/blob/master/lib/util.js
*/
function require(g){var a=require.resolve(g),e=require.modules[a];if(!e)throw"couldn't find module for: "+g;if(!e.exports)e.exports={},e.call(e.exports,e,e.exports,require.bind(a));return e.exports}require.modules={};require.resolve=function(g){if(require.modules[g])return g;if(!g.match(/\.js$/)){if(require.modules[g+".js"])return g+".js";if(require.modules[g+"/index.js"])return g+"/index.js";if(require.modules[g+"/index"])return g+"/index"}};
require.bind=function(g){return function(a){if(!a.match(/^\./))return require(a);var e=g.split("/");e.pop();for(var a=a.split("/"),n=0;n<a.length;n++){var w=a[n];w==".."?e.pop():w!="."&&e.push(w)}return require(e.join("/"))}};require.register=function(g,a){require.modules[g]=a};
require.register("kaffeine/browser.js",function(g,a,e){(function(){function a(d,l,h){var i=new (window.ActiveXObject||XMLHttpRequest)("Microsoft.XMLHTTP");i.open("GET",d,true);"overrideMimeType"in i&&i.overrideMimeType("text/plain");i.onreadystatechange=function(){i.readyState==4&&(w(d,i.responseText,l),h&&h(true))};try{i.send(null)}catch(v){console.log("failed loading: "+d)}}function w(a,l){var h=(new d).compile(l,{brequire_module:a.replace(/\.k/,"")});eval(h)}function v(){for(var d=document.getElementsByTagName("script"),
l=[],h=0;h<d.length;h++){var i=d[h];i.type.match(/kaffeine/)&&i.src&&l.push(i)}for(h=0;h<l.length;h++){d=l[h].attributes;for(h=0;h<d.length;h++)if(d[h].nodeName=="src")var v=d[h].value;a(v)}}function i(){for(var d=document.getElementsByTagName("script"),a=0;a<d.length;a++){var h=d[a];h.type.match(/kaffeine/)&&!h.src&&w(script.innerHTML)}}var d=e("./kaffeine");typeof window=="undefined"||window===null||(typeof document!="document"&&v(),window.addEventListener?addEventListener("DOMContentLoaded",i,
false):attachEvent("onload",i))}).call(this)});
require.register("kaffeine/index.js",function(g,a,e){function n(d){this.options=d}var w=e("./token");n.fn=n.prototype;n.VERSION="0.0.4";n.plugins={};var v=e("./uglify/parse-js"),i=e("./uglify/process");n.fn.compile=function(d,a){d.match(/\n$/)||(d+="\n");var l=d.match(/^#\s*([^\n]*)\s*\n/)||[1,"multiline_strings string_interpolation hash at brackets_for_keywords operators prototype implicit_functions extend_for pre_pipe implicit_brackets implicit_return pipe bang default_args implicit_vars"],h=l[1].replace(/\s+/g,
" ").replace(/ $/,"").split(" "),d=d.slice(l[0].length),l=this.runPlugins(d,h);a&&(h=v.parse(l),a=="uglify"?(h=i.ast_mangle(h),h=i.ast_squeeze(h),l=i.gen_code(h)):a=="beautify"&&(l=i.gen_code(h,{beautify:true})));return l};n.fn.runPlugins=function(d,a,i){this.currentStream=d=w.ize("function(){ "+d+"\n}");d.global=d.find(function(){if(this.curly)return true});d.global.global=true;for(var i=i||{},h=0;h<a.length;h++){var v=a[h],n=e("./plugins/"+v);if(!n)throw v+" - not loaded";try{n.call(this,d,w,i[v]||
{})}catch(o){throw o.plugin=v,o;}}return d.head().collectText().replace(/^function\(\)\{/,"").replace(/\n\}$/,"")};e.extensions&&(e.extensions[".k"]=function(d,a){var i=e("fs").readFileSync(a,"utf8"),i=(new n).compile(i);d.filename=a+" (compiled)";d._compile(i,d.filename)});g.exports=n});
require.register("kaffeine/plugins/at.js",function(g,a,e){var n=e("../token");g.exports=function(a){a.each(function(){if(this.unknown&&this.text=="@"){var a="this";this.next.text=="@"&&(this.next.remove(),a="this.constructor");a=new n.word(a);a.was_at_symbol=true;this.replaceWith(a);a.next.word&&!a.next.lbracket&&a.after(new n.operator("."));return a}})}});
require.register("kaffeine/plugins/bang.js",function(g,a,e){var n=e("../token");g.exports=function(a){a.each(function(a){if(a.bang){var i=a.next;if(!i||!i.lbracket||!i.round){var d=n.bracket.pair("()");a.after(d.L);d.L.after(d.R);i=a.next}a.indent();var q=a.expressionStart(function(){if(this.operator&&this.text!=".")return true}),l=q.prev,d=i.matching,h=q.lineStart(),w=[],e=a.findClosure(),o=e.asyncBangCount||0,r="_"+o;if(l&&l.assign){w=h.collectText(l.prev).split(", ");r=[];for(l=0;l<w.length;l++)r.push("_"+
(l+o));r=r.join(", ")}var g=0,l=null;q==h?g=0:(l=h.remove(q.prev),l.each(function(){this.lbracket&&g++;this.rbracket&&g--}));var h=d.next,F=h.find(function(){if(this.lbracket)return this.matching.next;if(this.rbracket)if(g==0)return true;else g--;if(this.__break)return true;if(this.next.text=="---")this.next.replaceWith(this.next.myText().replace("---","   ")),this.next.__break=true}),x;h!=F&&(x=h.remove(F.prev));h=l?l.collectText():"";h.match(/^[ \n]*$/)&&(r="",h&&q.before(h));i=i.next==d?0:i.next.collectText(d.prev).split(",").length;
x&&x.find(function(){if(this.was_at_symbol&&!this.findClosure())e.vars._this="this",this.text="_this"});r==""&&x&&!x.myTextNoComments().match(/^[ \n]*$/)&&(r="_"+o,o++);if(w.length>1){q=[];for(l=0;l<w.length;l++,o++)q.push(w[l]+" = _"+o);h=q.join(", ")}else o++,h+=r;x=h+(x?x.collectText():"");x=n.ize("function("+r+") { "+x+" }");i>0&&d.before(", ");d.before(x);a.text=a.text.replace(/!/,"");x.next.matching.nextNW().updateBlock();x.block.asyncBangCount=o}})}});
require.register("kaffeine/plugins/brackets_for_keywords.js",function(g,a,e){var n=e("../token");g.exports=function(a){var v=["if","for","while","catch"];a.each(function(){if(!(v.indexOf(this.text)<0)){var a=this.nextNW();if(!a.lbracket||!a.round){var a=n.bracket.pair("()"),d=this,q=this.find(function(a){if(a.lbracket&&a.curly)return true;if(a.lbracket)return a.matching;if(a.newline)return true;if(a.text==","&&a.prev.prev!=d)return true});if(q.text==",")q.spitRight(),q=q.next,q.prev.remove();if(q.operator&&
!q.unary_operator)q=q.expressionEnd().next;q.whitespace||q.spitRight();this.next.whitespace&&this.next.remove();this.after(a.L);var l=a.L.next.eaten.left[0];l&&l.space&&a.L.next.spitLeft().remove();(l=this.eaten.right[0])&&l.space&&this.spitRight().remove();var h=q.curly?q:null;if(q.prev.whitespace)q=q.prev;if(q.operator)q.spit(function(){return this.whitespace}),q=q.next;q.before(a.R);if((l=a.R.prev.eaten.right[0])&&l.space)a.R.prev.spitRight().remove(),a.R.after(" ");h&&h.updateBlock();this.addImpliedBraces()}}})}});
require.register("kaffeine/plugins/default_args.js",function(g,a,e){e("../token");g.exports=function(a){a.each(function(){if(this.text=="function"){var a=this.block,n=this.block.prevNW().matching,i=[];this.find(function(){if(this==n.matching)return true;if(this.text=="="){var a=this.prev.text,q=this.next.remove(this.next.expressionEnd(function(){if(this.text==",")return true})).collectText(),l=this.prev;this.remove();i.push(a+" = "+a+"==null ? "+q+" : "+a);return l}});i.length&&this.block.after(" "+
i.join(", ")+";");a.args=a.findArgs()}})}});
require.register("kaffeine/plugins/extend_for.js",function(g,a,e){e("../token");g.exports=function(a){a.each(function(){if(this.keyword&&this.text=="for"){var a="",a=this.next,n=false,i=[],d,q,l,h,e=a.matching;a.next.find(function(){if(this.next==e)return true;if(this.semi)return n=true;if(this.word&&(this.text=="in"||this.text=="of"))l=this;this.round&&(h=true);i.push(this)});q=i[0];i[1].text==","&&(d=i[2]);if(n)return e.next;h&&l.next.next.cacheExpression();var g=l.next.next.collectText(e.prev);
g.match(/ /)&&(g="("+g+")");var o,r=this.findClosure();o=a.matching.find(function(){if(this.curly)return true});if(l.text=="in"){if(!d)return;o.implied=false;o.matching.implied=false;d.prev.remove(d);o=q.text;d=d.text;r.vars[o]=true;r.vars[d]=true}else o.implied=false,o.matching.implied=false,a.next.remove(e.prev),o=d?d.text:r.getUnusedVar(),d=q.text,r.vars[o]=true,r.vars[d]=true,a.after(o+" = 0; "+o+" < "+g+".length; "+o+"++");this.block.after(" "+d+" = "+(h?"_xpr":g)+"["+o+"];")}})}});
require.register("kaffeine/plugins/hash.js",function(g,a,e){e("../token");g.exports=function(a){a.each(function(){if(this.unknown&&this.text=="#"){var a="arguments";a+=this.next.word?"["+this.next.remove().collectText()+"]":"[0]";ret=this.next;this.replaceWith(a);return ret}})}});
require.register("kaffeine/plugins/implicit_brackets.js",function(g,a,e){var n=e("../token");g.exports=function(a){var e={"for":1,"if":1,"while":1,"new":1,"return":1,"var":1,"throw":1,"in":1,of:1,"typeof":1,"instanceof":1,"else":1,"try":1,"catch":1,"class":1};a.tail().each(function(){var a=this.next;if(a&&a.space&&a.next&&(!this.word||!(e[this.text]&&this.prev.text!="."||this.block))&&!e[a.next.text]&&!(this.matching&&["for","if","while","else","catch"].indexOf(this.matching.prevNW().text)>=0)){var d=
a.next;if((this.word||this.rbracket)&&(d.word||d.lbracket||d.string)&&d.blockType!="function")if(d=d.expressionEnd(function(){if(this.text==","&&this.next.next.text==":")return true}),d!=null){var q=n.bracket.pair("()");a.replaceWith(q.L);if(d.whitespace)d=d.prev;d.after(q.R)}}},"prev")}});
require.register("kaffeine/plugins/implicit_functions.js",function(g,a,e){e("../token");g.exports=function(a){a.each(function(a){if(a.blockType=="object"&&a.next!=a.matching&&a.nextNW().next.text!=":"){var e=a.prevNW();e.text==")"?e.matching.before("function"):a.before("function() ");a.updateBlock()}})}});
require.register("kaffeine/plugins/implicit_return.js",function(g,a,e){var n=e("../token");g.exports=function(a){a.each(function(){if(this.blockType&&this.blockType=="function"&&!this.global){var a=this.matching.prev.findRev(function(a){return a.whitespace||a.semi?null:true});if(!(a==this||a.text=="return"))if((a=a.findRev(function(a){if(a.rbracket)return a.matching;else if(a.lbracket&&a.curly){var i=a.blockType;if(i=="function")return a.prev.findRev(function(a){if(a.text=="function")return true});
else if(i=="object"){if(a.prev.whitespace||a.prev.semi||a.prev.lbracket)return true}else return false}else return a.prev.whitespace?a.prev.prev.text=="new"?a.prev.prev:true:a.prev.semi||a.prev.lbracket?true:null}))&&a.text!="return"){if(a.prev.prev){var i=a.prev.prev.text;if(i=="throw"||i=="return")return}a.before(new n.whitespace(" ")).before(new n.word("return"))}}})}});
require.register("kaffeine/plugins/implicit_vars.js",function(g,a,e){e("../token");g.exports=function(a){var e,g,i;a.each(function(a){var i=a.prev;if(a.text=="var")return a.next.space&&a.next.remove(),a.remove(),i});a.each(function(a){if(a.assign&&(e=a.prev.text,/^[A-Za-z0-9$_]*$/.test(e)&&!(a.prev.prev.operator&&a.prev.prev.text!=",")&&a.prev.prev.prev.text!="var")){g=i=this.findClosure();for(a=false;g;){if(g.vars[e]||g.args[e]){a=true;break}g=g.parent}a||(i.vars[e]=true)}})}});
require.register("kaffeine/plugins/multiline_strings.js",function(g,a,e){e("../token");g.exports=function(a){var e=/\n/;a.each(function(){if(this.string&&e.test(this.text))this.text=this.text.replace(/(\\)?\n/g,function(a,i){return i?"\\\n":"\\n\\\n"})})}});
require.register("kaffeine/plugins/operators.js",function(g,a,e){var n=e("../token");g.exports=function(a){a.each(function(a){if(a.operator){if(a.text=="||=")var i="|| ";else if(a.text==".=")i=".";else return;optoken=a.after(i);a.text="=";var e="";a.prev.findRev(function(a){if(a.whitespace||a.unknown)return true;e=a.text+e});var h=n.ize(e);i!="."&&h.tail().eaten.right.push(n.ize(" "));a.after(h,h.tail())}});var i=false;a.each(function(d){if(d.text=="<-"){var e=this.expressionStart().remove(this.prev).collectText(),
g=this.next.remove(this.next.expressionEnd(function(){})).collectText(),d=this.prev;this.replaceWith("__extend("+e+", "+g+")");if(!i){e=a.block;if(!e.global)throw"WTF!";e.matching.before(new n.word(w));i=true}return d}})};var w="\nfunction __extend(a,b) {\n  var c = {}, i;\n  a = a || {};\n  for(i in a) c[i] = a[i];\n  for(i in b) c[i] = b[i];\n  return c;\n}"});
require.register("kaffeine/plugins/pipe.js",function(g,a,e){var n=e("../token");g.exports=function(a){a.each(function(){if(this.text=="|"){var a=this.expressionStart().remove(this.prev),i=this.next.remove(this.next.expressionEnd(function(){return this.text=="|"})),d=this.prev;pair=n.bracket.pair("()");tokens=n.ize("__."+this.pipe_function+".call");tokens.append(pair.L);tokens.append("this, ");tokens.append(a);tokens.append(", ");tokens.append(i);tokens.append(pair.R);this.replaceWith(tokens);return d}})}});
require.register("kaffeine/plugins/pre_pipe.js",function(g,a,e){e("../token");g.exports=function(a){a.each(function(){if(this.text=="|"||this.text=="|.")if(this.expressionStart(),this.text=="|."||this.next.assign)this.text="__"+this.text.slice(1),delete this.operator,this.word=true;else{if(this.text!="|")throw"unknown pipe operation";this.pipe_function=this.next.text;this.next.remove();this.next.whitespace&&this.next.remove();return this.next}})}});
require.register("kaffeine/plugins/prototype.js",function(g,a,e){e("../token");g.exports=function(a){var e="";a.each(function(){if(this.namedFunction)e=this.namedFunction.text;else if(this.word&&this.text=="prototype"){if(this.prev.text==".")e=this.prev.prev.text}else{var a=this.next;if(this.text=="::"){this.spit(function(){return this.whitespace});var i=".prototype.";this.prev.word?e=this.prev.text:i=e+i;this.replaceWith(i)}return a}})}});
require.register("kaffeine/plugins/string_interpolation.js",function(g,a,e){function n(a){var e=false,a=a.replace(w,function(a,g,l){g||(e=true);return g?a.slice(1):'" + ('+l.replace(/\\"/g,'"')+') + "'});e&&(a="("+a+")");return a=a.replace(' + ""',"")}e("../token");g.exports=function(a){a.each(function(){if(this.string){if(/#{"$/.test(this.text)){var a="",d=this.next.find(function(){a+=this.text;if(this.string&&/^"}/.test(this.text))return true});this.text+=a;this.next.remove(d)}if(/^".*[#]/.test(this.text))return d=
this.next,this.replaceWith(n(this.text)),d}});a.each(function(){if(this.lbracket&&this.round&&this.next.lbracket&&this.next.round){var a=this.matching.prev;a.rbracket&&a.round&&(this.next.remove(),a.remove())}})};var w=/(\\)?#{(.*?)}/g});require.register("kaffeine/plugins/undouble_brackets.js",function(g,a,e){e("../token");g.exports=function(a){a.each(function(){if(this.lbracket&&this.round&&this.next.lbracket&&this.next.round){var a=this.matching.prev;a.rbracket&&a.round&&(this.next.remove(),a.remove())}})}});
require.register("kaffeine/token.js",function(g){function a(m){this.text=m;this.id=a.id++;this.eaten={left:[],right:[]}}function e(a){return a=a.replace(/\t/g,"  ").replace(/ *\n/g,"\n").replace(/\r\n|\r/g,"")}function n(m){function c(a){j?(j.next=a,a.prev=j,j=a):d=j=a}var m=e(m),k,f,A,b=0,d,j;for(A=0;A<a.klasses.length;A++)a.klasses[A].match=void 0;for(;b<m.length;){for(A=0;A<a.klasses.length;A++)if(k=a.klasses[A],f=a.getMatch(k,b,m))break;f?(c(new k(f)),b+=f.length):(c(new v(m.charAt(b))),b+=1)}return d=
w(d)}function w(a){var c=[];a.each(function(){this.bracket&&(this.lbracket?c.push(this):this.matchWith(c.pop()))});if(c.length)throw"unmatching number of brackets";a.each(function(){this.curly&&this.lbracket&&this.updateBlock()});a.normalize();return a}function v(m){a.call(this,m)}function i(m){a.call(this,m);this.newline=/\n/.test(m);this.space=!this.newline}function d(m){a.call(this,m);if(B.indexOf(m)>=0)this.keyword=true;if(m.match(/!$/))this.bang=true}function q(m){a.call(this,m)}function l(m){a.call(this,
m)}function h(m){a.call(this,m);this.single=this.text.match(/^\/\//)}function z(m){a.call(this,m);this.assign=/^=$/.test(m);this.comparison=F.indexOf(this.text)>=0;this.unary_operator=x.indexOf(this.text)>=0}function s(m){a.call(this,m)}function o(m){a.call(this,m);this.lbracket=m.match(/[\(\[\{]/);this.rbracket=!this.lbracket;if(m=="{"||m=="}")this.curly=true;else if(m=="("||m==")")this.round=true;else if(m=="["||m=="]")this.square=true}var r=function(a,c){var k=function(){};k.prototype=c.prototype;
a.__super__=c.prototype;a.prototype=new k;a.prototype.constructor=a;a.fn=a.prototype};a.id=0;a.fn=a.prototype;a.klasses=[i,d,q,h,l,z,o,s];a.fn.normalize=function(){this.each(function(){var a=this.next;this.next&&this.next.whitespace&&["for"].indexOf(this.text)>=0&&this.eatRight();if(this.space)a&&a.space&&this.eatRight(function(){return this.space});else if(this.comment)return a.eatLeft(),a.prev;else this.operator?(this.eat(function(){return this.whitespace}),this.eat(function(){return this.whitespace})):
this.rbracket&&this.prev.whitespace&&!this.matching.global&&this.eatLeft()});this.each(function(){this.addImpliedBraces()})};a.fn.addImpliedBraces=function(){function a(c){return c.block?c.block.matching:"if,for,while,try,else,catch".split(",").indexOf(c.text)>=0?a(c.next.matching.nextNW()):c.find(function(){if(this.lbracket)return this.matching;if(this.next.newline)return true;if(this.next.rbracket&&this.next.curly)return true})}if(!(this.block||"if,for,while,try,else,catch".split(",").indexOf(this.text)<
0)){var c=this.next.matching;if(c){var k=o.pair("{}");k.L.implied=true;k.R.implied=true;var f=c.nextNW();a(f).after(k.R);c.after(" ").after(k.L);this.indent();k.R.before(" ");k.L.updateBlock();k.L.eatLeft();k.R.eatLeft();k.R.prev.whitespace&&k.R.eatLeft()}}};a.fn.after=function(a){typeof a=="string"&&(a=n(a));tail=a.tail();if(this.next)this.next.prev=tail,tail.next=this.next;this.next=a;a.prev=this;return tail};a.fn.before=function(a){typeof a=="string"&&(a=n(a));tail=a.tail();if(this.prev)this.prev.next=
a,a.prev=this.prev;this.prev=tail;tail.next=this;return a};a.fn.head=function(){for(var a=this;a.prev;)a=a.prev;return a};a.fn.tail=function(){for(var a=this;a.next;)a=a.next;return a};a.fn.remove=function(a){a=a||this;if(a.next)a.next.prev=this.prev;if(this.prev)this.prev.next=a.next;this.prev=a.next=null;return this};a.fn.replaceWith=function(a){typeof a=="string"&&(a=n(a));a=this.after(a);this.remove();return a};a.fn.append=function(a){typeof a=="string"&&(a=n(a));var c=this.tail();c.next=a;a.prev=
c};a.fn.find=function(a,c){for(var k=this,f=0;k;){var b=a.call(k,k,f++);if(b===true)if(c)c--;else return k;if(b===false)return null;k=b?b:k.next}};a.fn.findRev=function(a,c){for(var k=this,f=0;k;){var b=a.call(k,k,f++);if(b===true)if(c)c--;else return k;if(b===false)return null;k=b?b:k.prev}};a.fn.prevNW=function(){return this.prev.findRev(function(){if(!this.whitespace)return true})};a.fn.nextNW=function(){return this.next.find(function(){if(!this.whitespace)return true})};a.fn.lineStart=function(){var a=
this.findRev(function(){var a;if(this.rbracket)return this.matching;a=this.prev;y=a.prev;if(a.lbracket&&a.curly&&a.blockType!="object")return true;if(a.semi)return true;if(a.whitespace){if(y.word)return true;if(y.rbracket)return true}});a.whitespace&&(a=a.nextNW());return a};a.fn.expressionStart=function(a){return this.findRev(function(){var c;if(this.rbracket)return this.matching;c=this.prev;if(c.whitespace||c.semi||c.assign||c.lbracket)return true;if(a&&a.call(c,c))return true})};a.fn.expressionEnd=
function(a){return this.find(function(){if(this.lbracket)return this.matching;if(this.block)return this.block;var c=this.next;if(c.whitespace||c.semi||c.assign||c.rbracket)return true;if(a&&a.call(c,c))return true})};a.getMatch=function(a,c,k){if(a.match!==false){if(!a.match||a.match.index<c)if(a.match=null,a.regex.lastIndex=c,a.match=a.regex.exec(k),!a.match)a.match=false;if(a.match&&a.match.index==c)return a.extract?a.extract(c,k):a.match[0]}};a.fn.each=function(m,c){for(var k=this,c=c||"next";k;){var f=
m.call(k,k);if(f===false)break;last=k;k=f instanceof a?f:k[c]}return last.head()};a.fn.eat=function(a){this.eatLeft(a);this.eatRight(a)};a.fn.eatLeft=function(a){var c=this.prev;if(c&&(!a||a.call(c)))c.remove(),this.eaten.left.unshift(c),this.newline=this.myText().match(/\n/)};a.fn.eatRight=function(a){var c=this.next;if(c&&(!a||a.call(c)))c.remove(),this.eaten.right.push(c),this.newline=this.myText().match(/\n/)};a.fn.spit=function(a){this.spitLeft(a);this.spitRight(a)};a.fn.spitLeft=function(a){var c=
this.eaten.left.shift();if(c&&(!a||a.call(c)))this.before(c),this.newline=this.myText().match(/\n/);return c};a.fn.spitRight=function(a){var c=this.eaten.right.pop();if(c&&(!a||a.call(c)))this.after(c),this.newline=this.myText().match(/\n/);return c};a.fn.myTextNoComments=function(){return this.comment?"":this.myText()};a.fn.myText=function(){var a=[],c;if(this.implied)return"";for(c=0;c<this.eaten.left.length;c++)a.push(this.eaten.left[c].myText());a.push(this.text);this.vars&&(c=this.declareVariables(),
this.nextNW().before(new d(c)));for(c=0;c<this.eaten.right.length;c++)a.push(this.eaten.right[c].myText());return a.join("")};a.fn.collectText=function(a){for(var c=[],k=this;k;){c.push(k.myText());if(k==a)break;k=k.next}return c.join("")};a.fn.collectTextNoComments=function(a){for(var c=[],k=this;k;){c.push(k.myTextNoComments());if(k==a)break;k=k.next}return c.join("")};a.fn.findClosure=function(){return this.parent=this.prev.findRev(function(a){if(a.rbracket)return a.matching.prev;if(a.blockType==
"function")return true})};a.fn.prevNewline=function(a,c){return(a?this:this.prev).findRev(function(a){if(a.newline)return true;if(c&&a.rbracket)return a.matching.prev})};a.fn.nextNewline=function(a,c){return(a?this:this.next).find(function(a){if(a.newline)return true;if(c&&a.lbracket)return a.matching.next})};a.fn.nextNewlineOrRbracket=function(){return this.next.find(function(a){if(a.rbracket)return true;if(a.newline)return true;if(a.lbracket)return a.matching.next})};a.fn.followingWhitespaceWithNewline=
function(){return this.next.find(function(){return this.newline?true:this.whitespace?null:false})};a.fn.indent=function(){var a=this.prevNewline("include");return!a?"":(a=a.next.myText().match(/^( *)/))?a[1]:""};a.fn.getUnusedVar=function(a){for(var c=10,b,a=a||"_";;){b=c.toString(36);if(!this.vars[a+b])break;c++}return a+b};a.fn.cacheExpression=function(a){var a=a||"_xpr",c=o.pair("()");this.findClosure().vars[a]=true;this.expressionStart().before(new z("=")).before(new d(a)).before(c.L);this.expressionEnd().after(c.R)};
r(v,a);v.fn.unknown=true;r(i,a);i.fn.whitespace=true;i.regex=/ +|\n/g;var B="if for while else try catch function return var".split(" ");r(d,a);d.fn.word=true;d.regex=/[A-Za-z0-9_$]+!?/g;r(q,a);q.fn.string=true;q.regex=/['"]/g;r(l,a);l.fn.regex=true;l.fn.string=true;l.regex=/\/[^*\/ ][^\n]*\//g;r(h,a);h.fn.comment=true;h.regex=/\/\*|\/\//g;var F="<=,<,>=,>,==,!=,===,!==,||,&&".split(","),x="++,--,!,~,&,|".split(",");r(z,a);z.fn.operator=true;z.regex=/[!%^&*\-=+:,.|\\~<>\?]+|\/|\/=/g;r(s,a);s.fn.semi=
true;s.regex=/;/g;r(o,a);o.fn.bracket=true;o.regex=/[\(\)\[\]\{\}]/g;o.fn.matchWith=function(a){a.matching=this;this.matching=a};o.pair=function(a){var c=a.split(""),a=new o(c[0]),c=new o(c[1]);a.matchWith(c);return{L:a,R:c}};var b="if for while else try catch function".split(" ");o.fn.updateBlock=function(){var a=false,c=false,k;this.prev&&(k=this.prev.findRev(function(f){return f.whitespace?null:f.rbracket&&f.rbracket?(a=f.matching,f.matching.prev):f.word?b.indexOf(f.text)>=0?true:c?false:(c=f,
null):false}));k?(this.blockType=k.text,k.block=this,k.namedFunction=c,k.bracketExpression=a):this.blockType="object";if(this.blockType=="function")this.findClosure(),this.args=this.findArgs(),this.vars={}};o.fn.findArgs=function(){if(!this.prev)return{};var a={},c=this.prev.whitespace?this.prev.prev:this.prev;if(c.matching){var b=c.matching.collectText(c).replace(/[\(\) ]/g,""),c=b.split(",");if(b.length)for(b=0;b<c.length;b++)a[c[b]]=true;return a}};o.fn.declareVariables=function(){var a=[],c;for(c in this.vars){var b=
c;typeof this.vars[c]=="string"&&(b+=" = "+this.vars[c]);a.push(b)}return!a.length?"":"var "+a.join(", ")+"; "};q.extract=function(a,c){for(var b=c.charAt(a),f=a+1,d,e=b;f<c.length;){var h=c.charAt(f);e+=h;if(h==b&&d!="\\")return e;d=h;f+=1}};h.extract=function(a,c){for(var b="",f="",d=c.charAt(a+1);a<c.length;){var e=c.charAt(a);if(d=="/"&&e=="\n")return b;if(d=="*"&&e=="/"&&f=="*")return b+"/";b+=e;a+=1;f=e}};l.extract=function(a,c){for(var b="/",f="",d;a<c.length;){var e=c.charAt(a+1);b+=e;f=f==
"\\";if(e=="/"&&!f&&!d){d=c.charAt(a+2);if(d=="m"||d=="g"||d=="i")b+=d;return b}else e=="["&&!f?d=true:e=="]"&&!f&&d&&(d=false);a+=1;f=e}};g.exports={whitespace:i,operator:z,string:q,word:d,comment:h,bracket:o,unknown:v,semi:s,ize:n,postprocess:w,base:a}});
require.register("kaffeine/uglify/parse-js.js",function(g,a){function e(a){a=a.charCodeAt(0);return a>=48&&a<=57||a>=65&&a<=90||a>=97&&a<=122}function n(a){return e(a)||a=="$"||a=="_"}function w(a){a=a.charCodeAt(0);return a>=48&&a<=57}function v(a){if(k.test(a))return parseInt(a.substr(2),16);else if(f.test(a))return parseInt(a.substr(1),8);else if(A.test(a))return parseFloat(a)}function i(a,C,b,c){this.message=a;this.line=C;this.col=b;this.pos=c;try{({})()}catch(f){this.stack=f.stack}}function d(a,
b,c){return a.type==b&&(c==null||a.value==c)}function q(a,C){function f(){return u.text.charAt(u.pos)}function d(a){var b=u.text.charAt(u.pos++);if(a&&!b)throw J;b=="\n"?(u.newline_before=true,++u.line,u.col=0):++u.col;return b}function k(a,b){var c=u.text.indexOf(a,u.pos);if(b&&c==-1)throw J;return c}function h(a,c){u.regex_allowed=a=="operator"&&!B(T,c)||a=="keyword"&&B(b,c)||a=="punc"&&B(j,c);var C={type:a,value:c,line:u.tokline,col:u.tokcol,pos:u.tokpos,nlb:u.newline_before};u.newline_before=
false;return C}function A(a){for(var c="",b=f(),C=0;b&&a(b,C++);)c+=d(),b=f();return c}function x(a){throw new i(a,u.tokline,u.tokcol,u.tokpos);}function g(a){var b=false,c=false,C=false,f=A(function(f,d){if(f=="x"||f=="X")return C?false:C=true;if(!C&&(f=="E"||f=="e"))return b?false:b=c=true;if(f=="-")return c||d==0&&!a?true:false;c=false;return e(f)||f=="."});a&&(f=a+f);var d=v(f);if(isNaN(d))x("Invalid syntax: "+f);else return h("num",d)}function t(){var a=d(true);switch(a){case "n":return"\n";
case "r":return"\r";case "t":return"\t";case "b":return"\u0008";case "v":return"\u000b";case "f":return"\u000c";case "0":return"\x00";case "x":return String.fromCharCode(l(2));case "u":return String.fromCharCode(l(4));default:return a}}function l(a){for(var c=0;a>0;--a){var b=parseInt(d(true),16);isNaN(b)&&x("Invalid hex-character pattern in string");c=c<<4|b}return c}function r(){return L("Unterminated string constant",function(){for(var a=d(),c="";;){var b=d(true);if(b=="\\")b=t();else if(b==a)break;
c+=b}return h("string",c)})}function o(){d();var a=k("\n"),b;a==-1?(b=u.text.substr(u.pos),u.pos=u.text.length):(b=u.text.substring(u.pos,a),u.pos=a);return h("comment1",b)}function q(){d();return L("Unterminated multiline comment",function(){var a=k("*/",true),b=u.text.substring(u.pos,a),c=h("comment2",b);u.pos=a+2;u.newline_before=b.indexOf("\n")>=0;return c})}function z(){return L("Unterminated regular expression",function(){for(var a=false,b="",c,f=false;c=d(true);)if(a)b+="\\"+c,a=false;else if(c==
"[")f=true,b+=c;else if(c=="]"&&f)f=false,b+=c;else if(c=="/"&&!f)break;else c=="\\"?a=true:b+=c;a=A(function(a){return B(G,a)});return h("regexp",[b,a])})}function s(a){function b(a){var c=a+f();return B(M,c)?(d(),b(c)):a}return h("operator",b(a||d()))}function L(a,b){try{return b()}catch(c){if(c===J)x(a);else throw c;}}function P(){for(;B(O,f());)d();u.tokline=u.line;u.tokcol=u.col;u.tokpos=u.pos;var a=f();if(!a)return h("eof");if(w(a))return g();if(a=='"'||a=="'")return r();if(B(E,a))return h("punc",
d());if(a==".")return d(),w(f())?g("."):h("punc",".");if(a=="/")return I();if(B(c,a))return s();if(n(a))return a=A(n),!B(F,a)?h("name",a):B(M,a)?h("operator",a):B(m,a)?h("atom",a):h("keyword",a);x("Unexpected character '"+a+"'")}var u={text:a.replace(/\r\n?|[\n\u2028\u2029]/g,"\n"),pos:0,tokpos:0,line:0,tokline:0,col:0,tokcol:0,newline_before:false,regex_allowed:false},I=C?function(){d();switch(f()){case "/":return o(),P();case "*":return q(),P()}return u.regex_allowed?z():s("/")}:function(){d();
switch(f()){case "/":return o();case "*":return q()}return u.regex_allowed?z():s("/")};P.context=function(a){a&&(u=a);return u};return P}function l(a,b,c){this.name=a;this.start=b;this.end=c}function h(a){var b=o(arguments,1);return function(){return a.apply(this,b.concat(o(arguments)))}}function z(a){a instanceof Function&&(a=a());for(var b=1,c=arguments.length;--c>0;++b)arguments[b]();return a}function s(a){for(var b={},c=0;c<a.length;++c)b[a[c]]=true;return b}function o(a,b){return Array.prototype.slice.call(a,
b==null?0:b)}function r(a,b){for(var c=b.length;--c>=0;)if(b[c]===a)return true;return false}function B(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var F=s("break,case,catch,const,continue,default,delete,do,else,finally,for,function,if,in,instanceof,new,return,switch,throw,try,typeof,var,void,while,with,NaN".split(",")),x=s("abstract,boolean,byte,char,class,debugger,double,enum,export,extends,final,float,goto,implements,import,int,interface,long,native,package,private,protected,public,short,static,super,synchronized,throws,transient,volatile".split(",")),
b=s(["return","new","delete","throw"]),m=s(["false","null","true","undefined","NaN"]),c=s("+-*&%=<>!?|~^".split("")),k=/^0x[0-9a-f]+$/i,f=/^0[0-7]+$/,A=/^\d*\.?\d*(?:e-?\d*(?:\d\.?|\.?\d)\d*)?$/i,M=s("in,instanceof,typeof,new,void,delete,++,--,+,-,!,~,&,|,^,*,/,%,>>,<<,>>>,<,>,<=,>=,==,===,!=,!==,?,=,+=,-=,/=,*=,%=,>>=,<<=,>>>=,~=,%=,|=,^=,&&,||".split(",")),O=s(" \n\r\t".split("")),j=s("[{}(,.;:".split("")),E=s("[]{}(),;:".split("")),G=s("gmsiy".split(""));i.prototype.toString=function(){return this.message+
" (line: "+this.line+", col: "+this.col+", pos: "+this.pos+")\n\n"+this.stack};var J={},t=s("typeof,void,delete,--,++,!,~,-,+".split(",")),T=s(["--","++"]),L=function(a,b,c){for(;c<a.length;)b[a[c]]=a[c].substr(0,a[c].length-1),c++;return b}("+=,-=,/=,*=,%=,>>=,<<=,>>>=,~=,%=,|=,^=".split(","),{"=":true},0),W=function(a,b){for(var c=0,f=1;c<a.length;++c,++f)for(var d=a[c],j=0;j<d.length;++j)b[d[j]]=f;return b}([["||"],["&&"],["|"],["^"],["&"],["==","===","!=","!=="],"<,>,<=,>=,in,instanceof".split(","),
[">>","<<",">>>"],["+","-"],["*","/","%"]],{}),S=s(["for","do","while","switch"]),I=s(["atom","num","string","regexp","name"]);l.prototype.toString=function(){return this.name};a.tokenizer=q;a.parse=function(a,b,c){function f(a,b){return d(p.token,a,b)}function j(){p.prev=p.token;p.peeked?(p.token=p.peeked,p.peeked=null):p.token=p.input();return p.token}function E(a,b,c,f){var j=p.input.context();throw new i(a,b!=null?b:j.tokline,c!=null?c:j.tokcol,f!=null?f:j.tokpos);}function e(a){if(a==null)a=
p.token;E("Unexpected token: "+a.type+" ("+a.value+")",a.line,a.col)}function k(a,b){if(f(a,b))return j();var c=p.token;E("Unexpected token "+p.token.type+", expected "+a,c.line,c.col)}function A(a){return k("punc",a)}function G(){return!b&&(p.token.nlb||f("eof")||f("punc","}"))}function x(){f("punc",";")?j():G()||e()}function m(){return o(arguments)}function g(){A("(");var a=D();A(")");return a}function M(a){switch(p.token.type){case "num":case "string":case "regexp":case "operator":case "atom":return n();
case "name":var b;if(d(p.peeked||(p.peeked=p.input()),"punc",":")){b=z(p.token.value,j,j);p.labels.push(b);var c=p.token,C=H();B(S,C[0])||e(c);p.labels.pop();b=m("label",b,C)}else b=n();return b;case "punc":switch(p.token.value){case "{":j();for(b=[];!f("punc","}");)b.push(H());j();return m("block",b);case "[":case "(":return n();case ";":return j(),m("block");default:e()}case "keyword":switch(z(p.token.value,j)){case "break":return O("break");case "continue":return O("continue");case "case":return a||
e(),m("case",z(D,h(A,":")));case "debugger":return x(),m("debugger");case "default":return a||e(),A(":"),m("default");case "do":return b=N(H),k("keyword","while"),m("do",z(g,x),b);case "for":return A("("),(b=f("keyword","var"))&&j(),f("name")&&d(p.peeked||(p.peeked=p.input()),"operator","in")?(c=p.token.value,j(),j(),C=D(),A(")"),b=m("for-in",b,c,C,N(H))):(b=f("punc",";")?null:b?w():D(),A(";"),c=f("punc",";")?null:D(),A(";"),C=f("punc",")")?null:D(),A(")"),b=m("for",b,c,C,N(H))),b;case "function":return J(true);
case "if":return c=g(),C=H(),f("keyword","else")&&(j(),b=H()),m("if",c,C,b);case "return":return p.in_function==0&&E("'return' outside of function"),m("return",f("punc",";")?(j(),null):G()?null:z(D,x));case "switch":return m("switch",g(),N(h(s,true)));case "throw":return m("throw",z(D,x));case "try":b=s();if(f("keyword","catch"))j(),A("("),f("name")||E("Name expected"),C=p.token.value,j(),A(")"),C=[C,s()];f("keyword","finally")&&(j(),c=s());return m("try",b,C,c);case "var":return z(w,x);case "const":return z(F,
x);case "while":return m("while",g(),N(H));case "with":return m("with",g(),H());default:e()}}}function n(){return m("stat",z(D,x))}function O(a){p.in_loop==0&&E(a+" not inside a loop or switch");var b=f("name")?p.token.value:null;b!=null&&(j(),r(b,p.labels)||E("Label "+b+" without matching loop or statement"));x();return m(a,b)}function J(a){var b=f("name")?z(p.token.value,j):null;a&&!b&&e();A("(");return m(a?"defun":"function",b,function(a,b){for(;!f("punc",")");)a?a=false:A(","),f("name")||e(),
b.push(p.token.value),j();j();return b}(true,[]),function(){++p.in_function;var a=s();--p.in_function;return a}())}function s(a){A("{");for(var b=[];!f("punc","}");)b.push(H(a));j();return b}function u(){for(var a=[];;){f("name")||e();var b=p.token.value;j();f("operator","=")?(j(),a.push([b,D(false)])):a.push([b]);if(!f("punc",","))break;j()}return a}function w(){return m("var",u())}function F(){return m("const",u())}function v(a){if(f("operator","new")){j();var a=v(false),c;f("punc","(")?(j(),c=
Q(")")):c=[];return K(m("new",a,c),true)}if(f("operator")&&B(t,p.token.value))return V("unary-prefix",z(p.token.value,j),v(a));if(f("punc")){switch(p.token.value){case "(":return j(),K(z(D,h(A,")")),a);case "[":return j(),K(m("array",Q("]",!b)),a);case "{":j();c=K;var d;d=true;for(var E=[];!f("punc","}");){d?d=false:A(",");if(!b&&f("punc","}"))break;var k;a:{switch(p.token.type){case "num":case "string":k=z(p.token.value,j);break a}k=U()}A(":");var $=D(false);E.push([k,$])}j();d=m("object",E);return c(d,
a)}e()}if(f("keyword","function"))return j(),K(J(false),a);if(B(I,p.token.type))return c=p.token.type=="regexp"?m("regexp",p.token.value[0],p.token.value[1]):m(p.token.type,p.token.value),K(z(c,j),a);e()}function Q(a,b){for(var c=true,d=[];!f("punc",a);){c?c=false:A(",");if(b&&f("punc",a))break;d.push(D(false))}j();return d}function U(){switch(p.token.type){case "name":case "operator":case "keyword":case "atom":return z(p.token.value,j);default:e()}}function K(a,b){if(f("punc","."))return j(),K(m("dot",
a,U()),b);if(f("punc","["))return j(),K(m("sub",a,z(D,h(A,"]"))),b);return b&&f("punc","(")?(j(),K(m("call",a,Q(")")),true)):b&&f("operator")&&B(T,p.token.value)?z(h(V,"unary-postfix",p.token.value,a),j):a}function V(a,b,c){(b=="++"||b=="--")&&!X(c)&&E("Invalid use of "+b+" operator");return m(a,b,c)}function R(a,b){var c=f("operator")?p.token.value:null,d=c!=null?W[c]:null;return d!=null&&d>b?(j(),d=R(v(true),d),R(m("binary",c,a,d),b)):a}function aa(a){arguments.length==0&&(a=true);var b=R(v(true),
0);if(f("operator","?")){j();var c=D();A(":");return m("conditional",b,c,D(a))}return b}function X(a){a=a[0];return a=="name"||a=="dot"||a=="sub"}function Y(a){arguments.length==0&&(a=true);var b=aa(a),c=p.token.value;if(f("operator")&&B(L,c)){if(X(b))return j(),m("assign",L[c],b,Y(a));E("Invalid assignment")}return b}function D(a){arguments.length==0&&(a=true);var b=Y(a);return a&&f("punc",",")?(j(),m("seq",b,D())):b}function N(a){try{return++p.in_loop,a()}finally{--p.in_loop}}var p={input:q(a,true),
token:null,prev:null,peeked:null,in_function:0,in_loop:0,labels:[]};p.token=j();var H=c?function(a){var b=p.token,a=M(a),b=new l(a[0],b,p.prev);a[0]=b;return a}:M;return m("toplevel",function(a){for(;!f("eof");)a.push(H());return a}([]))};a.slice=o;a.curry=h;a.member=r;a.array_to_hash=s;a.PRECEDENCE=W;a.KEYWORDS_ATOM=m;a.RESERVED_WORDS=x;a.KEYWORDS=F;a.ATOMIC_START_TOKEN=I;a.is_alphanumeric_char=e});
require.register("kaffeine/uglify/process.js",function(g,a,e){function n(){function a(c){return c.map(function(a){var c=[a[0]];a.length>1&&(c[1]=b(a[1]));return c})}function b(a){if(a==null)return null;try{e.push(a);var b=a[0],h=c[b];if(h){var x=h.apply(a,a.slice(1));if(x!=null)return x}h=d[b];return h.apply(a,a.slice(1))}finally{e.pop()}}var d={string:function(a){return["string",a]},num:function(a){return["num",a]},name:function(a){return["name",a]},toplevel:function(a){return["toplevel",a.map(b)]},
block:function(a){var c=["block"];a!=null&&c.push(a.map(b));return c},"var":function(b){return["var",a(b)]},"const":function(b){return["const",a(b)]},"try":function(a,c,d){return["try",a.map(b),c!=null?[c[0],c[1].map(b)]:null,d!=null?d.map(b):null]},"throw":function(a){return["throw",b(a)]},"new":function(a,c){return["new",b(a),c.map(b)]},"switch":function(a,c){return["switch",b(a),c.map(b)]},"case":function(a){return["case",b(a)]},"default":function(){return["default"]},"break":function(a){return["break",
a]},"continue":function(a){return["continue",a]},conditional:function(a,c,d){return["conditional",b(a),b(c),b(d)]},assign:function(a,c,d){return["assign",a,b(c),b(d)]},dot:function(a){return["dot",b(a)].concat(s(arguments,1))},call:function(a,c){return["call",b(a),c.map(b)]},"function":function(a,c,d){return["function",a,c.slice(),d.map(b)]},defun:function(a,c,d){return["defun",a,c.slice(),d.map(b)]},"if":function(a,c,d){return["if",b(a),b(c),b(d)]},"for":function(a,c,d,e){return["for",b(a),b(c),
b(d),b(e)]},"for-in":function(a,c,d,e){return["for-in",a,c,b(d),b(e)]},"while":function(a,c){return["while",b(a),b(c)]},"do":function(a,c){return["do",b(a),b(c)]},"return":function(a){return["return",b(a)]},binary:function(a,c,d){return["binary",a,b(c),b(d)]},"unary-prefix":function(a,c){return["unary-prefix",a,b(c)]},"unary-postfix":function(a,c){return["unary-postfix",a,b(c)]},sub:function(a,c){return["sub",b(a),b(c)]},object:function(a){return["object",a.map(function(a){return[a[0],b(a[1])]})]},
regexp:function(a,b){return["regexp",a,b]},array:function(a){return["array",a.map(b)]},stat:function(a){return["stat",b(a)]},seq:function(){return["seq"].concat(s(arguments).map(b))},label:function(a,c){return["label",a,b(c)]},"with":function(a,c){return["with",b(a),b(c)]},atom:function(a){return["atom",a]}},c={},e=[];return{walk:b,with_walkers:function(a,b){var d={},e;for(e in a)h(a,e)&&(d[e]=c[e],c[e]=a[e]);try{return b()}finally{for(e in d)h(d,e)&&(d[e]?c[e]=d[e]:delete c[e])}},parent:function(){return e[e.length-
2]},stack:function(){return e}}}function w(a){this.names={};this.mangled={};this.rev_mangled={};this.cname=-1;this.refs={};this.uses_eval=this.uses_with=false;this.parent=a;this.children=[];a?(this.level=a.level+1,a.children.push(this)):this.level=0}function v(a){function b(a){e=new w(e);try{var b=e.body=a();b.scope=e;return b}finally{e=e.parent}}function d(a){return e.define(a)}function c(a,c,e){return[this[0],d(a),c,b(function(){c.map(d);return e.map(g)})]}var e=null,f=n(),g=f.walk,i=[];return b(function(){function l(a,
b){for(b=a.children.length;--b>=0;)l(a.children[b]);for(b in a.refs)if(h(a.refs,b))for(var c=a.has(b),d=a;d;d=d.parent)if(d.refs[b]=c,d===c)break}var j=f.with_walkers({"function":c,defun:c,"with":function(){for(var a=e;a;a=a.parent)a.uses_with=true},"var":function(a){a.map(function(a){d(a[0])})},"const":function(a){a.map(function(a){d(a[0])})},"try":function(a,c,j){if(c!=null)return["try",a.map(g),b(function(){return[d(c[0]),c[1].map(g)]}),j!=null?j.map(g):null]},name:function(a){a=="eval"&&i.push(e);
e.refs[a]=true},"for-in":function(a,b){a&&d(b)}},function(){return g(a)});i.map(function(a){if(!a.has("eval"))for(;a;)a.uses_eval=true,a=a.parent});l(e);return j})}function i(a,b){function e(a){a==null&&(a="");b&&(a=d(" ",b.indent_start+w*b.indent_level)+a);return a}function c(a,b){b==null&&(b=1);w+=b;try{return a.apply(null,s(arguments,1))}finally{w-=b}}function k(a){if(b)return a.join(" ");for(var c=[],d=0;d<a.length;++d){var j=a[d+1];c.push(a[d]);j&&(/[a-z0-9_\x24]$/i.test(a[d].toString())&&/^[a-z0-9_\x24]/i.test(j.toString())||
/[\+\-]$/.test(a[d].toString())&&/^[\+\-]/.test(j.toString()))&&c.push(" ")}return c.join("")}function f(a){return a.join(","+B)}function g(a){for(var b=t(a),c=1;c<arguments.length;++c){var d=arguments[c];if(d instanceof Function&&d(a)||a[0]==d)return"("+b+")"}return b}function i(a,b,c){var d="function";a&&(d+=" "+j(a));d+="("+f(b.map(j))+")";return k([d,G(c)])}function n(a){return JSON.stringify(a)}function j(a){return a.toString()}function E(a){for(var c=[],d=a.length-1,j=0;j<=d;++j){var f=t(a[j]);
f!=";"&&(!b&&j==d&&(f=f.replace(/;+\s*$/,"")),c.push(f))}return c.map(e)}function G(a){return!a?";":a.length==0?"{}":"{"+v+c(function(){return E(a).join(v)})+v+e("}")}function J(a){var b=a[0],a=a[1];a!=null&&(b=k([b,"=",t(a)]));return b}function t(a){var b=a[0],c=S[b];if(!c)throw Error("Can't find generator for \""+b+'"');return c.apply(b,a.slice(1))}b&&(b=q(b,{indent_start:0,indent_level:4,quote_keys:false,space_colon:false}));var w=0,v=b?"\n":"",B=b?" ":"",S={string:n,num:function(a){return String(a)},
name:j,toplevel:function(a){return E(a).join(v+v)},block:G,"var":function(a){return"var "+f(a.map(J))+";"},"const":function(a){return"const "+f(a.map(J))+";"},"try":function(a,b,c){a=["try",G(a)];b&&a.push("catch","("+b[0]+")",G(b[1]));c&&a.push("finally",G(c));return k(a)},"throw":function(a){return k(["throw",t(a)])+";"},"new":function(a,b){b=b.length>0?"("+f(b.map(t))+")":"";return k(["new",g(a,"seq","binary","conditional","assign","dot")+b])},"switch":function(a,b){return k(["switch","("+t(a)+
")",G(b)])},"case":function(a){return k(["\u0008case",t(a)+":"])},"default":function(){return"\u0008default:"},"break":function(a){var b="break";a!=null&&(b+=" "+j(a));return b+";"},"continue":function(a){var b="continue";a!=null&&(b+=" "+j(a));return b+";"},conditional:function(a,b,c){return k([g(a,"assign","seq"),"?",g(b,"seq"),":",g(c,"seq")])},assign:function(a,b,c){a&&a!==true?a+="=":a="=";return k([t(b),a,t(c)])},dot:function(a){var b=t(a),c=1;for(h(F,a[0])||(b="("+b+")");c<arguments.length;)b+=
"."+j(arguments[c++]);return b},call:function(a,b){var c=t(a);h(F,a[0])||(c="("+c+")");return c+"("+f(b.map(t))+")"},"function":i,defun:i,"if":function(a,b,c){a="("+t(a)+")";if(c)a:{for(var d=b;;){var j=d[0];if(j=="if"){if(!d[3]){b=t(["block",[b]]);break a}d=d[3]}else if(j=="while"||j=="do")d=d[2];else if(j=="for"||j=="for-in")d=d[4];else break}b=t(b)}else b=t(b);b=["if",a,b];c&&b.push("else",t(c));return k(b)},"for":function(a,b,c,d){var j=["for"],a=(a!=null?t(a):"").replace(/;*\s*$/,";"+B),b=(b!=
null?t(b):"").replace(/;*\s*$/,";"+B),c=(c!=null?t(c):"").replace(/;*\s*$/,""),a=a+b+c;a=="; ; "&&(a=";;");j.push("("+a+")",t(d));return k(j)},"for-in":function(a,b,c,d){var e=k(["for","("]);a&&(e+="var ");e+=k([j(b)+" in "+t(c)+")",t(d)]);return e},"while":function(a,b){return k(["while","("+t(a)+")",t(b)])},"do":function(a,b){return k(["do",t(b),"while","("+t(a)+")"])+";"},"return":function(a){var b=["return"];a!=null&&b.push(t(a));return k(b)+";"},binary:function(a,b,c){var d=t(b),j=t(c);if(o(b[0],
["assign","conditional","seq"])||b[0]=="binary"&&r[a]>r[b[1]])d="("+d+")";if(o(c[0],["assign","conditional","seq"])||c[0]=="binary"&&r[a]>=r[c[1]])j="("+j+")";return k([d,a,j])},"unary-prefix":function(a,b){var c=t(b);h(F,b[0])||b[0]=="num"||(c="("+c+")");return a+(z.is_alphanumeric_char(a.charAt(0))?" ":"")+c},"unary-postfix":function(a,b){var c=t(b);h(F,b[0])||b[0]=="num"||(c="("+c+")");return c+a},sub:function(a,b){var c=t(a);h(F,a[0])||(c="("+c+")");return c+"["+t(b)+"]"},object:function(a){return a.length==
0?"{}":"{"+v+c(function(){return a.map(function(a){var c=a[0],a=t(a[1]);if(b&&b.quote_keys||!l(c))c=n(c);return e(k(b&&b.space_colon?[c,":",a]:[c+":",a]))}).join(","+v)})+v+e("}")},regexp:function(a,b){return"/"+a+"/"+b},array:function(a){return a.length==0?"[]":k(["[",f(a.map(t)),"]"])},stat:function(a){return t(a).replace(/;*\s*$/,";")},seq:function(){return f(s(arguments).map(t))},label:function(a,b){return k([j(a),":",t(b)])},"with":function(a,b){return k(["with","("+t(a)+")",t(b)])},atom:function(a){return j(a)},
comment1:function(a){return"//"+a+"\n"},comment2:function(a){return"/*"+a+"*/"}},I=t(a);if(b)var Z=d(" ",b.indent_level/2)+"\u0008",I=I.replace(RegExp(Z,"g"),"");else I=I.replace(/\x08/g,"");return I}function d(a,b){if(b<=0)return"";if(b==1)return a;var e=d(a,b>>1);e+=e;b&1&&(e+=a);return e}function q(a,b){var d={};a===true&&(a={});for(var c in b)h(b,c)&&(d[c]=a&&h(a,c)?a[c]:b[c]);return d}function l(a){return/^[a-z_$][a-z0-9_$]*$/i.test(a)&&!h(z.KEYWORDS_ATOM,a)&&!h(z.RESERVED_WORDS,a)&&!h(z.KEYWORDS,
a)}function h(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var z=e("./parse-js"),s=z.slice,o=z.member,r=z.PRECEDENCE,B=function(){return function(a){var b="";do b="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$_".charAt(a%54)+b,a=Math.floor(a/54);while(a>0);return b}}();w.prototype={has:function(a){for(var b=this;b;b=b.parent)if(h(b.names,a))return b},has_mangled:function(a){for(var b=this;b;b=b.parent)if(h(b.rev_mangled,a))return b},toJSON:function(){return{names:this.names,uses_eval:this.uses_eval,
uses_with:this.uses_with}},next_mangled:function(){for(;;){var a=B(++this.cname),b;b=this.has_mangled(a);if(!(b&&this.refs[b.rev_mangled[a]]===b)&&(b=this.has(a),(!b||!((b.uses_eval||b.uses_with)&&this.refs[a]===b))&&!(h(this.refs,a)&&this.refs[a]==null)&&l(a)))return a}},get_mangled:function(a,b){if(this.uses_eval||this.uses_with)return a;var d=this.has(a);if(!d)return a;if(h(d.mangled,a))return d.mangled[a];if(!b)return a;var c=d.next_mangled();d.rev_mangled[c]=a;return d.mangled[a]=c},define:function(a){if(a!=
null)return this.names[a]=a}};var F=z.array_to_hash("name,array,string,dot,sub,call,regexp".split(","));a.ast_walker=n;a.ast_mangle=function(a,b){function d(a,c){return!b&&!l.parent?a:l.get_mangled(a,c)}function c(a,b,c){a&&(a=d(a));c=e(c.scope,function(){b=b.map(function(a){return d(a)});return c.map(i)});return[this[0],a,b,c]}function e(a,b){var c=l;l=a;for(var f in a.names)h(a.names,f)&&d(f,true);try{var g=b();g.scope=a;return g}finally{l=c}}function f(a){return a.map(function(a){return[d(a[0]),
i(a[1])]})}var g=n(),i=g.walk,l;return g.with_walkers({"function":c,defun:c,"var":function(a){return["var",f(a)]},"const":function(a){return["const",f(a)]},name:function(a){return["name",d(a)]},"try":function(a,b,c){return["try",a.map(i),b?e(b.scope,function(){return[d(b[0]),b[1].map(i)]}):null,c!=null?c.map(i):null]},toplevel:function(a){return e(this.scope,function(){return["toplevel",a.map(i)]})},"for-in":function(a,b,c,e){return["for-in",a,d(b),i(c),i(e)]}},function(){return i(v(a))})};a.ast_squeeze=
function(a,b){function d(a,b,e){return[this[0],a,b,c(e.map(r))]}function c(a){for(var c,d=0,e=[];d<a.length;++d)c=a[d],c[0]=="block"?c[1]&&e.push.apply(e,c[1]):e.push(c);for(var a=null,d=0,f=[];d<e.length;++d)c=e[d],a&&(c[0]=="var"&&a[0]=="var"||c[0]=="const"&&a[0]=="const")?a[1]=a[1].concat(c[1]):(f.push(c),a=c);if(!b.make_seqs)return f;a=null;d=0;for(e=[];d<f.length;++d)c=f[d],a?c[0]=="stat"?a.push(c[1]):c[0]=="seq"?a.push.apply(a,s(c,1)):(a=null,e.push(c)):c[0]=="stat"?(a=["seq",c[1]],e.push(["stat",
a])):e.push(c);return e.map(r)}function e(a,b){return i(a).length>i(b[0]=="stat"?b[1]:b).length?b:a}function f(a,b,c){return a[0]=="unary-prefix"&&a[1]=="!"?c?["conditional",a[2],c,b]:["binary","||",a[2],b]:c?["conditional",a,b,c]:["binary","&&",a,b]}function h(a){return!a||a[0]=="block"&&(!a[1]||a[1].length==0)}var b=q(b,{make_seqs:true}),g=n(),r=g.walk;return g.with_walkers({sub:function(a,b){if(b[0]=="string"){var c=b[1];if(l(c))return["dot",r(a),c]}},"if":function(a,b,c){var a=r(a),b=r(b),c=r(c),
d=a[0]=="unary-prefix"&&a[1]=="!";h(b)&&(a=d?a[2]:["unary-prefix","!",a],b=c,c=null);h(c)?c=null:d&&(a=a[2],d=b,b=c,c=d);if(h(c)&&h(b))return["stat",a];d=["if",a,b,c];if(b[0]=="stat")c?c[0]=="stat"&&(d=e(d,["stat",f(a,b[1],c[1])])):d=e(d,["stat",f(a,b[1])]);else if(c&&b[0]==c[0]&&(b[0]=="return"||b[0]=="throw"))d=e(d,[b[0],f(a,b[1],c[1])]);else{var g;if(g=c)g=b,g[0]=="block"&&g[1]&&g[1].length>0&&(g=g[1][g[1].length-1]),g=g[0]=="return"||g[0]=="break"||g[0]=="continue"||g[0]=="throw"?true:void 0;
g&&(d=[["if",a,b]],c[0]=="block"?c[1]&&(d=d.concat(c[1])):d.push(c),d=["block",d])}return d},toplevel:function(a){return["toplevel",c(a.map(r))]},"switch":function(a,b){return["switch",r(a),c(b.map(r))]},"function":d,defun:d,block:function(a){if(a)return a=["block",c(a.map(r))],a!=null&&a[0]=="block"&&a[1]&&a[1].length==1&&(a=a[1][0]),a},binary:function(a,b,c){var b=r(b),c=r(c),d=["binary",a,b,c];if((b[0]=="string"||b[0]=="num")&&(c[0]=="string"||c[0]=="num")){var f=null;switch(a){case "+":f=b[1]+
c[1];break;case "*":f=b[1]*c[1];break;case "/":f=b[1]/c[1];break;case "-":f=b[1]-c[1]}f!=null&&(d=e(d,[typeof f=="string"?"string":"num",f]))}return d},conditional:function(a,b,c){if(a[0]=="unary-prefix"&&a[1]=="!")return["conditional",r(a[2]),r(c),r(b)]},seq:function(){if(arguments.length==1)return r(arguments[0])}},function(){return r(a)})};a.gen_code=i;a.ast_add_scope=v});
(function(){function g(a){return a instanceof Array||Array.isArray(a)||a&&a!==Object.prototype&&g(a.__proto__)}function a(a){return a instanceof RegExp||typeof a==="function"&&a.constructor.name==="RegExp"&&a.compile&&a.test&&a.exec&&(""+a).match(/^\/.*\/[gim]{0,3}$/)}var e=80,n=function(d,i,l,h){function n(d,h){switch(typeof d){case "undefined":return o("undefined","undefined");case "string":var l="'"+JSON.stringify(d).replace(/^"|"$/g,"").replace(/'/g,"\\'").replace(/\\"/g,'"')+"'";return o(l,"string");
case "number":return o(""+d,"number");case "boolean":return o(""+d,"boolean")}if(d===null)return o("null","null");var x=Object.keys(d),b=i?Object.getOwnPropertyNames(d):x;if(typeof d==="function"&&b.length===0)return a(d)?o(""+d,"regexp"):o("[Function"+(d.name?": "+d.name:"")+"]","special");if(d instanceof Date&&b.length===0)return o(d.toUTCString(),"date");var m,c;g(d)?(c="Array",l=["[","]"]):(c="Object",l=["{","}"]);typeof d==="function"?(m=d.name?": "+d.name:"",m=a(d)?" "+d:" [Function"+m+"]"):
m="";d instanceof Date&&(m=" "+d.toUTCString());if(b.length===0)return l[0]+m+l[1];if(h<0)return a(d)?o(""+d,"regexp"):o("[Object]","special");s.push(d);b=b.map(function(a){var b,e;d.__lookupGetter__&&(d.__lookupGetter__(a)?e=d.__lookupSetter__(a)?o("[Getter/Setter]","special"):o("[Getter]","special"):d.__lookupSetter__(a)&&(e=o("[Setter]","special")));x.indexOf(a)<0&&(b="["+a+"]");e||(s.indexOf(d[a])<0?(e=h===null?n(d[a]):n(d[a],h-1),e.indexOf("\n")>-1&&(e=g(d)?e.split("\n").map(function(a){return"  "+
a}).join("\n").substr(2):"\n"+e.split("\n").map(function(a){return"   "+a}).join("\n"))):e=o("[Circular]","special"));if(typeof b==="undefined"){if(c==="Array"&&a.match(/^\d+$/))return e;b=JSON.stringify(""+a);b.match(/^"([a-zA-Z_][a-zA-Z_0-9]*)"$/)?(b=b.substr(1,b.length-2),b=o(b,"name")):(b=b.replace(/'/g,"\\'").replace(/\\"/g,'"').replace(/(^"|"$)/g,"'"),b=o(b,"string"))}return b+": "+e});s.pop();var k=0;return b=b.reduce(function(a,b){k++;b.indexOf("\n")>=0&&k++;return a+b.length+1},0)>e?l[0]+
(m===""?"":m+"\n ")+" "+b.join(",\n  ")+" "+l[1]:l[0]+m+" "+b.join(", ")+" "+l[1]}var s=[],o=function(a,d){var e={bold:[1,22],italic:[3,23],underline:[4,24],inverse:[7,27],white:[37,39],grey:[90,39],black:[30,39],blue:[34,39],cyan:[36,39],green:[32,39],magenta:[35,39],red:[31,39],yellow:[33,39]},h={special:"cyan",number:"blue","boolean":"yellow",undefined:"grey","null":"bold",string:"green",date:"magenta",regexp:"red"}[d];return h?"\u001b["+e[h][0]+"m"+a+"\u001b["+e[h][1]+"m":a};h||(o=function(a){return a});
return n(d,typeof l==="undefined"?2:l)},w=/%[sdj%]/g,v=function(a){if(typeof a!=="string"){for(var e=[],g=0;g<arguments.length;g++)e.push(n(arguments[g]));return e.join(" ")}for(var g=1,h=arguments,i=h.length,e=String(a).replace(w,function(a){if(g>=i)return a;switch(a){case "%s":return String(h[g++]);case "%d":return Number(h[g++]);case "%j":return JSON.stringify(h[g++]);case "%%":return"%";default:return a}}),s=h[g];g<i;s=h[++g])e+=s===null||typeof s!=="object"?" "+s:" "+n(s);return e},i={};self.console=
{log:function(){Sandboss.out(v.apply(this,arguments)+"\n")},dir:function(a){Sandboss.out(n(a)+"\n")},time:function(a){i[a]=Date.now()},timeEnd:function(a){var e=Date.now()-i[a];self.console.log("%s: %dms",a,e)},read:function(a){Sandboss.input(a||function(){})},inspect:n}})();
