/*

 Copyright (c) 2011 Rasmus Andersson <http://rsms.me/>

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 Copyright (c) 2011 Rasmus Andersson <http://rsms.me/>

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.

 Copyright Joyent, Inc. and other Node contributors.

 Permission is hereby granted, free of charge, to any person obtaining a
 copy of this software and associated documentation files (the
 "Software"), to deal in the Software without restriction, including
 without limitation the rights to use, copy, modify, merge, publish,
 distribute, sublicense, and/or sell copies of the Software, and to permit
 persons to whom the Software is furnished to do so, subject to the
 following conditions:

 The above copyright notice and this permission notice shall be included
 in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
 NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
 USE OR OTHER DEALINGS IN THE SOFTWARE.

 Original at: https://github.com/joyent/node/blob/master/lib/util.js
*/
window.move||(window.move=function(){typeof window.global=="undefined"&&(window.global=window);var J=function(c){function h(a,b){for(var a=a.replace(/\/+$/g,""),f=(b?b+"/../"+a:a).split("/"),q=0,e=f.length;e>=0;e--){var c=f[e];c=="."?f.splice(e,1):c===".."?(f.splice(e,1),q++):q&&(f.splice(e,1),q--)}return f.join("/")}function a(b,c,j){var q=b;b.charAt(0)==="."&&(j&&j.indexOf(c+"/index")!==-1&&(c+="/index"),b=h(b,c));if(!a.modules.hasOwnProperty(b))throw Error("Module not found "+JSON.stringify(q));
var e=a.modules[b];if(e.exports===void 0)c=function(f){return a(f,b,e.uri)},f(c,"main",a.main),j=e.block,delete e.block,e.exports={},a.initFilter&&(j=a.initFilter(j)),j(c,e,e.exports);return e.exports}function b(b,c,j){typeof c=="function"&&(j=c,c=null);j={block:j};return f(j,"id",String(b)),c&&f(j,"uri",String(c)),a.modules[j.id]=j,j}var f;Object.defineProperty?f=function(a,b,f){Object.defineProperty(a,b,{value:f,writable:false,enumerable:true,configurable:false})}:f=function(a,b,f){a[b]=f};a.modules=
{};var u=b("");return delete u.block,u.exports=c||{},f(a,"main",u),a.define=b,a},y=J();y.define("runtime/runtime_inspect","runtime/runtime_inspect.js",function(c,h,a){function b(a){return a instanceof Array||Array.isArray(a)||a&&a!==Object.prototype&&b(a.prototype)}function f(a){return a instanceof RegExp||typeof a=="function"&&a.constructor.name==="RegExp"&&a.compile&&a.test&&a.exec&&(""+a).match(/^\/.*\/[gim]{0,3}$/)}function u(a){if(a instanceof Date)return true;if(typeof a!="object")return false;
var b=Date.prototype&&Object.getOwnPropertyNames(Date.prototype),a=a.__proto__&&Object.getOwnPropertyNames(a.__proto__);return JSON.stringify(a)===JSON.stringify(b)}a.inspect=function(c,h,j){function q(i,v){if(i&&typeof i.inspect=="function"&&i!==a&&i.inspect!==a.inspect&&(!i.constructor||i.constructor.prototype!==i))return i.inspect(v);switch(typeof i){case "undefined":return"undefined";case "string":return JSON.stringify(i).replace(/'/g,"\\'").replace(/\\"/g,'"').replace(/(^"|"$)/g,"'");case "number":return""+
i;case "boolean":return""+i}if(i===null)return"null";var F=Object.keys(i),x=h?Object.getOwnPropertyNames(i):F;if(typeof i=="function"&&x.length===0)return f(i)?""+i:"[Function"+(i.name?": "+i.name:"")+"]";if(u(i)&&x.length===0)return G(i.toUTCString(),"date");var g,A,d;b(i)?(A="Array",d=["[","]"]):(A="Object",d=["{","}"]);typeof i=="function"?(g=i.name?": "+i.name:"",g=f(i)?" "+i:" [Function"+g+"]"):g="";u(i)&&(g=" "+i.toUTCString());if(x.length===0)return d[0]+g+d[1];if(v<0)return f(i)?""+i:"[Object]";
e.push(i);x=x.map(function(a){var d,g;i.__lookupGetter__&&(i.__lookupGetter__(a)?i.__lookupSetter__(a)?g="[Getter/Setter]":g="[Getter]":i.__lookupSetter__(a)&&(g="[Setter]"));F.indexOf(a)<0&&(d="["+a+"]");g||(e.indexOf(i[a])<0?(v===null?g=q(i[a]):g=q(i[a],v-1),g.indexOf("\n")>-1&&(b(i)?g=g.split("\n").map(function(a){return"  "+a}).join("\n").substr(2):g="\n"+g.split("\n").map(function(a){return"   "+a}).join("\n"))):g="[Circular]");if(typeof d=="undefined"){if(A==="Array"&&a.match(/^\d+$/))return g;
d=JSON.stringify(""+a);d.match(/^"([a-zA-Z_][a-zA-Z_0-9]*)"$/)?d=d.substr(1,d.length-2):d=d.replace(/'/g,"\\'").replace(/\\"/g,'"').replace(/(^"|"$)/g,"'")}return d+": "+g});e.pop();var B=0;return x.reduce(function(a,d){return B++,d.indexOf("\n")>=0&&B++,a+d.length+1},0)>50?x=d[0]+(g===""?"":g+"\n ")+" "+x.join(",\n  ")+" "+d[1]:x=d[0]+g+" "+x.join(", ")+" "+d[1],x}var e=[],G=function(a){return a};return q(c,typeof j=="undefined"?2:j)}});y.define("runtime/es5_array","runtime/es5_array.js",function(){Array.isArray||
(Array.isArray=function(c){return c instanceof Array||Object.prototype.toString.call(c)==="[object Array]"});Array.prototype.indexOf||(Array.prototype.indexOf=function(c,h){var a,b=this.length;for(a=+h||0;a<b;++a)if(this[a]===c)return a;return-1});Array.prototype.lastIndexOf||(Array.prototype.lastIndexOf=function(c,h){for(var a=Math.min(this.length,+h||0);a!==-1;--a)if(this[a]===c)return a;return-1});Array.prototype.filter||(Array.prototype.filter=function(c,h){for(var a=[],b=0;b<this.length;b++)c.call(h,
this[b])&&a.push(this[b]);return a});Array.prototype.forEach||(Array.prototype.forEach=function(c,h){for(var a=this.length>>>0,b=0;b<a;++b)b in this&&c.call(h,this[b],b,this)});Array.prototype.every||(Array.prototype.every=function(c,h){for(var a=this.length>>>0,b=0;b<a;++b)if(b in this&&!c.call(h,this[b],b,this))return false;return true});Array.prototype.some||(Array.prototype.some=function(c,h){for(var a=this.length>>>0,b=0;b<a;++b)if(b in this&&c.call(h,this[b],b,this))return true;return false});
Array.prototype.map||(Array.prototype.map=function(c,h){for(var a=this.length>>>0,b=Array(a),f=0;f<a;++f)b[f]=c.call(h,this[f],f,this);return b});Array.prototype.reduce||(Array.prototype.reduce=function(c){var h=this.length>>>0,a=0,b;if(h===0&&arguments.length===1)throw new TypeError;if(arguments.length>=2)b=arguments[1];else{do{if(a in this){b=this[a++];break}if(++a>=h)throw new TypeError;}while(1)}for(;a<h;a++)a in this&&(b=c.call(null,b,this[a],a,this));return b});Array.prototype.unshift||(Array.prototype.unshift=
function(){this.reverse();for(var c=arguments.length;c--;)this.push(arguments[c]);return this.reverse(),this.length})});y.define("runtime/es5_string","runtime/es5_string.js",function(){String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^(?:\s|\u00A0)+/,"").replace(/(?:\s|\u00A0)+$/,"")});String.prototype.trimLeft||(String.prototype.trimLeft=function(){return this.replace(/^(?:\s|\u00A0)+/,"")});String.prototype.trimRight||(String.prototype.trimRight=function(){return this.replace(/(?:\s|\u00A0)+$/,
"")})});y.define("runtime/runtime_class","runtime/runtime_class.mv",function(c,h,a){(function(){var b,f,c,n,h;return b=__move.runtime,f=b._MoveKWArgsT,c=b.extend,n=b.__class,h=Object.prototype.constructor,a.__class=n=function(){var a,b,e,c,i;a=arguments[0];if(arguments.length===3){if(b=arguments[1],e=arguments[2],(c=typeof e)!=="object"&&c!=="function")throw TypeError("unexpected type "+c+" of second argument (expected object)");}else if(arguments.length===2)if(e=arguments[1],(c=typeof e)==="function")b=
e,e=void 0;else if(c!=="object")throw TypeError("unexpected type "+c+" of first argument (expected object or function)");return e&&e.__kw===f&&delete e.__kw,b&&(i=Object.create(b.prototype||null),e&&Object.keys(e).forEach(function(a){a!==null&&typeof a=="object"&&a.__kw===f&&(arguments.keywords=a,a=a.key);var b;if((b=e[a])!==void 0)return i[a]=b}),e=i),a.prototype=e||null,a.constructor=void 0,a},n.create=function(a,b){var e,f;return e=Object.create(a.prototype),(f=e.constructor)&&f!==h&&typeof f==
"function"?f.apply(e,b):typeof b[0]=="object"&&c(e,b[0]),e}})()});y.define("runtime/runtime_date","runtime/runtime_date.mv",function(){(function(){Date.distantFuture===void 0&&(Date.distantFuture=new Date(359753450957352));Date.distantPast===void 0&&(Date.distantPast=new Date(-621356868E5));Date.nowUTC||(Date.nowUTC=function(){return(new Date).getUTCTime()});Date.prototype.getUTCTime||(Date.prototype.getUTCTime=function(){return this.getTime()-this.getTimezoneOffset()});if(!Date.prototype.getUTCComponents)return Date.prototype.getUTCComponents=
function(){return[this.getUTCFullYear(),this.getUTCMonth()+1,this.getUTCDate(),this.getUTCHours(),this.getUTCMinutes(),this.getUTCSeconds(),this.getUTCMilliseconds()]}})()});y.define("runtime/symbols","runtime/symbols.js",function(c,h,a){a._MoveKWArgsT=function f(a){return a.__kw=f,a}});y.define("runtime/runtime_array","runtime/runtime_array.js",function(){typeof Array.prototype.unique!="function"&&(Array.prototype.unique=function(){var c=[],a,b,f=this.length;for(a=0;a<f;++a){for(b=a+1;b<f;++b)this[a]===
this[b]&&(b=++a);c.push(this[a])}return c});if(typeof Array.prototype._move_setSlice!="function"){var c=Array.prototype.splice;Array.prototype._move_setSlice=function(h,a,b){if(a!==void 0){if(typeof a!="number")throw new TypeError("Second argument must be a number");a-=h}else a=this.length;return c.apply(this,[h,a].concat(b))}}});y.define("runtime/runtime_string","runtime/runtime_string.js",function(){String.prototype.repeat||(String.prototype.repeat=function(c){for(s="";c--;)s+=this;return s});String.prototype.padLeft||
(String.prototype.padLeft=function(c,h){return this.length>=c?this:String(h||" ").repeat(c-this.length)+this});String.prototype.padRight||(String.prototype.padRight=function(c,h){return this.length>=c?this:this+String(h||" ").repeat(c-this.length)});String.prototype.editDistance||(String.prototype.editDistance=function h(a){var b,f=(b=this.split("")).length,u=(a=a.split("")).length,n,w,j,q;if(!f&&!u)return Math.max(f,u);h=[];for(n=f+1;n;h[--n]=[n]);for(n=u+1;h[0][--n]=n;);for(n=-1,j=b.length;++n<
j;)for(w=-1,q=a.length;++w<q;)h[(n*=1)+1][(w*=1)+1]=Math.min(h[n][w+1]+1,h[n+1][w]+1,h[n][w]+(b[n]!=a[w]));return h[f][u]});String.prototype.matchAll||(String.prototype.matchAll=function(h){h instanceof RegExp?h.global||(h=RegExp(h.source,"g")):h=RegExp(h,"g");for(var a,b=[];a=h.exec(this);)b.push(a);return b});String.prototype.forEachMatch||(String.prototype.forEachMatch=function(h,a,b){return b||(b=this),this.matchAll(h).forEach(a,b),b});typeof String.prototype.toLocaleLowerCase=="function"&&(String.prototype.toLowerCase=
String.prototype.toLocaleLowerCase);typeof String.prototype.toLocaleUpperCase=="function"&&(String.prototype.toUpperCase=String.prototype.toLocaleUpperCase)});y.define("runtime/runtime_move","runtime/runtime_move.mv",function(c,h,a){(function(){var b,f,h,n,w,j,q,e;b=__move.runtime;f=b._MoveKWArgsT;h=b.extend;n=b.JSON;f=global.__move.runtime._MoveKWArgsT;global.__move.runtime=a;w=typeof process!="undefined"&&!!(typeof process.versions=="object"&&process.versions.node||process.pid);w||(c("./es5_object"),
c("./es5_array"),c("./es5_date"),c("./es5_json"));c("./runtime_object");c("./runtime_string");c("./runtime_date");c("./runtime_array");Object.defineProperty?j=function(a,b,e){return a!==null&&typeof a=="object"&&a.__kw===f&&(arguments.keywords=a,e=a.value,b=a.name,a=a.obj),Object.defineProperty(a,b,{value:e,writable:false,enumerable:true,configurable:false})}:j=function(a,b,e){return a!==null&&typeof a=="object"&&a.__kw===f&&(arguments.keywords=a,e=a.value,b=a.name,a=a.obj),a[b]=e};j(a,"_MoveKWArgsT",
f);j(a,"Text",String);String.prototype.toText=String.prototype.toString;a.extend=h=function(a,b){a!==null&&typeof a=="object"&&a.__kw===f&&(arguments.keywords=a,b=a.body,a=a.object);var e;e=b===null?"undefined":typeof b;if(e==="object")Object.keys(b).forEach(function(g){g!==null&&typeof g=="object"&&g.__kw===f&&(arguments.keywords=g,g=g.key);var e;if((e=b[g])!==void 0&&e!==f)return a[g]=e});else if(e==="function")b.call(a);else if(e!=="undefined")throw new TypeError('"body" argument must be either an object or a function, not a '+
e);return a};a.create=function(a,b){return a!==null&&typeof a=="object"&&a.__kw===f&&(arguments.keywords=a,b=a.body,a=a.prototype),h(Object.create(a),b)};if(typeof Object.inspect!="function")try{if(Object.inspect=c("util").inspect,typeof Object.inspect!="function")throw 1;}catch(G){Object.inspect=c("./runtime_inspect").inspect}typeof console!="undefined"&&console.log?typeof window!="undefined"?(a.print=function F(){return F.consoleFun.apply(console,Array.prototype.slice.call(arguments))},a.print.consoleFun=
console.log):a.print=console.log:a.print=function(){};a.repeat=function(a,b,g){a!==null&&typeof a=="object"&&a.__kw===f&&(arguments.keywords=a,g=a.block,b=a.every,a=a.times);var e,d;if(typeof a=="function")for(;;){if(!a())break}else{if(typeof g!="function")return function(g){g!==null&&typeof g=="object"&&g.__kw===f&&(arguments.keywords=g,g=g.block);if(a!==void 0)for(e=0;e<a;++e){if(g(e)===true)break}else{if(b!==void 0)return d=Object.create({},{cancel:{value:function(){return clearInterval(this.id)}}}),
d.id=setInterval(function(){return g(d)},b),d;for(;;)if(!g())break}};if(a!==void 0)for(e=0;e<a;++e){if(g(e)===true)break}else{if(b!==void 0)return d=Object.create({},{cancel:{value:function(){return clearInterval(this.id)}}}),d.id=setInterval(function(){return g(d)},b),d;for(;;)if(!g())break}}};a.after=function(a,b){a!==null&&typeof a=="object"&&a.__kw===f&&(arguments.keywords=a,b=a.date,a=a.delay);if(a){if(typeof a!="number")throw new TypeError('"delay" argument must be a number');}else if(b){if(typeof b==
"string"||typeof b=="number"){if(b=new Date(b),isNaN(b.getTime()))throw Error('Invalid date/time passed for "date" argument');}else if(typeof b!="object"||!(b instanceof Date))throw new TypeError('"date" argument must be a Date object or a string');a=Math.max(0,b.getTime()-(new Date).getTime())}return function(b){return b!==null&&typeof b=="object"&&b.__kw===f&&(arguments.keywords=b,b=b.block),setTimeout(b,a)}};n=global.JSON;q=function(a,b){return a!==null&&typeof a=="object"&&a.__kw===f&&(arguments.keywords=
a,b=a.parse,a=a.build),a!==void 0||b===void 0?n.stringify(a):n.parse(b)};q.parse=n.parse;q.stringify=n.stringify;a.JSON=q;b=function(a,b){a!==null&&typeof a=="object"&&a.__kw===f&&(arguments.keywords=a,b=a.propertyName,a=a.target);var g,e;return g=a[b],e=function(a,b){a!==null&&typeof a=="object"&&a.__kw===f&&(arguments.keywords=a,b=a.call,a=a.event);var e;return b?g.call(this,a,b):(e=this,function(b){return b!==null&&typeof b=="object"&&b.__kw===f&&(arguments.keywords=b,b=b.block),g.call(e,a,b)})},
a[b]=e};try{e=c("events")}catch(i){}return e&&e.EventEmitter&&(b(e.EventEmitter.prototype,"addListener"),e.EventEmitter.prototype.on=e.EventEmitter.prototype.addListener),typeof process!="undefined"&&typeof process.on=="function"&&b(process,"on"),a.__class=c("./runtime_class").__class})()});y.define("runtime/es5_json","runtime/es5_json.js",function(){var c=global.JSON;if(typeof c!="object"||typeof c.stringify!="function"||typeof c.parse!="function")c=global.JSON={},function(){function h(a){return a<
10?"0"+a:a}function a(a){return u.lastIndex=0,u.test(a)?'"'+a.replace(u,function(a){var b=j[a];return typeof b=="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(e,f){var i,c,j,x,g=n,A,d=f[e];d&&typeof d=="object"&&typeof d.toJSON=="function"&&(d=d.toJSON(e));typeof q=="function"&&(d=q.call(f,e,d));switch(typeof d){case "string":return a(d);case "number":return isFinite(d)?String(d):"null";case "boolean":case "null":return String(d);case "object":if(!d)return"null";
n+=w;A=[];if(Object.prototype.toString.apply(d)==="[object Array]"){x=d.length;for(i=0;i<x;i+=1)A[i]=b(i,d)||"null";return j=A.length===0?"[]":n?"[\n"+n+A.join(",\n"+n)+"\n"+g+"]":"["+A.join(",")+"]",n=g,j}if(q&&typeof q=="object"){x=q.length;for(i=0;i<x;i+=1)c=q[i],typeof c=="string"&&(j=b(c,d),j&&A.push(a(c)+(n?": ":":")+j))}else for(c in d)Object.hasOwnProperty.call(d,c)&&(j=b(c,d),j&&A.push(a(c)+(n?": ":":")+j));return j=A.length===0?"{}":n?"{\n"+n+A.join(",\n"+n)+"\n"+g+"}":"{"+A.join(",")+"}",
n=g,j}}typeof Date.prototype.toJSON!="function"&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+h(this.getUTCMonth()+1)+"-"+h(this.getUTCDate())+"T"+h(this.getUTCHours())+":"+h(this.getUTCMinutes())+":"+h(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
u=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,n,w,j={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},q;typeof c.stringify!="function"&&(c.stringify=function(a,c,f){var j;n="";w="";if(typeof f=="number")for(j=0;j<f;j+=1)w+=" ";else typeof f=="string"&&(w=f);q=c;if(!c||typeof c=="function"||typeof c=="object"&&typeof c.length=="number")return b("",{"":a});throw Error("JSON.stringify");
});typeof c.parse!="function"&&(c.parse=function(a,b){function c(a,e){var g,f,d=a[e];if(d&&typeof d=="object")for(g in d)Object.hasOwnProperty.call(d,g)&&(f=c(d,g),f!==void 0?d[g]=f:delete d[g]);return b.call(a,e,d)}var j;a=String(a);f.lastIndex=0;f.test(a)&&(a=a.replace(f,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return j=eval("("+a+")"),typeof b=="function"?c({"":j},""):j;throw new SyntaxError("JSON.parse");})}()});y.define("runtime/es5_object","runtime/es5_object.js",function(){var c=Array.prototype.slice.call;Object.create||(Object.create=function(c,a){var b=function(){a&&Object.defineProperties&&Object.defineProperties(this,a)};return b.prototype=c,new b});Object.keys||(Object.keys=function a(b){var a=[],c;for(c in b)a.push(c);return a});Object.getOwnPropertyNames||
(Object.getOwnPropertyNames=function(){return Object.keys.apply(this,c(arguments))});Object.getOwnPropertyDescriptor||(Object.getOwnPropertyDescriptor=function(a,b){if(a.hasOwnProperty(b))return{configurable:true,enumerable:true,value:a[b],writable:true}});Object.prototype.hasOwnProperty||(Object.prototype.hasOwnProperty=function(a){return a in this});Object.defineProperty||Object.prototype.__defineGetter__&&Object.prototype.__defineSetter__&&(Object.defineProperty=function(a,b,c){if(typeof c=="object")if(c.hasOwnProperty("value")){if(!a.__lookupGetter__(b)&&
!a.__lookupSetter__(b)&&(a[b]=c.value),c.hasOwnProperty("get")||c.hasOwnProperty("set"))throw new TypeError("Object doesn't support this action");}else typeof c.get=="function"&&a.__defineGetter__(b,c.get),typeof c.set=="function"&&a.__defineSetter__(b,c.set);return a});!Object.defineProperties&&Object.defineProperty&&(Object.defineProperties=function(a,b){for(var c in b)Object.defineProperty(a,c,b[c])})});y.define("runtime","runtime/index.js",function(c){c("./runtime_string");global.__move||(global.__move=
{});global.__move.runtime={_MoveKWArgsT:c("./symbols")._MoveKWArgsT};global.__move.runtime=c("./runtime_move")});y.define("runtime/runtime_object","runtime/runtime_object.js",function(){if(!Object.prototype.forEach){var c;Object.defineProperty&&Object.defineProperty(Object.prototype,"forEach",{value:function(c,a){a!==null&&typeof a!="object"&&(a=this);var b=this;return Object.keys(this).forEach(function(f){c.call(a,f,b[f],b)}),this}})}});y.define("runtime/es5_date","runtime/es5_date.js",function(){Date.now||
(Date.now=function(){return(new Date).getTime()});Date.prototype.getTimezoneOffset||(Date.prototype.getTimezoneOffset=function(){if(this._timezoneOffsetStd===void 0){var c=new Date(this.getFullYear(),this.getMonth(),this.getDate(),0,0,0,0),h=c.toGMTString();this._timezoneOffsetStd=(new Date(h.substring(0,h.lastIndexOf(" ")-1))-c)/6E4}return this._timezoneOffsetStd})});y.define("compiler/parser","compiler/parser.js",function(c,h,a){function b(a){return a=a.charCodeAt(0),a>=48&&a<=57||a>=65&&a<=90||
a>=97&&a<=122}function f(a){return b(a)||a=="$"||a=="_"}function u(a){return a=a.charCodeAt(0),a>=48&&a<=57}function n(a){if(H.test(a))return parseInt(a.substr(2),16);if(Z.test(a))return parseInt(a.substr(1),8);if(N.test(a))return parseFloat(a)}function w(a,b,d,g){this.name="JS_Parse_Error";this.message=a;this.line=b;this.col=d;this.pos=g;try{({})()}catch(l){this.stack=this.message,l&&l.stack&&(this.stack+="\n"+l.stack.split(/[\r\n]/).slice(3).join("\n"))}}function j(a,b,d){return a.type==b&&(d==
null||a.value==d)}function q(a,l){function c(){return t.text.charAt(t.pos)}function e(a){var b=t.text.charAt(t.pos++);if(a&&!b)throw o;return b=="\n"?(t.newline_before=true,++t.line,t.col=0):++t.col,b}function i(a,b){var k=t.text.indexOf(a,t.pos);if(b&&k==-1)throw o;return k}function k(a,b,k){t.regex_allowed=a=="operator"&&!g($,b)||a==="keyword"&&g(d,b)||a==="punc"&&g(J,b);a={type:a,value:b,line:t.tokline,col:t.tokcol,pos:t.tokpos,nlb:t.newline_before};return k||(a.comments_before=t.comments_before,
t.comments_before=[]),t.newline_before=false,t.prev_token=a,a}function V(a){for(var b="",k=c(),d=0;k&&a(k,d++);)b+=e(),k=c();return b}function j(a){throw new w(a,t.tokline,t.tokcol,t.tokpos);}function q(a){var d=false,g=false,l=false,c=a==".",e=V(function(k,e){return k=="x"||k=="X"?l?false:l=true:l||k!="E"&&k!="e"?k=="-"?g||e==0&&!a?true:false:k=="+"?g:(g=false,k=="."?c?false:c=true:b(k)):d?false:d=g=true});a&&(e=a+e);var E=n(e);if(!isNaN(E))return k("num",E);j("Invalid syntax: "+e)}function x(){var a=
e(true);switch(a){case "n":return"\n";case "r":return"\r";case "t":return"\t";case "b":return"\u0008";case "v":return"\u000b";case "f":return"\u000c";case "0":return"\x00";case "x":return String.fromCharCode(X(2));case "u":return String.fromCharCode(X(4));default:return a}}function X(a){for(var b=0;a>0;--a){var k=parseInt(e(true),16);isNaN(k)&&j("Invalid hex-character pattern in string");b=b<<4|k}return b}function v(){return U("Unterminated string constant",function(){for(var a=e(),b="";;){var d=
e(true);if(d=="\\")d=x();else if(d==a)break;b+=d}return k("string",b)})}function h(){e();var a=i("\n"),b;return a==-1?(b=t.text.substr(t.pos),t.pos=t.text.length):(b=t.text.substring(t.pos,a),t.pos=a),k("comment1",b,true)}function F(){return e(),U("Unterminated multiline comment",function(){var a=i("*/",true),b=t.text.substring(t.pos,a),d=k("comment2",b,true);return t.pos=a+2,t.line+=b.split("\n").length-1,t.newline_before=b.indexOf("\n")>=0,d})}function aa(){return U("Unterminated regular expression",
function(){for(var a=false,b="",d,l=false;d=e(true);)if(a)b+="\\"+d,a=false;else if(d=="[")l=true,b+=d;else if(d=="]"&&l)l=false,b+=d;else{if(d=="/"&&!l)break;d=="\\"?a=true:b+=d}a=V(function(a){return g(T,a)});return k("regexp",[b,a])})}function H(a){function b(a){if(!c())return a;var k=a+c();return g(y,k)?(e(),b(k)):a}return k("operator",b(a||e()))}function E(){e();var a=t.regex_allowed;switch(c()){case "/":return t.comments_before.push(h()),t.regex_allowed=a,O();case "*":return t.comments_before.push(F()),
t.regex_allowed=a,O()}return t.regex_allowed?aa():H("/")}function R(){var a=V(f);return g(A,a)?g(y,a)?k("operator",a):g(B,a)?k("atom",a):k("keyword",a):k("name",a)}function U(a,b){try{return b()}catch(k){if(k===o)j(a);else throw k;}}function O(a){if(t.queued_tokens.length)return t.queued_tokens.shift();if(a)return aa();for(;g(D,c());)e();t.tokline=t.line;t.tokcol=t.col;t.tokpos=t.pos;a=c();if(!a)return k("eof");if(u(a))return q();if(a==='"'||a==="'")return v();if(g(L,a))return k("punc",e());if(a===
".")return e(),u(c())?q("."):k("punc",".");if(a==="/")return E();if(a==="#")return a=t.regex_allowed,t.comments_before.push(h()),t.regex_allowed=a,O();if(a==="^")return e(),a=c(),a==="{"&&(t.queued_tokens.push(k("punc","(")),t.queued_tokens.push(k("punc",")"))),k("keyword","function");if(g(z,a))return H();if(a==="@"){e();var a=R(),b=k("name","this");return b.nlb=a.nlb,a.nlb=false,t.queued_tokens.push(k("punc",".")),t.queued_tokens.push(a),b}if(f(a))return R();j("Unexpected character '"+a+"'")}typeof l!=
"object"&&(l={});var t={text:a.replace(/\r\n?|[\n\u2028\u2029]/g,"\n").replace(/^\uFEFF/,""),pos:0,tokpos:0,line:0,tokline:0,col:0,tokcol:0,newline_before:false,regex_allowed:false,comments_before:[],queued_tokens:[]};return O.context=function(a){return a&&(t=a),t},O}function e(a,b,d){this.name=a;this.start=b;this.end=d}function G(a){var b=F(arguments,1);return function(){return a.apply(this,b.concat(F(arguments)))}}function i(a){a instanceof Function&&(a=a());for(var b=1,d=arguments.length;--d>0;++b)arguments[b]();
return a}function v(a){for(var b={},d=0;d<a.length;++d)b[a[d]]=true;return b}function F(a,b){return Array.prototype.slice.call(a,b==null?0:b)}function x(a,b){for(var d=b.length;--d>=0;)if(b[d]===a)return true;return false}function g(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var A=v("break,case,catch,const,continue,default,delete,do,else,finally,for,function,if,in,instanceof,new,return,switch,throw,try,typeof,var,void,while,with,import,export,xor".split(","));a.KEYWORDS=A;c=v("abstract,boolean,byte,char,class,debugger,double,enum,extends,final,float,goto,implements,int,interface,long,native,package,private,protected,public,short,static,super,synchronized,throws,transient,volatile".split(","));
a.RESERVED_WORDS=c;var d=v("return,new,delete,throw,else,case".split(",")),B=v(["false","null","true","undefined"]),z=v("+-*&%=<>!?|~".split("")),H=/^0x[0-9a-f]+$/i,Z=/^0[0-7]+$/,N=/^\d*\.?\d*(?:e[+-]?\d*(?:\d\.?|\.?\d)\d*)?$/i,y=v("in,instanceof,typeof,new,void,delete,++,--,+,-,!,~,&,|,*,/,%,>>,<<,>>>,<,>,<=,>=,==,===,!=,!==,?,=,+=,-=,/=,*=,%=,>>=,<<=,>>>=,%=,|=,&=,&&,||,xor".split(",")),D=v(" \n\r\t".split("")),J=v("[{}(,.;:".split("")),L=v("[]{}(),;:".split("")),T=v("gmsiy".split(""));w.prototype.toString=
function(){return this.message+" (line: "+this.line+", col: "+this.col+", pos: "+this.pos+")\n\n"+this.stack};var o={},l=v("typeof,void,delete,--,++,!,~,-,+".split(",")),$=v(["--","++"]),X=function(a,b,d){for(;d<a.length;)b[a[d]]=a[d].substr(0,a[d].length-1),d++;return b}("+=,-=,/=,*=,%=,>>=,<<=,>>>=,|=,xor=,&=".split(","),{"=":true},0),ha=function(a,b){for(var d=0,g=1;d<a.length;++d,++g)for(var l=a[d],k=0;k<l.length;++k)b[l[k]]=g;return b}([["||"],["&&"],["|"],["xor"],["&"],["==","===","!=","!=="],
"<,>,<=,>=,in,instanceof".split(","),[">>","<<",">>>"],["+","-"],["*","/","%"]],{}),aa=v(["for","do","while","switch"]),V=v(["atom","num","string","regexp","name"]);e.prototype.toString=function(){return this.name};a.tokenizer=q;a.parse=function(a,b,d){function c(a,b){return j(p.token,a,b)}function A(){return p.peeked||(p.peeked=p.input())}function k(){return p.prev=p.token,p.peeked?(p.token=p.peeked,p.peeked2?(p.peeked=p.peeked2,p.peeked2=null):p.peeked=null):p.token=p.input(),p.token}function f(a,
b,d,c){var k=p.input.context();throw new w(a,b!=null?b:k.tokline,d!=null?d:k.tokcol,c!=null?c:k.tokpos);}function B(a){a==null&&(a=p.token);var b="Unexpected token: "+a.type+" "+JSON.stringify(a.value);f(b,a.line,a.col)}function v(a,b){if(c(a,b))return k();var d=p.token;f("Unexpected token: "+p.token.type+", expected "+a,d.line,d.col)}function z(a){return v("punc",a)}function h(a,b){var d;if(c("punc",a)||c("punc",b))d=k();else{var g=p.token;f("Unexpected token: "+p.token.type+", expected punc or punc",
g.line,g.col)}return d}function n(){return!b&&(p.token.nlb||c("eof")||c("punc","}"))}function H(){c("punc",";")?k():n()||B()}function o(){return F(arguments)}function u(){z("(");var a=K();return z(")"),a}function Z(){c("operator","/")&&(p.peeked2?(p.token=p.peeked2,p.peeked2=null):p.token=p.input(true),p.peeked=null);S.automaticVarDeclarations&&p.token.type==="keyword"&&p.token.value==="var"&&B();switch(p.token.type){case "num":case "string":case "regexp":case "operator":case "atom":return E();case "name":var a;
if(j(A(),"punc",":")){a=i(p.token.value,k,k);p.labels.push(a);var d=p.token,l=Q();a=(b&&!g(aa,l[0])&&B(d),p.labels.pop(),o("label",a,l))}else a=E();return a;case "punc":switch(p.token.value){case "{":return o("block",O());case "[":case "(":return E();case ";":return k(),o("block");default:B()}case "keyword":switch(i(p.token.value,k)){case "break":return R("break");case "continue":return R("continue");case "debugger":return H(),o("debugger");case "do":return a=Y(Q),v("keyword","while"),o("do",i(u,
H),a);case "for":d=false;(d=c("punc","("))&&k();(l=!S.automaticVarDeclarations&&c("keyword","var"))&&k();if(c("name")&&j(A(),"operator","in")){a=p.token.value;k();k();var e=K(false,d),d=(d&&z(")"),o("for-in",l,a,e,Y(Q)))}else l=c("punc",";")?null:l?N():K(),z(";"),e=c("punc",";")?null:K(),z(";"),d=(d?(a=c("punc",")")?null:K(),z(")")):a=c("punc","{")?null:K(false,false,true),o("for",l,e,a,Y(Q)));return d;case "function":return da(true);case "if":return a=u(),l=Q(),c("keyword","else")&&(k(),d=Q()),o("if",
a,l,d);case "return":return p.in_function==0&&f("'return' outside of function"),o("return",c("punc",";")?(k(),null):n()?null:i(K,H));case "switch":return o("switch",u(),ma());case "throw":return o("throw",i(K,H));case "try":a=O();if(c("keyword","catch"))k(),z("("),c("name")||f("Name expected"),d=p.token.value,k(),z(")"),e=[d,O()];return c("keyword","finally")&&(k(),l=O()),!e&&!l&&f("Missing catch/finally blocks"),o("try",a,e,l);case "var":return i(N,H);case "const":return i(y,H);case "while":return o("while",
u(),Y(Q));case "with":f("'with' statement not allowed");case "import":return i(D,H);case "export":return i(la,H);default:B()}}}function E(){return o("stat",i(K,H))}function R(a){var b=c("name")?p.token.value:null;return b!=null?(k(),x(b,p.labels)||f("Label "+b+" without matching loop or statement")):p.in_loop==0&&f(a+" not inside a loop or switch"),H(),o(a,b)}function U(a){var d=c("name")?i(p.token.value,k):null;a&&!d&&!p.in_function&&B();z("(");var l;l=true;for(var g,e=[],E={};!c("punc",")");){l?
l=false:z(",");if(!b&&c("punc",")"))break;g=P();e.push(g);c("punc",":")?(k(),E[g]=K(false)):E[g]=void 0}l=(k(),{names:e,values:E});g=o;a=a?"defun":"function";e=l.names;++p.in_function;E=p.in_loop;p.in_loop=0;var $=O(),E=(--p.in_function,p.in_loop=E,$);return g(a,d,e,E,l.values)}function O(){z("{");for(var a=[];!c("punc","}");)c("eof")&&B(),a.push(Q());return k(),a}function t(){for(var a=[];;){c("name")||B();var b=p.token.value;k();c("operator","=")?(k(),a.push([b,K(false)])):a.push([b]);if(!c("punc",
","))break;k()}return a}function N(){return o("var",t())}function y(){return o("const",t())}function D(){return o("import",t())}function la(){return o("export",t())}function J(a,d){if(c("operator","new")){k();var e=J(false),E;return c("punc","(")?(k(),E=L(")")):E=[],M(o("new",e,E),true)}if(c("operator")&&g(l,p.token.value))return fa("unary-prefix",i(p.token.value,k),J(a,d));if(c("punc")){switch(p.token.value){case "(":return k(),M(i(K(false,a,d),G(z,")")),a);case "[":return k(),M(o("array",L("]",
!b,true)),a,d);case "{":return k(),M(ga(),a,d)}B()}if(c("keyword","function"))return k(),M(da(false),a);if(g(V,p.token.type))return e=p.token.type=="regexp"?o("regexp",p.token.value[0],p.token.value[1]):o(p.token.type,p.token.value),M(i(e,k),a,d);B()}function L(a,b,d){for(var l=true,g=[];!c("punc",a);){l?l=false:z(",");if(b&&c("punc",a))break;c("punc",",")&&d?g.push(["atom","undefined"]):g.push(K(false))}return k(),g}function ga(){for(var a=true,d=[];!c("punc","}");){a?a=false:z(",");if(!b&&c("punc",
"}"))break;var l=p.token.type,g=P();l!="name"||g!="get"&&g!="set"||c("punc",":")?(z(":"),d.push([g,K(false)])):d.push([T(),da(false),g])}return k(),o("object",d)}function P(){switch(p.token.type){case "num":case "string":return i(p.token.value,k)}return T()}function T(){switch(p.token.type){case "name":case "operator":case "keyword":case "atom":return i(p.token.value,k);default:B()}}function M(a,b,d){if(c("punc","."))return k(),M(o("dot",a,T()),b,d);if(c("punc","[")){if(p.token.nlb)return a;k();var l=
null,e=null;c("punc",":")?k():l=i(K(false,b,d),G(h,"]",":"));p.prev.value===":"?(c("punc","]")?k():e=i(K(false,b,d),G(z,"]")),d=l,c("operator","=")?(k(),l=Q(),a=M(["call",["dot",a,"_move_setSlice"],[d||["num","0"],e||["name","undefined"],l[1]||["name","undefined"]]],b)):(d=[d||["num","0"]],a=(e&&d.push(e),M(["call",["dot",a,"slice"],d],b)))):a=M(o("sub",a,l),b,d);return a}if(b&&c("punc","("))return p.token.nlb?a:(k(),M(o("call",a,L(")")),b,d));if(b&&!d&&S.keywordArguments&&c("punc","{")){if(p.token.nlb)return a;
k();var E;c("operator","&")?(k(),E=K(false,b,d),z("}"),S.raw||(E=["call",["name","_MoveKWArgsT"],[E]])):(E=ga(),E[1].push(["__kw",["name","__Move_KWArgs__"]]));return M(o("call",a,[E]),b,d)}if(b&&c("operator")&&g($,p.token.value))return p.token.nlb?a:i(G(fa,"unary-postfix",p.token.value,a),k);if(b&&!c("eof")&&!c("punc")&&!c("operator")&&(p.token.type!=="keyword"||p.token.value==="function")){if(p.token.nlb)return a;E=[];for(var f=true,R;!c("punc",";");){if(f)f=false;else{if(!c("punc",",")){e=true;
break}R=A();if(R.type==="name"&&(!(l=p.peeked2?p.peeked2:(A(),p.peeked2=p.input()))||l.type==="punc"&&l.value===":")){e=true;break}if(R.type==="punc"&&R.value==="}"){e=true;break}k()}E.push(K(false,b,d))}return!e&&!c("punc",";")&&k(),p.token.nlb||c("punc",";")?o("call",a,E):M(o("call",a,E),true,d)}return a}function fa(a,b,d){return(b=="++"||b=="--")&&!ia(d)&&f("Invalid use of "+b+" operator"),o(a,b,d)}function ea(a,b,d,l){var g=c("operator")?p.token.value:null,e=g!=null?ha[g]:null;d===void 0&&(d=
true);return e!=null&&e>b?(k(),e=ea(J(d,l),e,d,l),ea(o("binary",g,a,e),b,d,l)):a}function ia(a){switch(a[0]){case "dot":case "sub":return true;case "name":return a[1]!="this"}}function ja(a,b){var d;var l=a;d=(l===void 0&&(l=true),ea(J(l,b),0,l,b));c("operator","?")&&(k(),l=K(false,a,b),d=(z(":"),o("conditional",d,l,K(false,a,b))));l=p.token.value;if(c("operator")&&g(X,l)){if(ia(d))return k(),o("assign",X[l],d,ja());f("Invalid assignment")}return d}function K(a,b,d){arguments.length==0&&(a=true);
var l=ja(b,d);return a&&c("punc",",")?(k(),o("seq",l,K())):l}function Y(a){try{return++p.in_loop,a()}finally{--p.in_loop}}var S={};typeof b=="object"&&(S=b,b=S.strictMode,d=S.embedTokens);var p={input:typeof a=="string"?q(a,S):a,token:null,prev:null,peeked:null,in_function:0,in_loop:0,labels:[]};p.token=k();var Q=d?function(){var a=p.token,b=Z.apply(this,arguments);return b[0]=b[0]instanceof e?b[0]:new e(b[0],a,p.prev),b}:Z,da=d?function(){var a=p.prev,b=U.apply(this,arguments);return b[0]=b[0]instanceof
e?b[0]:new e(b[0],a,p.prev),b}:U,ma=G(Y,function(){z("{");for(var a=[],b=null;!c("punc","}");)c("eof")&&B(),c("keyword","case")?(k(),b=[],a.push([K(),b]),z(":")):c("keyword","default")?(k(),z(":"),b=[],a.push([null,b])):(b||B(),b.push(Q()));return k(),a});return o("toplevel",function(a){for(;!c("eof");)a.push(Q());return a}([]))};a.slice=F;a.curry=G;a.member=x;a.array_to_hash=v;a.PRECEDENCE=ha;a.KEYWORDS_ATOM=B;a.RESERVED_WORDS=c;a.KEYWORDS=A;a.ATOMIC_START_TOKEN=V;a.OPERATORS=y;a.is_alphanumeric_char=
b;a.is_identifier_char=f});y.define("compiler/ast-mutators","compiler/ast-mutators.js",function(c,h,a){var b=c("./parser"),f=c("./process");a.add_implicit_returns=function(a){var b=f.ast_walker(),c=f.MAP,e;e=function v(a){if(!a)return a;var b=a[0];if(b==="stat")a[0]="return";else{if(b==="defun")return a[0]="function",["return",a];if(b==="if")for(b=2;b<a.length;++b)a[b]=v(a[b]);else b==="block"&&(b=a[1])&&b.length!==0&&(b[b.length-1]=v(b[b.length-1]))}return a};var h=function(a,f,h,g){return h.length&&
(h[h.length-1]=e(h[h.length-1])),[this[0],a,f.slice(),c(h,b.walk),g]};return b.with_walkers({defun:h,"function":h},function(){return b.walk(a)})};a.first_time_var_delc=function j(a,c){function h(a){g=new x(g);g.vars=[];a=g.body=a();if(g.vars.length){var b=a[0]==="toplevel"?a[1]:a,c=["var",n(g.vars,function(a){return[a]})];b.splice(0,0,c)}return g=g.parent,a}function i(a){return g.define(a)}function j(a,b,c,g){return[this[0],i(a),b,h(function(){return n(b,i),n(c,v.walk)}),g]}var v=f.ast_walker(),n=
f.MAP,x=f.Scope,g=null;return c&&(g=new x,g.names=b.array_to_hash(c)),h(function(){return v.with_walkers({defun:j,"function":j,"var":function(a){return[this[0],n(a,function(a){i(a[0]);var b=[a[0]];return a.length>1&&(b[1]=v.walk(a[1])),b})]},"import":function(a){n(a,function(a){i(a[0]);g.vars.push(a[0])})},"export":function(a){n(a,function(a){i(a[0]);g.vars.push(a[0])})},"const":function(a){n(a,function(a){i(a[0])})},assign:function(a,b,c){if(b[0]==="name"){var e=b[1];g.has(e)||(g.vars.push(e),i(e))}return[this[0],
a,v.walk(b),v.walk(c)]},"for-in":function(a,b,c,e){return a?[this[0],v.walk(a),v.walk(b),v.walk(c),v.walk(e)]:(g.has(b)||(g.vars.push(b),i(b)),[this[0],a,b,v.walk(c),v.walk(e)])}},function(){return v.walk(a)})})};var u=/^[_\$a-z][_\$\w\d]*$/i,n=function(a){var c;if(a[0]==="name")c=a[1];else if(a[0]==="dot")c=a[a.length-1];else if(a[0]==="sub")if(a=a[a.length-1],a[0]==="string"){if(c=a[1],b.KEYWORDS[c]||b.RESERVED_WORDS[c]||!u.test(c))c=void 0}else c=a;return c};a.named_lambda_assignments=function(a){var b=
f.ast_walker(),c=f.MAP;return b.with_walkers({"export":function(a){return[this[0],c(a,function(a){var c=[a[0]];return a.length>1&&(a[1]&&a[1][0]==="function"&&!a[1][1]&&(a[1][1]=a[0]),c[1]=b.walk(a[1])),c})]},assign:function(a,c,e){if(Array.isArray(e)&&e[0]==="function"&&!e[1]){var f=n(c);typeof f=="string"&&(e[1]=f)}return[this[0],a,b.walk(c),b.walk(e)]}},function(){return b.walk(a)})};a.enforce_strict_eq_ops=function(a){var b=f.ast_walker();return b.with_walkers({binary:function(a,c,f){return a===
"=="?a="===":a==="!="&&(a="!=="),[this[0],a,b.walk(c),b.walk(f)]}},function(){return b.walk(a)})};a.enable_keyword_arguments=function(a,b){var c=f.ast_walker(),h=f.MAP;typeof b!="object"&&(b={});var i=b.raw?"true":"_MoveKWArgsT";return c.with_walkers({"function":function(a,b,f,g){if(b.length){var A,d,B,j=["seq"],n=b[0],q=[null],u=["binary","&&",["binary","!==",["name",n],["name","null"]],["binary","&&",["binary","===",["unary-prefix","typeof",["name",n]],["string","object"]],["binary","===",["dot",
["name",n],"__kw"],["name",i]]]];j.push(["assign",true,["dot",["name","arguments"],"keywords"],["name",n]]);for(A=b.length;--A!==-1;)d=b[A],B=g&&g[d],j.push(["assign",true,["name",d],["dot",["name",n],d]]),B&&q.push(["if",["binary","===",["name",d],["name","undefined"]],["stat",["assign",true,["name",d],B]]]);q[0]=["stat",["binary","&&",u,j]];f=q.concat(f)}return[this[0],a,b,h(f,c.walk),g]},call:function(a,b){if(b.length===1&&b[0][0]==="object"){for(var f,g=b[0][1],A=[],d=g.length;--d!==-1;)f=g[d],
f[0]==="__kw"&&f[1]&&f[1][1]==="__Move_KWArgs__"&&A.push(d);if(A.length){for(;A.length>1;)delete g[A.pop()];g[A.pop()]=["__kw",["name",i]]}}return[this[0],c.walk(a),h(b,c.walk)]}},function(){return c.walk(a)})};a.enable_class_rt_function=function(a,b){var c=f.ast_walker(),h=f.MAP,i;return c.with_walkers({name:function(a){return a==="class"&&(a="__class"),[this[0],a]},assign:function(a,b,f){var g=n(b);return i=typeof g=="string"?g:void 0,r=[this[0],a,c.walk(b),c.walk(f)],i=void 0,r},call:function(a,
f){var j;if(a[0]==="name"&&a[1]==="class"&&i){j=i||"__UntitledClass";f.unshift(["assign",true,["name",j],["function",j,[],[["return",["call",["dot",["name","__class"],"create"],[["name",j],["name","arguments"]]]]]]]);a:{j=f[1];var g,A;if(j&&j[0]==="object"){j=j[1];for(A=0;A<j.length;A++)if(g=j[A],g[0]==="__kw"&&g[1][0]==="name"&&(b.raw&&g[1][1]==="true"||!b.raw&&g[1][1]==="_MoveKWArgsT")){j.splice(A,1);break a}}}}return[this[0],c.walk(a),h(f,c.walk)]}},function(){return c.walk(a)})}});y.define("compiler/preprocessors/ehtml",
"compiler/preprocessors/ehtml.mv",function(c,h,a){(function(){var b,c;b=__move.runtime;c=b._MoveKWArgsT;__move.EHTML=function n(a){a!==null&&typeof a=="object"&&a.__kw===c&&(arguments.keywords=a,a=a.html);var b;return n.spawnerElement||(n.spawnerElement=document.createElement("div")),n.spawnerElement.innerHTML=a,b=n.spawnerElement.firstChild,b.toString=function(){return a},b};a.process=function(a,b){a!==null&&typeof a=="object"&&a.__kw===c&&(arguments.keywords=a,b=a.options,a=a.src);var j,h,e,G,i;
return j=0,h=function(b){b!==null&&typeof b=="object"&&b.__kw===c&&(arguments.keywords=b,b=b.endch);var e,i;for(e=null;i=a[j++];){if(i===b&&e!=="\\")break;e=i}},e=function F(){var b,g,e,d,i,h,q;for(b=0,g=j-1,e="<",d=[];e==="<";){for(i=F=null;(e=a[j++])&&e!==">";)i===null&&(i=e),e==="{"&&F!=="\\"&&(d.push([true,g,j-1]),g=j,h=G(true),d.push([false,h]),g=j),F=e;if(i==="/"){if(--b,b<0)throw Error("EHTML: Premature termination");}else F!=="/"&&++b;if(!e||b===0)break;for(;(e=a[j++])&&e!=="<";)e==="{"&&
F!=="\\"&&(d.push([true,g,j-1]),g=j,h=G(true),d.push([false,h]),g=j),F=e}return d.push([true,g,j]),q="",d.forEach(function(b){b!==null&&typeof b=="object"&&b.__kw===c&&(arguments.keywords=b,b=b.range);var d;return b[0]?(d=a.substring(b[1],b[2]),d=d.replace(/\n/g,"\\n"),d=d.replace(/\t/g,"\\t"),d=d.replace(/'/g,"\\'")):d="'+("+b[1]+")+'",q+=d}),q="EHTML('"+q+"')",q},G=function x(b){b!==null&&typeof b=="object"&&b.__kw===c&&(arguments.keywords=b,b=b.isDeep);var i,d,B,z,H,w;for(i="",d=0,x=null,B=1;z=
a[j++];){H=false;switch(z){case " ":case "\n":case "\r":case "\t":i+=z;break;case '"':w=j;h('"');i+=a.substring(w-1,j);break;case "'":w=j;h("'");i+=a.substring(w-1,j);break;case "<":d===1?(d=0,i+=z):i+=e();break;default:i+=z,H=true}if(H){if(b&&x!=="\\")if(z==="{")++B;else if(z==="}"&&--B===0){i=i.substr(0,i.length-1);break}z.match(/[a-z0-9_\)\}]/i)?d=1:d=0}x=z}return i},i="EHTML = __move.EHTML\n"+G(),i}})()});y.define("compiler/squeeze-more","compiler/squeeze-more.js",function(c,h,a){c("./parser");
var b=c("./process");a.ast_squeeze_more=function(a){var c=b.ast_walker(),h=c.walk;return c.with_walkers({call:function(a,b){if(a[0]=="dot"&&a[2]=="toString"&&b.length==0)return["binary","+",a[1],["string",""]]}},function(){return h(a)})}});y.define("compiler/process","compiler/process.js",function(c,h,a){function b(){function a(d){return[this[0],o(d,function(a){var d=[a[0]];return a.length>1&&(d[1]=b(a[1])),d})]}function b(a){if(!a)return null;try{e.push(a);var l=a[0],g=d[l];if(g){var f=g.apply(a,
a.slice(1));if(f!=null)return f}return g=c[l],g.apply(a,a.slice(1))}finally{e.pop()}}var c={string:function(a){return[this[0],a]},num:function(a){return[this[0],a]},name:function(a){return[this[0],a]},toplevel:function(a){return[this[0],o(a,b)]},block:function(a){var d=[this[0]];return a!=null&&d.push(o(a,b)),d},"var":a,"const":a,"import":a,"export":a,"try":function(a,d,c){return[this[0],o(a,b),d!=null?[d[0],o(d[1],b)]:null,c!=null?o(c,b):null]},"throw":function(a){return[this[0],b(a)]},"new":function(a,
d){return[this[0],b(a),o(d,b)]},"switch":function(a,d){return[this[0],b(a),o(d,function(a){return[a[0]?b(a[0]):null,o(a[1],b)]})]},"break":function(a){return[this[0],a]},"continue":function(a){return[this[0],a]},conditional:function(a,d,c){return[this[0],b(a),b(d),b(c)]},assign:function(a,d,c){return[this[0],a,b(d),b(c)]},dot:function(a){return[this[0],b(a)].concat(H(arguments,1))},call:function(a,d){return[this[0],b(a),o(d,b)]},"function":function(a,d,c,l){return[this[0],a,d.slice(),o(c,b),l]},defun:function(a,
d,c,l){return[this[0],a,d.slice(),o(c,b),l]},"if":function(a,d,c){return[this[0],b(a),b(d),b(c)]},"for":function(a,d,c,l){return[this[0],b(a),b(d),b(c),b(l)]},"for-in":function(a,d,c,l){return a?[this[0],b(a),b(d),b(c),b(l)]:[this[0],a,d,b(c),b(l)]},"while":function(a,d){return[this[0],b(a),b(d)]},"do":function(a,d){return[this[0],b(a),b(d)]},"return":function(a){return[this[0],b(a)]},binary:function(a,d,c){return[this[0],a,b(d),b(c)]},"unary-prefix":function(a,d){return[this[0],a,b(d)]},"unary-postfix":function(a,
d){return[this[0],a,b(d)]},sub:function(a,d){return[this[0],b(a),b(d)]},object:function(a){return[this[0],o(a,function(a){return a.length==2?[a[0],b(a[1])]:[a[0],b(a[1]),a[2]]})]},regexp:function(a,b){return[this[0],a,b]},array:function(a){return[this[0],o(a,b)]},stat:function(a){return[this[0],b(a)]},seq:function(){return[this[0]].concat(o(H(arguments),b))},label:function(a,d){return[this[0],a,b(d)]},"with":function(a,d){return[this[0],b(a),b(d)]},atom:function(a){return[this[0],a]}},d={},e=[];return{walk:b,
with_walkers:function(a,b){var c={},l;for(l in a)B(a,l)&&(c[l]=d[l],d[l]=a[l]);var e=b();for(l in c)B(c,l)&&(c[l]?d[l]=c[l]:delete d[l]);return e},parent:function(){return e[e.length-2]},stack:function(){return e}}}function f(a){this.names={};this.mangled={};this.rev_mangled={};this.cname=-1;this.refs={};this.uses_with=false;this.uses_eval=false;this.parent=a;this.children=[];a?(this.level=a.level+1,a.children.push(this)):this.level=0}function u(a){function d(a){g=new f(g);a=g.body=a();return a.scope=
g,g=g.parent,a}function c(a){return g.define(a)}function e(a,b,l,g){return[this[0],c(a),b,d(function(){return o(b,c),o(l,h)}),g]}var g=null,i=b(),h=i.walk,j=[];return d(function(){function b(a,d){for(d=a.children.length;--d>=0;)b(a.children[d]);for(d in a.refs)if(B(a.refs,d))for(var c=a.has(d),l=a;l;l=l.parent)if(l.refs[d]=c,l===c)break}var d=i.with_walkers({"function":e,defun:e,"with":function(){for(var a=g;a;a=a.parent)a.uses_with=true},"var":function(a){o(a,function(a){c(a[0])})},"const":function(a){o(a,
function(a){c(a[0])})},"try":function(a,b,d){if(b!=null)return[this[0],o(a,h),[c(b[0]),o(b[1],h)],d!=null?o(d,h):null]},name:function(a){a=="eval"&&j.push(g);g.refs[a]=true},"for-in":function(a,b){a?c(b):g.refs[b]=true}},function(){return h(a)});return o(j,function(a){if(!a.has("eval"))for(;a;)a.uses_eval=true,a=a.parent}),b(g),d})}function n(a,b){return x(a).length>x(b[0]=="stat"?b[1]:b).length?b:a}function w(a){return a[0]=="block"&&a[1]&&a[1].length>0?a[1][a[1].length-1]:a}function j(a){if(a&&
(a=w(a),a[0]=="return"||a[0]=="break"||a[0]=="continue"||a[0]=="throw"))return true}function q(a){return a[0]=="unary-prefix"&&y(a[1],["!","delete"])||a[0]=="binary"&&y(a[1],"in,instanceof,==,!=,===,!==,<,<=,>=,>".split(","))||a[0]=="binary"&&y(a[1],["&&","||"])&&q(a[2])&&q(a[3])||a[0]=="conditional"&&q(a[2])&&q(a[3])||a[0]=="assign"&&a[1]===true&&q(a[3])||a[0]=="seq"&&q(a[a.length-1])}function e(a,b,d){return a[0]=="unary-prefix"&&a[1]=="!"?d?["conditional",a[2],d,b]:["binary","||",a[2],b]:d?["conditional",
a,b,d]:["binary","&&",a,b]}function G(a){return!a||a[0]=="block"&&(!a[1]||a[1].length==0)}function i(a){return a[0]=="string"||a[0]=="unary-prefix"&&a[1]=="typeof"||a[0]=="binary"&&a[1]=="+"&&(i(a[2])||i(a[3]))}function v(a){G(a)||L("Dropping unreachable code: "+x(a,true))}function F(a){var b=0,d=0;return a=a.replace(/[\\\b\f\n\r\t\x22\x27]/g,function(a){switch(a){case "\\":return"\\\\";case "\u0008":return"\\b";case "\u000c":return"\\f";case "\n":return"\\n";case "\r":return"\\r";case "\t":return"\\t";
case '"':return++b,'"';case "'":return++d,"'"}return a}),b>d?"'"+a.replace(/\x27/g,"\\'")+"'":'"'+a.replace(/\x22/g,'\\"')+'"'}function x(a,c){function e(a){return a==null&&(a=""),c&&(a=g(" ",c.indent_start+x*c.indent_level)+a),a}function f(a,b){b==null&&(b=1);x+=b;try{return a.apply(null,H(arguments,1))}finally{x-=b}}function i(a){if(c)return a.join(" ");for(var b=[],d=0;d<a.length;++d){var e=a[d+1];b.push(a[d]);e&&(/[a-z0-9_\x24]$/i.test(a[d].toString())&&/^[a-z0-9_\x24]/i.test(e.toString())||/[\+\-]$/.test(a[d].toString())&&
/^[\+\-]/.test(e.toString()))&&b.push(" ")}return b.join("")}function h(a){return a.join(","+J)}function j(a){for(var b=C(a),d=1;d<arguments.length;++d){var c=arguments[d];if(c instanceof Function&&c(a)||a[0]==c)return"("+b+")"}return b}function n(a){if(a.length==1)return a[0];if(a.length==2){var b=a[1];return a=a[0],a.length<=b.length?a:b}return n([a[0],n(a.slice(1))])}function q(a){if(a[0]=="function")for(var b=H(P),d=b.pop(),c=b.pop();c;){if(c[0]=="stat")return true;if(c[0]=="seq"&&c[1]===d||c[0]==
"call"&&c[1]===d||c[0]=="binary"&&c[2]===d)d=c,c=b.pop();else return false}return!B(T,a[0])}function v(a){var b=a.toString(10),d=[b.replace(/^0\./,".")],c;return Math.floor(a)===a?(d.push("0x"+a.toString(16).toLowerCase(),"0"+a.toString(8)),(c=/^(.*?)(0+)$/.exec(a))&&d.push(c[1]+"e"+c[2].length)):(c=/^0?\.(0+)(.*)$/.exec(a))&&d.push(c[2]+"e-"+(c[1].length+c[2].length),b.substr(b.indexOf("."))),n(d)}function u(a,b,d,e,g){e=g||"function";return a?e+=" "+k(a):c&&(e+=" "),e+="("+h(o(b,k))+")",i([e,W(d)])}
function k(a){return a.toString()}function ba(a){for(var b=[],d=a.length-1,g=0;g<=d;++g){var k=a[g],l=C(k);l!=";"&&(!c&&g==d&&(k[0]=="while"&&G(k[2])||y(k[0],["for","for-in"])&&G(k[4])||k[0]=="if"&&G(k[2])&&!k[3]||k[0]=="if"&&k[3]&&G(k[3])?l=l.replace(/;*\s*$/,";"):l=l.replace(/;+\s*$/,"")),b.push(l))}return o(b,e)}function ka(a){var b=a.length;return b==0?"{}":"{"+w+o(a,function(a,d){var g=a[1].length>0,k=f(function(){return e(a[0]?i(["case",C(a[0])+":"]):"default:")},0.5)+(g?w+f(function(){return ba(a[1]).join(w)}):
"");return!c&&g&&d<b-1&&(k+=";"),k}).join(w)+w+e("}")}function W(a){return a?a.length==0?"{}":"{"+w+f(function(){return ba(a).join(w)})+w+e("}"):";"}function ca(a){var b=a[0],a=a[1];return a!=null&&(b=i([b,"=",C(a)])),b}function C(a){if(a){var b=a[0],d=L[b];if(!d)throw Error("Can't find generator for \""+b+'"');P.push(a);a=d.apply(b,a.slice(1));return P.pop(),a}}c&&(c=A(c,{indent_start:0,indent_level:4,quote_keys:false,space_colon:false}));var x=0,w=c?"\n":"",J=c?" ":"",L={string:F,num:v,name:k,toplevel:function(a){return ba(a).join(w+
w)},block:W,"var":function(a){return"var "+h(o(a,ca))+";"},"const":function(a){return"const "+h(o(a,ca))+";"},"import":function(a){return h(o(a,function(a){var b=a[0];return a.length>1&&(a=a[1][1]),b+" = require("+C(["string",b])+")"}))+";"},"export":function(a){return h(o(a,function(b){return"exports."+b[0]+" = "+h(o(a,ca))}))+";"},"try":function(a,b,d){a=["try",W(a)];return b&&a.push("catch","("+b[0]+")",W(b[1])),d&&a.push("finally",W(d)),i(a)},"throw":function(a){return i(["throw",C(a)])+";"},
"new":function(a,d){return d=d.length>0?"("+h(o(d,C))+")":"",i(["new",j(a,"seq","binary","conditional","assign",function(a){var d=b(),c={};try{d.with_walkers({call:function(){throw c;},"function":function(){return this}},function(){d.walk(a)})}catch(e){if(e===c)return true;throw e;}})+d])},"switch":function(a,b){return i(["switch","("+C(a)+")",ka(b)])},"break":function(a){var b="break";return a!=null&&(b+=" "+k(a)),b+";"},"continue":function(a){var b="continue";return a!=null&&(b+=" "+k(a)),b+";"},
conditional:function(a,b,d){return i([j(a,"assign","seq","conditional"),"?",j(b,"seq"),":",j(d,"seq")])},assign:function(a,b,d){return a&&a!==true?a+="=":a="=",d||console.log("assign:",a,b,d),i([C(b),a,j(d,"seq")])},dot:function(a){var b=C(a),d=1;for(a[0]=="num"?b+=".":q(a)&&(b="("+b+")");d<arguments.length;)b+="."+k(arguments[d++]);return b},call:function(a,b){var d=C(a);return q(a)&&(d="("+d+")"),d+"("+h(o(b,function(a){return j(a,"seq")}))+")"},"function":u,defun:u,"if":function(a,b,d){a="("+C(a)+
")";if(d)a:if(b[0]=="do")b=C(["block",[b]]);else{for(var c=b;;){var e=c[0];if(e=="if"){if(!c[3]){b=C(["block",[b]]);break a}c=c[3]}else if(e=="while"||e=="do")c=c[2];else if(e=="for"||e=="for-in")c=c[4];else break}b=C(b)}else b=C(b);b=["if",a,b];return d&&b.push("else",C(d)),i(b)},"for":function(a,b,d,c){var e=["for"];a=(a!=null?C(a):"").replace(/;*\s*$/,";"+J);b=(b!=null?C(b):"").replace(/;*\s*$/,";"+J);d=(d!=null?C(d):"").replace(/;*\s*$/,"");a=a+b+d;return a=="; ; "&&(a=";;"),e.push("("+a+")",
C(c)),i(e)},"for-in":function(a,b,d,c){var e=i(["for","("]);return a&&(e+="var "),e+=i([k(b)+" in "+C(d)+")",C(c)]),e},"while":function(a,b){return i(["while","("+C(a)+")",C(b)])},"do":function(a,b){return i(["do",C(b),"while","("+C(a)+")"])+";"},"return":function(a){var b=["return"];return a!=null&&b.push(C(a)),i(b)+";"},binary:function(a,b,d){var c=C(b),e=C(d);if(y(b[0],["assign","conditional","seq"])||b[0]=="binary"&&N[a]>N[b[1]])c="("+c+")";if(y(d[0],["assign","conditional","seq"])||d[0]=="binary"&&
N[a]>=N[d[1]]&&(d[1]!=a||!y(a,["&&","||","*"])))e="("+e+")";return a==="xor"&&(a="^"),i([c,a,e])},"unary-prefix":function(a,b){var d=C(b);return b[0]=="num"||b[0]=="unary-prefix"&&!B(D,a+b[1])||!q(b)||(d="("+d+")"),a+(z.is_alphanumeric_char(a.charAt(0))?" ":"")+d},"unary-postfix":function(a,b){var d=C(b);return b[0]=="num"||b[0]=="unary-postfix"&&!B(D,a+b[1])||!q(b)||(d="("+d+")"),d+a},sub:function(a,b){var d=C(a);return q(a)&&(d="("+d+")"),d+"["+C(b)+"]"},object:function(a){return a.length==0?"{}":
"{"+w+f(function(){return o(a,function(a){if(a.length==3)return e(u(a[0],a[1][2],a[1][3],a[1][4],a[2]));var b=a[0],a=C(a[1]);return c&&c.quote_keys?b=F(b):(typeof b=="number"||!c&&+b+""==b)&&parseFloat(b)>=0?b=v(+b):d(b)||(b=F(b)),e(i(c&&c.space_colon?[b,":",a]:[b+":",a]))}).join(","+w)})+w+e("}")},regexp:function(a,b){return"/"+a+"/"+b},array:function(a){return a.length==0?"[]":i(["[",h(o(a,function(a){return!c&&a[0]=="atom"&&a[1]=="undefined"?"":j(a,"seq")})),"]"])},stat:function(a){return C(a).replace(/;*\s*$/,
";")},seq:function(){return h(o(H(arguments),C))},label:function(a,b){return i([k(a),":",C(b)])},"with":function(a,b){return i(["with","("+C(a)+")",C(b)])},atom:function(a){return k(a)}},P=[];return C(a)}function g(a,b){if(b<=0)return"";if(b==1)return a;var d=g(a,b>>1);return d+=d,b&1&&(d+=a),d}function A(a,b){var d={};a===true&&(a={});for(var c in b)B(b,c)&&(d[c]=a&&B(a,c)?a[c]:b[c]);return d}function d(a){return/^[a-z_$][a-z0-9_$]*$/i.test(a)&&a!="this"&&!B(z.KEYWORDS_ATOM,a)&&!B(z.RESERVED_WORDS,
a)&&!B(z.KEYWORDS,a)}function B(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var z=c("./parser"),H=z.slice,y=z.member,N=z.PRECEDENCE,D=z.OPERATORS,J=function(){return function(a){var b="";do b="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$_".charAt(a%54)+b,a=Math.floor(a/54);while(a>0);return b}}();f.prototype={has:function(a){for(var b=this;b;b=b.parent)if(B(b.names,a))return b},has_mangled:function(a){for(var b=this;b;b=b.parent)if(B(b.rev_mangled,a))return b},toJSON:function(){return{names:this.names,
uses_eval:this.uses_eval,uses_with:this.uses_with}},next_mangled:function(){for(;;){var a=J(++this.cname),b;b=this.has_mangled(a);if(!(b&&this.refs[b.rev_mangled[a]]===b)&&(b=this.has(a),(!b||!(b!==this&&this.refs[a]===b&&!b.has_mangled(a)))&&!(B(this.refs,a)&&this.refs[a]==null)&&d(a)))return a}},get_mangled:function(a,b){if(this.uses_eval||this.uses_with)return a;var d=this.has(a);if(!d)return a;if(B(d.mangled,a))return d.mangled[a];if(!b)return a;var c=d.next_mangled();return d.rev_mangled[c]=
a,d.mangled[a]=c},define:function(a){if(a!=null)return this.names[a]=a}};var L=function(){},P=function(){function a(d){switch(d[0]){case "string":case "num":return d[1];case "name":case "atom":switch(d[1]){case "true":return true;case "false":return false}break;case "unary-prefix":switch(d[1]){case "!":return!a(d[2]);case "typeof":return typeof a(d[2]);case "~":return~a(d[2]);case "-":return-a(d[2]);case "+":return+a(d[2])}break;case "binary":var c=d[2],e=d[3];switch(d[1]){case "&&":return a(c)&&
a(e);case "||":return a(c)||a(e);case "|":return a(c)|a(e);case "&":return a(c)&a(e);case "^":return a(c)^a(e);case "+":return a(c)+a(e);case "*":return a(c)*a(e);case "/":return a(c)/a(e);case "-":return a(c)-a(e);case "<<":return a(c)<<a(e);case ">>":return a(c)>>a(e);case ">>>":return a(c)>>>a(e);case "==":return a(c)==a(e);case "===":return a(c)===a(e);case "!=":return a(c)!=a(e);case "!==":return a(c)!==a(e);case "<":return a(c)<a(e);case "<=":return a(c)<=a(e);case ">":return a(c)>a(e);case ">=":return a(c)>=
a(e);case "in":return a(c)in a(e);case "instanceof":return a(c)instanceof a(e)}}throw b;}var b={};return function(d,c,e){try{var g=a(d),f;switch(typeof g){case "string":f=["string",g];break;case "number":f=["num",g];break;case "boolean":f=["name",String(g)];break;default:throw Error("Can't handle constant of type: "+typeof g);}return c.call(d,f,g)}catch(h){if(h===b)return d[0]=="binary"&&(d[1]=="==="||d[1]=="!==")&&(i(d[2])&&i(d[3])||q(d[2])&&q(d[3]))&&(d[1]=d[1].substr(0,2)),e?e.call(d,d):null;throw h;
}}}(),T=z.array_to_hash("name,array,string,dot,sub,call,regexp".split(",")),o;(function(){function a(b){this.v=b}o=function(b,d,c){for(var e=[],g=0;g<b.length;++g){var f=d.call(c,b[g],g);f instanceof a?e.unshift(f.v):e.push(f)}return e};o.at_top=function(b){return new a(b)}})();a.ast_walker=b;a.ast_mangle=function(a,d){function c(a,b){return!d&&!j.parent?a:j.get_mangled(a,b)}function e(a,b,d,f){return a&&(a=c(a)),d=g(d.scope,function(){return b=o(b,function(a){return c(a)}),o(d,h)}),[this[0],a,b,
d,f]}function g(a,b){var d=j;j=a;for(var e in a.names)B(a.names,e)&&c(e,true);e=b();return e.scope=a,j=d,e}function f(a){return[this[0],o(a,function(a){return[c(a[0]),h(a[1])]})]}var i=b(),h=i.walk,j;return i.with_walkers({"function":e,defun:function(){var a=e.apply(this,arguments);switch(i.parent()[0]){case "toplevel":case "function":case "defun":return o.at_top(a)}return a},"var":f,"const":f,name:function(a){return[this[0],c(a)]},"try":function(a,b,d){return[this[0],o(a,h),b!=null?[c(b[0]),o(b[1],
h)]:null,d!=null?o(d,h):null]},toplevel:function(a){var b=this;return g(b.scope,function(){return[b[0],o(a,h)]})},"for-in":function(a,b,d,e){return[this[0],a,c(b),h(d),h(e)]}},function(){return h(u(a))})};a.ast_squeeze=function(a,c){function g(a){var b=["unary-prefix","!",a];switch(a[0]){case "unary-prefix":return a[1]=="!"&&q(a[2])?a[2]:b;case "seq":return a=H(a),a[a.length-1]=g(a[a.length-1]),a;case "conditional":return n(b,["conditional",a[1],g(a[2]),g(a[3])]);case "binary":var d=a[1],e=a[2],a=
a[3];if(!c.keep_comps)switch(d){case "<=":return["binary",">",e,a];case "<":return["binary",">=",e,a];case ">=":return["binary","<",e,a];case ">":return["binary","<=",e,a]}switch(d){case "==":return["binary","!=",e,a];case "!=":return["binary","==",e,a];case "===":return["binary","!==",e,a];case "!==":return["binary","===",e,a];case "&&":return n(b,["binary","||",g(e),g(a)]);case "||":return n(b,["binary","&&",g(e),g(a)])}}return b}function f(a,b){var d=D;D=a;var c=b();return c.scope=a,D=d,c}function i(a,
b,d,c){return[this[0],a,b,f(d.scope,function(){return h(o(d,I),"lambda")}),c]}function h(a,b){return a=a.reduce(function(a,b){return b&&(b[0]=="block"?b[1]&&a.push.apply(a,b[1]):a.push(b)),a},[]),a=function(b,d){return a.forEach(function(a){d&&(a[0]=="var"&&d[0]=="var"||a[0]=="const"&&d[0]=="const")?d[1]=d[1].concat(a[1]):(b.push(a),d=a)}),b}([]),c.dead_code&&(a=function(b,d){return a.forEach(function(a){d?y(a[0],["function","defun","var","const"])?b.push(a):c.no_warnings||v(a):(b.push(a),y(a[0],
["return","throw","break","continue"])&&(d=true))}),b}([])),c.make_seqs&&(a=function(b,d){return a.forEach(function(a){d&&d[0]=="stat"&&a[0]=="stat"?d[1]=["seq",d[1],a[1]]:(b.push(a),d=a)}),b}([])),b=="lambda"&&(a=function(b,d,c){for(;b<a.length;){c=a[b++];if(c[0]=="if"&&!c[3]){if(c[2][0]=="return"&&c[2][1]==null){d.push(z(g(c[1]),["block",a.slice(b)]));break}var e=w(c[2]);if(e[0]=="return"&&e[1]==null){d.push(z(c[1],["block",c[2][1].slice(0,-1)],["block",a.slice(b)]));break}}d.push(c)}return d}(0,
[])),a}function z(a,b,d){return P(a,function(a,c){return c?(v(d),b):(v(b),d)},function(){var c;c=a;var f=b,i=d;c=I(c);f=I(f);i=I(i);if(G(f))c=g(c),f=i,i=null;else if(G(i))i=null;else{var h=x(c),l=g(c);x(l).length<h.length&&(f=i,i=f,c=l)}G(i)&&G(f)?c=["stat",c]:(h=["if",c,f,i],c=(f[0]=="if"&&G(f[3])&&G(i)?h=n(h,I(["if",["binary","&&",c,f[1]],f[2]])):f[0]=="stat"?i?i[0]=="stat"&&(h=n(h,["stat",e(c,f[1],i[1])])):h=n(h,["stat",e(c,f[1])]):i&&f[0]==i[0]&&(f[0]=="return"||f[0]=="throw")&&f[1]&&i[1]?h=n(h,
[f[0],e(c,f[1],i[1])]):i&&j(f)?(h=[["if",c,f]],i[0]=="block"?i[1]&&(h=h.concat(i[1])):h.push(i),h=I(["block",h])):f&&j(i)&&(h=[["if",g(c),i]],f[0]=="block"?f[1]&&(h=h.concat(f[1])):h.push(f),h=I(["block",h])),h));return c})}function F(a,b){return P(a,function(a,d){return d?["for",null,null,null,I(b)]:(v(b),["block"])})}var c=A(c,{make_seqs:true,dead_code:true,keep_comps:true,no_warnings:false}),N=b(),I=N.walk,D;return N.with_walkers({sub:function(a,b){if(b[0]=="string"){var c=b[1];if(d(c))return["dot",
I(a),c]}},"if":z,toplevel:function(a){return["toplevel",f(this.scope,function(){return h(o(a,I))})]},"switch":function(a,b){var d=b.length-1;return["switch",I(a),o(b,function(a,b){var c=h(o(a[1],I));if(b==d&&c.length>0){var e=c[c.length-1];e[0]=="break"&&!e[1]&&c.pop()}return[a[0]?I(a[0]):null,c]})]},"function":function(){var a=i.apply(this,arguments);return a[1]&&!B(D.refs,a[1])&&(a[1]=null),a},defun:i,block:function(a){if(a)return a=["block",h(o(a,I))],a!=null&&a[0]=="block"&&a[1]&&(a[1].length==
1?a=a[1][0]:a[1].length==0&&(a=["block"])),a},binary:function(a,b,d){return P(["binary",a,I(b),I(d)],function(a){return n(I(a),this)},function(){return this})},conditional:function(a,b,d){return e(I(a),I(b),I(d))},"try":function(a,b,d){return["try",h(o(a,I)),b!=null?[b[0],h(o(b[1],I))]:null,d!=null?h(o(d,I)):null]},"unary-prefix":function(a,b){var b=I(b),d=["unary-prefix",a,b];return a=="!"&&(d=n(d,g(b))),P(d,function(a){return I(a)},function(){return d})},name:function(a){switch(a){case "true":return["unary-prefix",
"!",["num",0]];case "false":return["unary-prefix","!",["num",1]]}},"new":function(a,b){if(a[0]=="name"&&a[1]=="Array"&&!D.has("Array"))return b.length!=1?["array",b]:["call",["name","Array"],b]},call:function(a,b){if(a[0]=="name"&&a[1]=="Array"&&b.length!=1&&!D.has("Array"))return["array",b]},"while":F,"do":F},function(){return I(u(a))})};a.gen_code=x;a.ast_add_scope=u;a.ast_squeeze_more=c("./squeeze-more").ast_squeeze_more;a.set_logger=function(a){L=a};a.make_string=F;a.split_lines=function(a,b){var d=
[0];return z.parse(function(){function c(){var a=e.apply(this,arguments);if(!(f&&f.type=="keyword")&&a.pos-g>b)switch(a.type){case "keyword":case "atom":case "name":case "punc":g=a.pos,d.push(g)}return f=a,a}var e=z.tokenizer(a),g=0,f;return c.context=function(){return e.context.apply(this,arguments)},c}()),d.map(function(b,c){return a.substring(b,d[c+1]||a.length)}).join("\n")};a.MAP=o;a.Scope=f});y.define("compiler","compiler/index.js",function(c,h,a){var b;try{b=c("fs")}catch(f){}try{c("http")}catch(u){}var n=
c("./parser"),w=c("./process"),j=c("./ast-mutators");c("../runtime/runtime_string");a.preprocessors={};a.defaultCompilationOptions={source:null,filename:"?",globals:[],ignorePragmas:false,implicitReturns:true,automaticVarDeclarations:true,namedLambdas:true,strictEqualityOperators:true,keywordArguments:true,mangleNames:false,optimizationLevel:0,runtimeClassCreation:true,moduleStub:false,codegen:true,outputFormatting:{indent_level:2,beautify:true},detailedOutput:false,strict:true,raw:false,wrapSource:true,
includeRuntime:true};var q=function(a,b,d){a.name="SyntaxError";var b=b.split(/[\r\n]/),c=a.line+1,b=b.slice(c<3?0:c-3,c);if(c>3){var e="";if(m=b[0].match(/^\s+/))for(c=0;c<m[0].length;++c)e+=" ";b[0]=e+"...\n"+b[0]}b=b.join("\n");e="";for(c=0;c<a.col;++c)e+=" ";return a.diagnostic=a.name+": "+a.message+" ("+d.filename+":"+a.line+":"+a.col+")\n"+b+"\n"+e+"\u2b06",a.stack&&(a.stack=a.diagnostic+"\n"+a.stack.split(/[\r\n]/).slice(1).join("\n")),a};a.compile=function(b,e){var d=Object.create(a.defaultCompilationOptions);
typeof b=="object"&&(e=b,b=e.source);b||(b="");if(typeof e=="object")for(var f in e)d[f]=e[f];d.strictMode=false;d.embedTokens=false;if(!d.ignorePragmas){var i=/^\s*(?:true|y.*|on|1)\s*$/i;b.forEachMatch(/^#\s*pragma\s+(\w+)\s(.+)/gm,function(a){var b=a[1],a=a[2];switch(b){case "strict":d.strict=i.test(a);break;case "enable":if(a==="ehtml")Array.isArray(d.preprocess)?d.preprocess.indexOf("ehtml")===-1&&d.preprocess.push("ehtml"):d.preprocess=["ehtml"];else throw Error('Unknown value "'+a+'" for "enable" pragma');
break;case "disable":if(a==="ehtml")Array.isArray(d.preprocess)&&(a=d.preprocess.indexOf("ehtml"))!==-1&&d.preprocess.splice(a,1);else throw Error('Unknown value "'+a+'" for "disable" pragma');break;default:throw Error('Unknown pragma directive "'+b+'"');}})}if(d.preprocess){if(!Array.isArray(d.preprocess))throw Error('"preprocess" option must have an array value');d.preprocess.forEach(function(e){var f,i;typeof e=="function"||typeof e=="object"?f=e:(f=a.preprocessors[e])||(f=c("./preprocessors/"+
e));if(!f)throw Error("preprocessor "+e+" not found");typeof f.process=="function"?i=f.process:i=f;b=i.call(f,b,d)})}b+="\n";d.includeRuntime&&(b=x(b,d));d.wrapSource&&(b="(function() {"+b+"})()");try{var h=n.parse(b,d)}catch(v){throw v.name==="JS_Parse_Error"&&(v=q(v,b,d)),v;}d.implicitReturns&&(h=j.add_implicit_returns(h,d));d.automaticVarDeclarations&&(f="global,process,require,window,__filename,__dirname,module".split(","),Array.isArray(d.globals)&&d.globals.length&&(f=f.concat(d.globals)),d.moduleStub&&
f.push("exports"),h=j.first_time_var_delc(h,f,d));d.namedLambdas&&(h=j.named_lambda_assignments(h,d));d.strictEqualityOperators&&(h=j.enforce_strict_eq_ops(h,d));d.keywordArguments&&(h=j.enable_keyword_arguments(h,d));d.runtimeClassCreation&&(h=j.enable_class_rt_function(h,d));d.mangleNames&&(h=w.ast_mangle(h));d.optimizationLevel&&(h=w.ast_squeeze(h));typeof d.optimizationLevel=="number"&&d.optimizationLevel>1&&(h=w.ast_squeeze_more(h));if(!d.codegen)return h;f=w.gen_code(h,d.outputFormatting);return d.wrapSource&&
d.moduleStub&&(f=f.replace(/^\(function\s*\(\)\s*\{/,"function(require,module,exports){").replace(/\)\(\);$/,"")),d.strict&&(d.wrapSource?f=f.replace(/\(function\s*\(\)\s*\{/,'(function(){"use strict";'):f='"use strict";'+f),a.debug&&typeof console!="undefined"&&console.log((e.filename||"<move code>")+" -> \n"+f),d.detailedOutput?{ast:h,code:f}:f};a.compileFileSync=function(c,e){if(!b)throw Error("File system access is not supported");return typeof e=="object"&&!e.filename?e.filename=c:e={filename:c},
a.compile(b.readFileSync(c,"utf8"),e)};a.eval=function(b,c){if(typeof b=="object")c=b;else{if(!c||typeof c!="object")c={};c.source=b}var d=a.compile(c);return e(d,c)};var e,y;try{y=c("vm").runInThisContext,e=function(a,b){var d={require:global.require};global.require=c;var e=y(a.code!==void 0?a.code:a,String(b&&b.filename||"<input>"));return Object.keys(d).forEach(function(a){var b=d[a];b!==void 0?global[a]=b:delete global[a]}),e}}catch(i){e=function(a,b){var d=global.require;global.require=__move.require;
var c=global.eval(a.code!==void 0?a.code:a,String(b&&b.filename||"<input>"));return d!==void 0?global.require=d:delete global.require,c}}typeof window!="undefined"&&window&&(a.compileURL=function(a,b,d){var c=F(arguments,[["url"],["options"],["callback"]]);typeof c.options=="function"&&(c.callback=c.options,c.options={});var e=window.ActiveXObject?new window.ActiveXObject("Microsoft.XMLHTTP"):new XMLHttpRequest;return e.open("GET",c.url,true),"overrideMimeType"in e&&e.overrideMimeType("text/plain"),
e.onreadystatechange=function(){if(e.readyState===4){var b,d,f=a.indexOf("://")!==-1?a.match(/^http/):document.location.protocol.match(/^http/);if(f&&String(e.status).charAt(0)==="2"||!f&&e.status===0)try{b=D.compile(e.responseText,c.options)}catch(i){d=i}else e.status&&e.statusText?(d=Error("HTTP request error: "+e.status+" "+e.statusText),d.httpStatus=e.status):d=Error("Unspecified HTTP request error");if(typeof c.callback=="function")c.callback(d,b);else if(d)throw d;}},e.send(null)});var v=c("../runtime/symbols")._MoveKWArgsT,
F=function(a,b){var d=a[0],c,e,f;if(typeof d=="object"&&d.__kw===v)for(f=0;f<b.length;++f)c=b[f][0],d[c]===void 0&&(e=b[f][1])!==void 0&&(d[c]=e);else{d={};for(f=0;f<b.length;++f)c=b[f][0],e=a[f],e===void 0&&(e=b[f][1]),e!==void 0&&(d[c]=e)}return d},x=function(a,b){var d="";b.automaticVarDeclarations||(d+="var ");d+="Move = __move.runtime";var c=Object.keys(global.__move.runtime);return c.length&&(d+=", "+c.map(function(a){return a+" = Move."+a}).join(",")),d+"; "+a};c.extensions&&(c.extensions[".mv"]=
c.extensions[".move"]=function(b,c){return content=a.compileFileSync(c),b._compile(content,c)});Object.keys(a).forEach(function(b){global.__move[b]=a[b]});c("../runtime")});y.define("","index.js",function(c,h,a,b,f){global.__move=a;a.version=function(){return a.version._v===void 0&&(a.version._v=JSON.parse(c("fs").readFileSync(f+"/../package.json","utf8")).version),a.version._v};c("./compiler")});y("");var D=global.__move;D.version=function(){return"0.4.3"};D.require=J();D.executeScript=function(c,
h){if(c)throw c;Function(h)()};D.compileModule=function(c,h,a,b,f){var u;return typeof f=="object"?f=Object.create(f):f={},f.filename=a||"<"+(h||"main")+">",f.moduleStub=true,u=D.compile(c,f),h?u=L(u,null,a,h):u="("+u+")(__move.require, {exports:{}}, {});\n",b=b||b===void 0,b?D.executeScript(null,u,a):u};D.scriptCompilationOptions={preprocess:["ehtml"]};var L=function(c,h,a,b){return b||(b=h.replace(/\.[^\.]+$/,"")),"__move.require.define("+JSON.stringify(b)+","+JSON.stringify(a||h)+","+c+");\n"};
D.runBrowserScripts=function(c,h){var a,b,f,u,n,w=Object.create(D.scriptCompilationOptions),j=0,q=[],e=0,y=function(){if(--e===0){for(var a=0,b=q.length;a<b;++a)D.executeScript.apply(D,q[a]);typeof h=="function"&&h(null,q)}};u=(c||document).getElementsByTagName("script");++e;for(b=0,f=u.length;b<f;++b)a=u[b],a&&a.type==="text/move"&&function(a,b){++e;var c=Object.create(w);if(b.src)c.filename=b.src,c.moduleStub=true,D.compileURL(c.filename,c,function(e,d){d=L(d,b.getAttribute("src"),c.filename);q[a]=
[e,d,b];y()});else{try{var f=b.getAttribute("module");n=D.compileModule(b.innerHTML,f,null,false,c);q[a]=[null,n,b]}catch(g){q[a]=[g,null,b]}y()}}(j++,a);return y(),null};J=function(){D.runBrowserScripts()};return window.addEventListener?window.addEventListener("DOMContentLoaded",J,false):window.attachEvent("onload",J),D}());
(function(){function J(a){return a instanceof Array||Array.isArray(a)||a&&a!==Object.prototype&&J(a.__proto__)}function y(a){return a instanceof RegExp||typeof a==="function"&&a.constructor.name==="RegExp"&&a.compile&&a.test&&a.exec&&(""+a).match(/^\/.*\/[gim]{0,3}$/)}var D=80,L=function(a,c,h,n){function w(a,b){switch(typeof a){case "undefined":return q("undefined","undefined");case "string":var h="'"+JSON.stringify(a).replace(/^"|"$/g,"").replace(/'/g,"\\'").replace(/\\"/g,'"')+"'";return q(h,"string");
case "number":return q(""+a,"number");case "boolean":return q(""+a,"boolean")}if(a===null)return q("null","null");var n=Object.keys(a),u=c?Object.getOwnPropertyNames(a):n;if(typeof a==="function"&&u.length===0)return y(a)?q(""+a,"regexp"):q("[Function"+(a.name?": "+a.name:"")+"]","special");if(a instanceof Date&&u.length===0)return q(a.toUTCString(),"date");var x,g;J(a)?(g="Array",h=["[","]"]):(g="Object",h=["{","}"]);typeof a==="function"?(x=a.name?": "+a.name:"",x=y(a)?" "+a:" [Function"+x+"]"):
x="";a instanceof Date&&(x=" "+a.toUTCString());if(u.length===0)return h[0]+x+h[1];if(b<0)return y(a)?q(""+a,"regexp"):q("[Object]","special");j.push(a);u=u.map(function(d){var c,f;a.__lookupGetter__&&(a.__lookupGetter__(d)?f=a.__lookupSetter__(d)?q("[Getter/Setter]","special"):q("[Getter]","special"):a.__lookupSetter__(d)&&(f=q("[Setter]","special")));n.indexOf(d)<0&&(c="["+d+"]");f||(j.indexOf(a[d])<0?(f=b===null?w(a[d]):w(a[d],b-1),f.indexOf("\n")>-1&&(f=J(a)?f.split("\n").map(function(a){return"  "+
a}).join("\n").substr(2):"\n"+f.split("\n").map(function(a){return"   "+a}).join("\n"))):f=q("[Circular]","special"));if(typeof c==="undefined"){if(g==="Array"&&d.match(/^\d+$/))return f;c=JSON.stringify(""+d);c.match(/^"([a-zA-Z_][a-zA-Z_0-9]*)"$/)?(c=c.substr(1,c.length-2),c=q(c,"name")):(c=c.replace(/'/g,"\\'").replace(/\\"/g,'"').replace(/(^"|"$)/g,"'"),c=q(c,"string"))}return c+": "+f});j.pop();var A=0;return u=u.reduce(function(a,b){A++;b.indexOf("\n")>=0&&A++;return a+b.length+1},0)>D?h[0]+
(x===""?"":x+"\n ")+" "+u.join(",\n  ")+" "+h[1]:h[0]+x+" "+u.join(", ")+" "+h[1]}var j=[],q=function(a,b){var c={bold:[1,22],italic:[3,23],underline:[4,24],inverse:[7,27],white:[37,39],grey:[90,39],black:[30,39],blue:[34,39],cyan:[36,39],green:[32,39],magenta:[35,39],red:[31,39],yellow:[33,39]},f={special:"cyan",number:"blue","boolean":"yellow",undefined:"grey","null":"bold",string:"green",date:"magenta",regexp:"red"}[b];return f?"\u001b["+c[f][0]+"m"+a+"\u001b["+c[f][1]+"m":a};n||(q=function(a){return a});
return w(a,typeof h==="undefined"?2:h)},c=/%[sdj%]/g,h=function(a){if(typeof a!=="string"){for(var f=[],h=0;h<arguments.length;h++)f.push(L(arguments[h]));return f.join(" ")}for(var h=1,n=arguments,w=n.length,f=String(a).replace(c,function(a){if(h>=w)return a;switch(a){case "%s":return String(n[h++]);case "%d":return Number(n[h++]);case "%j":return JSON.stringify(n[h++]);case "%%":return"%";default:return a}}),j=n[h];h<w;j=n[++h])f+=j===null||typeof j!=="object"?" "+j:" "+L(j);return f},a={};self.console=
{log:function(){Sandboss.out(h.apply(this,arguments)+"\n")},dir:function(a){Sandboss.out(L(a)+"\n")},time:function(b){a[b]=Date.now()},timeEnd:function(b){var c=Date.now()-a[b];self.console.log("%s: %dms",b,c)},read:function(a){Sandboss.input(a||function(){})},inspect:L}})();
