/*

 Copyright 2010 Steve Hanov

 This file is part of qb.js

 qb.js is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 qb.js is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with qb.js.  If not, see <http://www.gnu.org/licenses/>.
*/
var QBasic={};
(function(){function f(a){this.mchar=a}function b(a,d){this.ranges=a;this.include=d}function c(a){this.mchar=a;this.next=[];this.id=h++;this.lastList=0;this.accept=void 0}function a(){this.nfaStates=[];this.next={};this.accepts=[];this.id=h++}function d(a,d){this.start=a;this.end=d}var h=0;QBasic.Locus=function(a,d){this.line=a;this.position=d};QBasic.Locus.prototype={toString:function(){return""+(this.line+1)+":"+(this.position+1)}};f.prototype={match:function(a){return this.mchar==-3?a>="0"&&a<=
"9":this.mchar==-4?a!=-1&&a!=-2&&a!="\n":a==this.mchar},toString:function(){return this.mchar==-3?"\\d":this.mchar}};b.prototype={match:function(a){for(var d=0;d<this.ranges.length;d++){var b=this.ranges[d];if(a>=b[0]&&a<=b[1])return this.include}return!this.include},toString:function(){var a="[";this.include||(a+="^");for(var d=0;d<this.ranges.length;d++)a+=this.ranges[d][0]==this.ranges[d][1]?this.ranges[d][0]:this.ranges[d][0]+"-"+this.ranges[d][1];return a+"]"}};c.prototype.toString=function(){var a=
"\nState ["+this.id+"] ch="+this.mchar+"\n";this.accept!==void 0&&(a+="    Accept "+this.accept+"\n");for(var d=0;d<this.next.length;d++)a+="    ch="+this.next[d].mchar+" goto ["+this.next[d].id+"]\n";return a};d.prototype.toString=function(){for(var a={},d=[this.start],b="";d.length>0;){var c=d.pop();if(!a[c]){a[c]=1;for(var h=0;h<c.next.length;h++)d.push(c.next[h]);b+=c.toString()}}return b};QBasic.Token=function(a,d,b,c){this.id=a;this.text=d;this.locus=new QBasic.Locus(b,c)};QBasic.Token.prototype=
{toString:function(){return"Token("+this.text+")"}};QBasic.Tokenizer=function(){this.root=new c(null);this.expr=null;this.index=0;this.listId=1;this.dfaCache={};this.text="";this.lineNumbers=[];this.EOF_TOKEN={};this.IGNORE_TOKEN={};this.finished=true};QBasic.Tokenizer.prototype={addToken:function(a,d){this.expr=d;this.index=0;var b=this.parseAlternation();this.root.next.push(b.start);b.end.accept=a},ignore:function(a){this.addToken(this.IGNORE_TOKEN,a)},eof:function(){return this.index==this.expr.length},
matchChar:function(a){return this.expr[this.index]==a?(this.index++,true):false},peek:function(a){return this.expr[this.index]==a},parseChar:function(){return this.matchChar("\\")?this.matchChar("n")?"\n":this.matchChar("r")?"\r":this.matchChar("t")?"\t":this.matchChar("d")?-3:this.expr[this.index++]:this.matchChar(".")?-4:this.matchChar("$")?-2:this.matchChar("^")?-1:this.expr[this.index++]},parseRange:function(){for(var a=true,h=[];!this.eof()&&!this.peek("]");){this.matchChar("^")&&(a=false);var j=
this.parseChar(),f=j;this.matchChar("-")&&(f=this.parseChar());j==-3&&(j="0",f="9");h.push([j,f])}a=new c(new b(h,a));return new d(a,a)},parseBasic:function(){var a;if(this.matchChar("(")){if(a=this.parseAlternation(),!this.matchChar(")"))throw"Expected ')'";}else if(this.matchChar("[")){if(a=this.parseRange(),!this.matchChar("]"))throw"Expected ']'";}else a=new c(new f(this.parseChar())),a=new d(a,a);return a},parseKleene:function(){var a=this.parseBasic(),d;if(this.matchChar("+"))d=new c(null),
a.end.next.push(d),d.next.push(a.start),a.end=d;else if(this.matchChar("*"))d=new c(null),d.next.push(a.start),a.end.next.push(d),a.start=d,a.end=d;else if(this.matchChar("?")){d=new c(null);var b=new c(null);d.next.push(a.start);d.next.push(b);a.end.next.push(b);a.start=d;a.end=b}return a},parseConcat:function(){for(var a=new c(null),b=a;;){if(this.peek("|")||this.peek(")")||this.eof())break;var h=this.parseKleene();b.next.push(h.start);b=h.end}return new d(a,b)},parseAlternation:function(){var a=
new c(null),b=new c(null);do{var h=this.parseConcat();a.next.push(h.start);h.end.next.push(b)}while(this.matchChar("|"));return new d(a,b)},addState:function(a,d,b){if(b.lastList!=this.listId&&(b.accept!==void 0&&d.push(b.accept),b.lastList=this.listId,a.push(b),b.mchar===null))for(var c=0;c<b.next.length;c++)this.addState(a,d,b.next[c])},nextState:function(d,b){var c=[],h=[],f;this.listId++;for(f=0;f<d.nfaStates.length;f++){var e=d.nfaStates[f];e.mchar!==null&&(e.mchar.match(b)?this.addState(c,h,
e.next[0]):(b==-2||b==-1)&&this.addState(c,h,e))}c.sort(function(a,d){return a.id-d.id});e="";for(f=0;f<c.length;f++)e+=c[f].id+".";if(this.dfaCache[e]===void 0)d=new a,d.nfaStates=c,d.accepts=h,this.dfaCache[e]=d;return this.dfaCache[e]},setText:function(a){this.text=a;this.lineNumbers.length=0;this.lineNumbers.push(0);this.finished=false;for(a=0;a<this.text.length;a++)this.text[a]=="\n"&&this.lineNumbers.push(a+1)},getLine:function(a){return this.text.substr(this.lineNumbers[a],this.lineNumbers[a+
1]-this.lineNumbers[a])},nextTokenInternal:function(d,b){var c=0,h,f=null;if(this.rootDfa===void 0)this.rootDfa=new a,this.addState(this.rootDfa.nfaStates,this.rootDfa.accepts,this.root);var e=this.rootDfa,l=this.lineNumbers[d]+b;if(l==this.text.length)return this.finished=true,new QBasic.Token(this.EOF_TOKEN,"!EOF",d,b);l>0&&(c=this.text[l-1]);for(h=l;h<this.text.length;h++){var m=this.text[h];if(m==="\n"&&c!=-2)m=-2,h--;else if(c==="\n"||c===0)m=-1,h--;c==="\n"&&d++;c=m;e.next[m]===void 0&&(e.next[m]=
this.nextState(e,m));e=e.next[m];e.accepts.length&&(f=new QBasic.Token(e.accepts[0],this.text.substr(l,h-l+1),d,l-this.lineNumbers[d]));if(e.nfaStates.length===0)break}return f},nextToken:function(a,d){for(;;){var b=this.nextTokenInternal(a,d);if(b===null||b.id!==this.IGNORE_TOKEN)return b;a=b.locus.line;d=b.locus.position+b.text.length}}}})();
(function(){QBasic.NullType=function(){this.name=":NULL"};QBasic.NullType.prototype={createInstance:function(){return null},copy:function(f){return f}};QBasic.IntegerType=function(){this.name="INTEGER"};QBasic.IntegerType.prototype={createInstance:function(){return 0},copy:function(f){return(Math.round(f+32768)&65535)-32768}};QBasic.SingleType=function(){this.name="SINGLE"};QBasic.SingleType.prototype={createInstance:function(){return 0},copy:function(f){return f}};QBasic.DoubleType=function(){this.name=
"DOUBLE"};QBasic.DoubleType.prototype={createInstance:function(){return 0},copy:function(f){return f}};QBasic.StringType=function(){this.name="STRING"};QBasic.StringType.prototype={createInstance:function(){return""},copy:function(f){return f}};QBasic.AnyType=function(){this.name="ANY"};QBasic.DeriveTypeNameFromVariable=function(f){switch(f[f.length-1]){case "$":return"STRING";case "%":return"INTEGER";case "&":return"LONG";case "#":return"DOUBLE";case "!":return"SINGLE"}return null};QBasic.ArrayType=
function(f){this.elementType=f;this.name="ARRAY OF "+f.name};QBasic.UserType=function(f,b){this.name=f;this.members=b};QBasic.UserType.prototype={createInstance:function(){var f={},b;for(b in this.members)f[b]=new QBasic.ScalarVariable(this.members[b],this.members[b].createInstance());return f},copy:function(f){var b={},c;for(c in f)b[c]=f[c].copy();return b}};QBasic.Dimension=function(f,b){this.lower=f;this.upper=b};QBasic.ScalarVariable=function(f,b){this.type=f;this.value=b};QBasic.ScalarVariable.prototype=
{copy:function(){return new QBasic.ScalarVariable(this.type,this.type.copy(this.value))}};QBasic.ArrayVariable=function(f,b){this.type=f;this.dimensions=b;this.values=[];var c=1,a;for(a=0;a<this.dimensions.length;a++)c*=this.dimensions[a].upper-this.dimensions[a].lower+1;for(a=0;a<c;a++)this.values.push(new QBasic.ScalarVariable(this.type,this.type.createInstance()))};QBasic.ArrayVariable.prototype={copy:function(){return this},getIndex:function(f){for(var b=1,c=0,a=this.dimensions.length-1;a>=0;a--)c+=
(f[a]-this.dimensions[a].lower)*b,b*=this.dimensions[a].upper-this.dimensions[a].lower+1;return c},assign:function(f,b){this.values[this.getIndex(f)]=b},access:function(f){return this.values[this.getIndex(f)]}};QBasic.IsNumericType=function(f){return f.name=="INTEGER"||f.name=="SINGLE"||f.name=="DOUBLE"};QBasic.IsStringType=function(f){return f.name=="STRING"};QBasic.IsArrayType=function(f){return f instanceof QBasic.ArrayType};QBasic.IsUserType=function(f){return f instanceof QBasic.UserType};QBasic.IsNullType=
function(f){return f instanceof QBasic.NullType};QBasic.AreTypesCompatible=function(f,b){return f.name==b.name?true:QBasic.IsNumericType(f)&&QBasic.IsNumericType(b)?true:QBasic.IsArrayType(f)&&QBasic.IsArrayType(b)&&(f.elementType.name=="ANY"||b.elementType.name=="ANY")?true:!QBasic.IsArrayType(f)&&!QBasic.IsArrayType(b)&&(f.name=="ANY"||b.name=="ANY")?true:false}})();
(function(){var f=0,b=function(b,a,d,h,g,i){this.id=f++;this.rule=b;this.pos=a;this.base=d;this.token=h;this.prev=g;this.locus=i};b.prototype={toString:function(){for(var b="["+this.id+"] "+this.rule.name+":",a=0;a<this.rule.symbols.length;a++)a==this.pos&&(b+=" ."),b+=" "+this.rule.symbols[a];a==this.pos&&(b+=" .");b+=", "+this.base;this.token instanceof QBasic.Token?b+=", token="+this.token.text:this.token&&(b+=", rule="+this.token.rule);this.prev&&(b+=", prev="+this.prev.id);return b}};QBasic.EarleyParser=
function(b){this.tokenizer=b.createTokenizer();this.EPSILON=b.EPSILON;b.computeFirst();this.rules=b.rules;this.first=b.first;this.debug=false};QBasic.EarleyParser.prototype={getNonTerminal:function(b){return this.rules[b]},getRegexFromTerminal:function(b){return b.substr(1,b.length-2)},isTerminal:function(b){return b!==void 0&&b[0]=="'"},isNonTerminal:function(b){return b!==void 0&&b[0]!="'"},parse:function(c){var a=[[new b(this.rules._start[0],0,0)]],d=0,h=0;this.tokenizer.setText(c);this.errors=
[];for(c=0;;c++){var g=this.tokenizer.nextToken(d,h);if(g===null)return this.errors.push("Bad token at "+d+":"+h),this.debug&&console.log("Bad token!"),null;else this.debug&&this.debug&&console.log("Got token "+g+" at "+g.locus);this.locus=g.locus;a.push([]);for(d=0;d<a[c].length;)this.predict(a[c],d,c,g),this.complete(a,c,d,c),d++;this.scan(a,c,g);if(a[c].length===0){this.errors.push("Syntax error at "+this.locus+": "+g);for(d=0;d<a[c-1].length;d++)this.errors.push("  "+a[c-1][d]+"\n");break}this.debug&&
this.printState(a,c);d=g.locus.line;h=g.locus.position+g.text.length;if(g.id===this.tokenizer.EOF_TOKEN){c++;break}}this.debug&&this.printState(a,c);if(a[c].length)return this.evaluate(a[c][0]);this.errors.push("Syntax error at "+this.locus);for(d=0;d<a[c-1].length;d++)this.errors.push("  "+a[c-1][d]+"\n");return null},predict:function(b,a,d,h){a=b[a];if(this.isNonTerminal(a.rule.symbols[a.pos]))for(var a=this.getNonTerminal(a.rule.symbols[a.pos]),g=0;g<a.length;g++){var i=a[g];(i.symbols.length===
0||i.symbols[0][0]==="'"||this.first[i.symbols[0]][h.id]||this.first[i.symbols[0]][this.EPSILON])&&this.addToState(b,i,0,d,void 0,void 0)}},complete:function(b,a,d){d=b[a][d];if(d.pos==d.rule.symbols.length)for(var h=b[d.base],g=0;g<h.length;g++)h[g].rule.symbols[h[g].pos]==d.rule.name&&this.addToState(b[a],h[g].rule,h[g].pos+1,h[g].base,d,h[g])},scan:function(c,a,d){for(var h=c[a],g=0;g<h.length;g++)if(h[g].rule.symbols[h[g].pos]==d.id){var i=new b(h[g].rule,h[g].pos+1,h[g].base,d,h[g],this.locus);
c[a+1].push(i)}},addToState:function(c,a,d,h,g,i){for(var j=0;j<c.length;j++)if(c[j].rule===a&&c[j].pos===d&&c[j].base===h)return;c.push(new b(a,d,h,g,i,this.locus))},printState:function(b,a){if(this.debug){var d=b[a];console.log("State ["+a+"]");for(var h=0;h<d.length;h++)console.log(d[h])}},evaluate:function(b){if(b){for(var a=[],d=b,h=b.locus;d;)d.token instanceof QBasic.Token?a.unshift(d.token.text):d.token&&a.unshift(this.evaluate(d.token)),h=d.locus,d=d.prev;return b.rule.action?b.rule.action(a,
h):a[0]}}}})();
(function(){function f(c,a,d){this.id=b++;this.name=c;this.symbols=a;this.action=d}var b=0;f.prototype={toString:function(){for(var b=this.name+":",a=0;a<this.symbols.length;a++)b+=" "+this.symbols[a];return b}};QBasic.RuleSet=function(){this.rules={};this.terminals=[];this.terminalsAdded={};this.first={};this.joinExpr=(this.eatWhiteSpace=true," *");this.EOF_TOKEN="'EOF'";this.addRule("_start",["start",this.EOF_TOKEN])};QBasic.RuleSet.prototype={EPSILON:{toString:function(){return"EPSILON"}},toString:function(){var b=
"",a;for(a in this.rules)for(var d=this.rules[a],h=0;h<d.length;h++)b+=d[h].toString()+"\n";return b},check:function(b){var a=b.length,d;for(d in this.rules)for(var h=this.rules[d],g=0;g<h.length;g++)for(var i=h[g],j=0;j<i.symbols.length;j++){var f=i.symbols[j];f.length===0?b.push("Error: Rule '"+d+"' contains a zero length symbol: "+f):f[0]!="'"&&this.rules[f]===void 0&&b.push("Error: Rule'"+d+"' contains an undefined symbol: "+f)}return b.length-a},optimize:function(){for(var b=1;b;){var b=0,a;
for(a in this.rules){var d=this.rules[a];d.length==1&&d[0].name!="_start"&&!d[0].action&&(this.replaceRule(d[0].name,d[0].symbols),b|=1)}}},innerExpr:function(b){return b.substr(1,b.length-2)},replaceRule:function(b,a){delete this.rules[b];for(var d in this.rules)for(var h=this.rules[d],g=0;g<h.length;g++)for(var i=0;i<h[g].symbols.length;i++)if(h[g].symbols[i]==b){h[g].symbols.splice(i,1);for(var j=0;j<a.length;j++)h[g].symbols.splice(i+j,0,a[j]);i+=a.length-1}},addRule:function(b,a,d){this.rules[b]===
void 0&&(this.rules[b]=[]);this.rules[b].push(new f(b,a,d));for(b=0;b<a.length;b++)a.length>0&&a[b][0]=="'"&&!this.terminalsAdded[a[b]]&&(this.terminalsAdded[a[b]]=1,this.terminals.push(a[b]))},addToken:function(b,a){this.addRule(b,["'"+a+"'"])},computeFirst:function(){function b(a,d){var c=!(d in g.first[a]);g.first[a][d]=1;return c}function a(a,d){var h=0,m;for(m in g.first[d])h|=b(a,m);return h}this.first={};for(var d in this.rules)this.first[d]={};for(var h=1,g=this;h;)for(d in h=0,this.rules)for(var i=
this.rules[d],j=0;j<i.length;j++){i[j].symbols.length===0&&(h|=b(d,this.EPSILON));for(var f=0;f<i[j].symbols.length;f++)if(i[j].symbols[f][0]=="'"){h|=b(d,i[j].symbols[f]);break}else if(h|=a(d,i[j].symbols[f]),this.first[i[j].symbols[f]][this.EPSILON]!==1)break}},computeFollow:function(){var b;this.follow={};for(b in this.rules)this.follow[b]={};for(var a=1;a;){var a=0,d;for(b in this.rules)for(var h=this.rules[b],g=0;g<h.length;g++)for(var i=h[g],f=0;f<i.symbols.length;f++)if(i.symbols[f][0]!=="'"){var k=
this.follow[i.symbols[f]];if(f==i.symbols.length-1){if(i.symbols[f][0]!="'"&&i.symbols[f]!=b)for(d in this.follow[b])d!==this.EPSILON&&(a|=k[d]===void 0,k[d]=1)}else if(i.symbols[f+1][0]=="'"||i.symbols[f+1]===this.EOF_TOKEN)a|=k[i.symbols[f+1]]===void 0,k[i.symbols[f+1]]=1;else for(d in this.first[i.symbols[f+1]])d!==this.EPSILON&&(a|=k[d]===void 0,k[d]=1)}}},finalize:function(){this.optimize();this.computeFirst();this.computeFollow()},createTokenizer:function(){var b=new QBasic.Tokenizer;b.ignore("[ \t\r\u001a]+");
for(var a=0;a<this.terminals.length;a++)b.addToken(this.terminals[a],this.innerExpr(this.terminals[a]));b.EOF_TOKEN=this.EOF_TOKEN;return b}}})();
(function(){QBasic.RuleParser=function(){this.nextRuleId=0;this.buildSet=new QBasic.RuleSet;var f=new QBasic.RuleSet,b=this;f.addRule("start",["rule"]);f.addRule("identifier",["'[A-Za-z0-9_]+'"]);f.addRule("terminal",["''([^'\\\\]|\\\\.)*''"]);f.addRule("expr",["or_expr"]);f.addRule("rule",["identifier","':'","expr"],function(c){b.buildSet.addRule(c[0],c[2],b.action);return c[0]});f.addRule("rule",["identifier","':'"],function(c){b.buildSet.addRule(c[0],[],b.action);return c[0]});f.addRule("or_expr",
["or_expr","'\\|'","cat_expr"],function(c){var a="_"+b.nextRuleId++;b.buildSet.addRule(a,c[0]);b.buildSet.addRule(a,c[2]);return[a]});f.addRule("or_expr",["cat_expr"]);f.addRule("cat_expr",["cat_expr","list_expr"],function(b){b[0].push(b[1]);return b[0]});f.addRule("cat_expr",["list_expr"],function(b){return[b[0]]});f.addRule("list_expr",["kleene_expr"]);f.addRule("list_expr",["'\\['","kleene_expr","','","kleene_expr","'\\]'"],function(c){var a="_"+b.nextRuleId++,d="_"+b.nextRuleId++;b.buildSet.addRule(a,
[d]);b.buildSet.addRule(a,[],function(){return[]});b.buildSet.addRule(d,[c[1]],function(a){return a});b.buildSet.addRule(d,[d,c[3],c[1]],function(a){a[0].push(a[2]);return a[0]});return a});f.addRule("kleene_expr",["basic_expr","'[\\+\\*\\?]'"],function(c){var a="_"+b.nextRuleId++;if(c[1]=="*")b.buildSet.addRule(a,[a,c[0]],function(a){a[0].push(a[1]);return a[0]}),b.buildSet.addRule(a,[],function(){return[]});else if(c[1]=="?")b.buildSet.addRule(a,[c[0]]),b.buildSet.addRule(a,[],function(){return null});
else if(c[1]=="+"){var d="_"+b.nextRuleId++;b.buildSet.addRule(a,[d,c[0]]);b.buildSet.addRule(d,[d,c[0]]);b.buildSet.addRule(d,[])}return a});f.addRule("kleene_expr",["basic_expr"]);f.addRule("basic_expr",["identifier"]);f.addRule("basic_expr",["'\\('","expr","'\\)'"],function(c){var a="_"+b.nextRuleId++;b.buildSet.addRule(a,c[1]);return a});f.addRule("basic_expr",["terminal"]);f.finalize();this.parser=new QBasic.EarleyParser(f)};QBasic.RuleParser.prototype={addToken:function(f,b){this.buildSet.addToken(f,
b)},addRule:function(f,b){this.action=b;this.parser.parse(f)}}})();
(function(){function f(){this.names={}}function b(a,b){this.name=a;this.astNode=b}function c(a,b){this.type=a;this.counter=b}QBasic.TypeChecker=function(a,b){a=a||{};this.declaredSubs=a.declaredSubs||{};this.declaredSubs._main=new QBasic.AstDeclareFunction(new QBasic.Locus(0,0),"_main",[],false);this.errors=b;this.scopes=a.scopes||[new f];this.shared=a.shared||new f;this.labelsUsed=a.labelsUsed||[];this.labelsDefined=a.labelsDefined||{};this.types=a.types||{INTEGER:new QBasic.IntegerType,SINGLE:new QBasic.SingleType,
DOUBLE:new QBasic.DoubleType,STRING:new QBasic.StringType,ANY:new QBasic.AnyType,":NULL":new QBasic.NullType};this.defaultType=a.defaultType||this.types.SINGLE;this.loopStack=a.loopStack||[]};QBasic.TypeChecker.prototype={sprintf:function(){var a=arguments;a.length==1&&a[0]instanceof Array&&(a=a[0]);for(var b="",c=a[0].split(/%[^%]/),g=0;g<c.length;g++)b+=c[g],a[g+1]!==void 0&&(b+=a[g+1]);return b},error:function(){for(var a=arguments[0],b=[],c=1;c<arguments.length;c++)b.push(arguments[c]);a="Error at "+
a.locus+": "+this.sprintf(b);this.errors.push(a);throw Error(a);},removeSuffix:function(a){switch(a[a.length-1]){case "%":case "$":case "!":case "&":case "#":return a.substr(0,a.length-1);default:return a}},getTypeFromVariableName:function(a){var b=this.scopes[0].names[a];if(b!==void 0)return b;b=this.shared.names[a];if(b!==void 0)return b;b=QBasic.DeriveTypeNameFromVariable(a);return b!==null?this.types[b]:this.defaultType},visitProgram:function(a){var b;for(b=0;b<a.subs.length;b++)a.subs[b].accept(this);
for(b=0;b<this.labelsUsed.length;b++)a=this.labelsUsed[b],this.labelsDefined[a.name]===void 0&&this.error(a.astNode,"Label %s is not defined",a.name);for(var c in this.declaredSubs)b=this.declaredSubs[c],!b.hasBody&&b.used&&this.error(b,"SUB or FUNCTION '%s' has no body",c)},visitDeclareFunction:function(a){this.declaredSubs[a.name]!==void 0&&this.error(a,"Subroutine %s is already declared on line %s",a.name,this.declaredSubs[a.name].locus.line+1);this.declaredSubs[a.name]=a;a.args.accept(this);if(a.isFunction)a.type=
this.getTypeFromVariableName(a.name)},visitSubroutine:function(a){function b(d){g.error(a,"Sub or function %s does not match declaration on line %s",a.name,d.locus.line+1)}var c,g=this;if(this.declaredSubs[a.name]===void 0)this.error(a,"Subroutine %s is not declared",a.name);else{var i=this.declaredSubs[a.name];i.isFunction!=a.isFunction&&b(i);if(a.args.length!=i.args.length)b(i);else for(c=0;c<a.args.length;c++)(a.args[c].typeName!=i.args[c].typeName&&i.args[c].typeName!="ANY"||a.args[c].isArray!=
i.args[c].isArray)&&b(i);i.hasBody=true}this.scopes.unshift(new f);for(c=0;c<a.args.length;c++)a.args[c].accept(this),this.scopes[0].names[a.args[c].name]=a.args[c].type;for(c=0;c<a.statements.length;c++)a.statements[c]&&(a.statements[c].accept===void 0?console.log("ERROR: Could not visit object of type "+a.statements[c]):a.statements[c].accept(this));this.scopes.shift()},checkCallArguments:function(a,b){a.used=true;if(a.args.length!=b.length)this.error(a,"Wrong number of arguments");else for(var c=
0;c<b.length;c++)b[c].wantRef=true,b[c].accept(this),QBasic.AreTypesCompatible(b[c].type,a.args[c].type)||this.error(b[c],"Type mismatch in argument %d of call to %s. Expected %s but got %s",c+1,a.name,a.args[c].type.name,b[c].type.name)},visitCallStatement:function(a){if(QBasic.SystemSubroutines[a.name]!==void 0)for(var b=0;b<a.args.length;b++)a.args[b].wantRef=true,a.args[b].accept(this);else b=this.declaredSubs[a.name],b===void 0?this.error(a,"Call to undefined sub '%s'",a.name):this.checkCallArguments(b,
a.args)},visitArgument:function(a){var b;a.typeName?(b=this.types[a.typeName],b===void 0&&(this.error(a,"Type %s is not defined",a.typeName),b=new QBasic.UserType(a.typeName,{}),this.types[a.typeName]=b)):b=this.getTypeFromVariableName(a.name);a.isArray&&(b=new QBasic.ArrayType(b));a.type=b},visitPrintStatement:function(a){a.printItems.accept(this)},visitPrintUsingStatement:function(a){for(var b=0;b<a.exprList.length;b++)a.exprList[b].wantRef=true,a.exprList[b].accept(this),b===0&&!QBasic.IsStringType(a.exprList[b].type)?
this.error(a.exprList[b],"Format string must be STRING, not %s",a.exprList[b].type.name):b>0&&!QBasic.IsStringType(a.exprList[b].type)&&!QBasic.IsNumericType(a.exprList[b].type)&&this.error(a.exprList[b],"Type Mismatch Error");a.exprList.length===0&&this.error(a,"PRINT USING requires at least one argument")},visitPrintItem:function(a){a.expr!==null&&(a.expr.accept(this),!QBasic.IsNumericType(a.expr.type)&&!QBasic.IsStringType(a.expr.type)&&this.error(a.expr,"Expected string or number, but got '%s'",
a.expr.type.name))},visitInputStatement:function(a){a.promptExpr&&(a.promptExpr.accept(this),QBasic.IsStringType(a.promptExpr.type)||this.error(a,"Prompt must be a string"));for(var b=0;b<a.identifiers.length;b++){var c=this.getTypeFromVariableName(a.identifiers[b]);!QBasic.IsNumericType(c)&&!QBasic.IsStringType(c)&&this.error(a,"Identifier '%s' should be string or numeric.",a.identifiers.type)}},visitNullStatement:function(){},visitEndStatement:function(){},visitForLoop:function(a){QBasic.IsNumericType(this.getTypeFromVariableName(a.identifier))||
this.error(a,"Loop counter must be a number");a.startExpr.wantRef=true;a.startExpr.accept(this);a.endExpr.accept(this);a.stepExpr.accept(this);(!QBasic.IsNumericType(a.startExpr.type)||!QBasic.IsNumericType(a.endExpr.type)||!QBasic.IsNumericType(a.stepExpr.type))&&this.error(a,"Loop expression must be a number.");this.loopStack.unshift(new c("FOR",a.identifier))},visitNextStatement:function(a){for(var b=0;b<a.identifiers.length;b++){if(this.loopStack.length===0){this.error(a,"NEXT without FOR");break}if(this.loopStack[0].type!==
"FOR"){this.error(a,"NEXT without FOR");break}a.identifiers[b]!=this.loopStack[0].counter&&this.error(a,"Mismatched loop counter '%s' in NEXT",a.identifiers[b]);this.loopStack.shift()}a.identifiers.length===0&&(this.loopStack.length===0?this.error(a,"NEXT without FOR"):this.loopStack.shift())},visitExitStatement:function(a){a.what&&a.what!="FOR"&&a.what!="DO"&&a.what!="WHILE"&&this.error(a,"EXIT %s not supported",a.what);this.loopStack.length===0&&this.error(a,"EXIT without loop not supported");a.what&&
a.what!=this.loopStack[0].type&&this.error(a,"MISMATCHED EXIT. Expected: '%s'",this.loopStack[0].type)},visitArrayDeref:function(a){var b;a.expr.accept(this);if(a.expr instanceof QBasic.AstVariableReference&&this.declaredSubs[a.expr.name])b=this.declaredSubs[a.expr.name],b.isFunction||this.error(a,"Tried to call non-function '%s'",a.expr.name),this.checkCallArguments(b,a.parameters),a.type=b.type;else if(a.expr instanceof QBasic.AstVariableReference&&QBasic.SystemFunctions[a.expr.name]!==void 0){var c=
QBasic.SystemFunctions[a.expr.name];a.type=this.types[c.type];a.parameters.accept(this);if(a.parameters.length<c.minArgs||a.parameters.length>c.args.length)this.error(a,"Function '%s' called with wrong number of arguments",c.name);else for(b=0;b<a.parameters.length;b++)QBasic.AreTypesCompatible(a.parameters[b].type,this.types[c.args[b]])||this.error(a,"Argument %d to '%s' function is of type '%s', but '%s' expected",b+1,c.name,a.parameters[b].type.name,c.args[b])}else{for(b=0;b<a.parameters.length;b++)a.parameters[b].accept(this),
QBasic.IsNumericType(a.parameters[b].type)||this.error(a.parameters[b],"Array subscript must be numeric type");QBasic.IsArrayType(a.expr.type)?a.type=a.parameters.length===0?a.expr.type:a.expr.type.elementType:(this.error(a,"Subscript used on non-array '%s'",a.expr.name),a.type=this.types.INTEGER)}},visitMemberDeref:function(a){a.lhs.accept(this);if(QBasic.IsUserType(a.lhs.type)){if(a.type=a.lhs.type.members[a.identifier],a.type===void 0)this.error(a,"Type '%s' does not contain member '%s'",a.lhs.type.name,
a.identifier),a.type=this.types.SINGLE}else this.error(a,"Tried to dereference non-user-type '%s'",a.lhs.type.name),a.type=this.types.SINGLE},visitVariableReference:function(a){var b;QBasic.SystemFunctions[a.name]!==void 0?(b=QBasic.SystemFunctions[a.name],a.type=this.types[b.type]):this.declaredSubs[a.name]!==void 0?(b=this.declaredSubs[a.name],b.isFunction?a.type=b.type:(this.error(a,"SUB '%s' used as a function",b.name),a.type=this.types.SINGLE)):a.type=this.getTypeFromVariableName(a.name)},visitRange:function(a){a.lowerExpr.accept(this);
a.upperExpr.accept(this);(!QBasic.IsNumericType(a.lowerExpr.type)||!QBasic.IsNumericType(a.upperExpr.type))&&this.error(a,"Expected a number.")},visitDataStatement:function(){},visitReturnStatement:function(){},visitRestoreStatement:function(a){a.label&&this.labelsUsed.push(new b(a.label,a))},visitConstStatement:function(a){a.name in this.shared.names&&this.error(a,"Redeclared variable '%s'",a.name);a.expr.accept(this);this.shared.names[a.name]=a.expr.type},visitDefTypeStatement:function(a){this.defaultType=
this.types[a.typeName]},visitDimStatement:function(a){var b;a.typeName&&(b=this.types[a.typeName],b===void 0&&this.error(a,"Type '%s' is not defined",a.typeName));if(!b)b=this.getTypeFromVariableName(a.name),a.typeName=b.name;for(var c=0;c<a.ranges.length;c++)a.ranges[c].accept(this);a.ranges.length&&(b=new QBasic.ArrayType(b));a.shared?this.shared.names[a.name]=b:this.scopes[0].names[a.name]=b},visitDoStatement:function(a){a.expr&&a.expr.accept(this);a.expr!==null&&!QBasic.IsNumericType(a.expr.type)&&
this.error(a,"Loop expression must be numeric");this.loopStack.unshift(new c("DO",null));a.statements.accept(this);this.loopStack.shift()},visitWhileLoop:function(a){a.expr.accept(this);QBasic.IsNumericType(a.expr.type)||this.error(a,"Loop expression must be numeric");this.loopStack.unshift(new c("WHILE",null));a.statements.accept(this);this.loopStack.shift()},visitIfStatement:function(a){a.expr.accept(this);QBasic.IsNumericType(a.expr.type)||this.error(a,"Expected numeric expression");a.statements.accept(this);
a.elseStatements&&a.elseStatements.accept(this)},visitSelectStatement:function(a){a.expr.accept(this);!QBasic.IsNumericType(a.expr.type)&&!QBasic.IsStringType(a.expr.type)&&this.error(a,"Select expression must be numeric or string");for(var b=0;b<a.cases.length;b++){var c=a.cases[b];c.accept(this);for(var g=0;g<c.exprList.length;g++)QBasic.AreTypesCompatible(a.expr.type,c.exprList[g].type)||this.error(c,"CASE expression cannot be compared with SELECT")}},visitCaseStatement:function(a){a.exprList.accept(this);
a.statements.accept(this)},visitTypeMember:function(a){var b;a.typeName&&(b=this.types[a.typeName],b===void 0&&this.error(a,"Undefined type '%s'",a.typeName));b===void 0&&(b=this.getTypeFromVariableName(a.name));a.type=b},visitUserType:function(a){this.types[a.name]!==void 0&&this.error(a,"Typename '%s' already defined",a.name);for(var b={},c=0;c<a.members.length;c++)a.members[c].accept(this),b[a.members[c].name]!==void 0&&this.error(a.members[c],"Type member '%s' already defined",a.members[c].name),
b[a.members[c].name]=a.members[c].type;this.types[a.name]=new QBasic.UserType(a.name,b)},visitGotoStatement:function(a){this.labelsUsed.push(new b(a.label,a))},visitGosub:function(a){this.labelsUsed.push(new b(a.label,a))},visitLabel:function(a){this.labelsDefined[a.label]!==void 0&&this.error(a,"Label '%s' is already defined",a.label);this.labelsDefined[a.label]=new b(a.label,a)},visitAssignStatement:function(a){a.lhs.wantRef=true;a.lhs.accept(this);a.expr.accept(this);QBasic.AreTypesCompatible(a.lhs.type,
a.expr.type)||this.error(a,"Tried to assign type '%s' to type '%s'",a.expr.type.name,a.lhs.type.name)},visitBinaryOp:function(a){var b=a.op;a.lhs.accept(this);a.rhs.accept(this);var c=0,g=a.lhs.type;QBasic.AreTypesCompatible(a.lhs.type,a.rhs.type)||(c=1);QBasic.IsStringType(a.lhs.type)&&(c|=b!="+"&&b!="<"&&b!=">"&&b!="<>"&&b!="="&&b!="==");QBasic.IsUserType(a.lhs.type)&&(c|=b!="="&&b!="==");if(b=="="||b=="=="||b=="<>"||b=="<"||b=="<="||b==">=")g=this.types.INTEGER;QBasic.IsArrayType(a.lhs.type)&&
(c|=1);c&&this.error(a,"Incompatible types for '%s' operator: %s,%s",a.op,a.lhs.type.name,a.rhs.type.name);a.type=g},visitUnaryOperator:function(a){a.expr.accept(this);QBasic.IsNumericType(a.expr.type)||this.error(a,"Incompatible type for '%s' operator",a.op);a.type=a.expr.type},visitConstantExpr:function(a){a.type=a.value===null?this.types[":NULL"]:a.value.constructor==String?this.types.STRING:this.types.SINGLE}}})();
(function(){function f(a,b){this.instr=a;this.arg=b}function b(a,b,c){this.name=a;this.codeOffset=b;this.dataOffset=c}function c(a,b,c,g){this.counter=a;this.forLabel=b;this.nextLabel=c;this.endLabel=g}f.prototype={toString:function(){return this.instr.numArgs===0?this.instr.name:this.instr.name+" "+this.arg}};QBasic.CodeGenerator=function(a){a=a||{};this.instructions=a.instructions||[];this.instructions_start=a.instructions?a.instructions.length:0;this.data=a.data||[];this.shared=a.shared||{};this.labels=
a.labels||[];this.labelMap=a.labelMap||{};this.loopStack=a.loopStack||[];this.selectStack=a.selectStack||[];this.functionNames=a.functionNames||{};this.lineMapping=a.lineMapping||[];this.lastLine=a.lastLine||-1;a||this.getGotoLabel(":top")};QBasic.CodeGenerator.prototype={link:function(){for(var a=this.instructions_start;a<this.instructions.length;a++){var b=this.instructions[a];if(b.instr.addrLabel)b.arg=this.labels[b.arg].codeOffset;else if(b.instr.dataLabel)b.arg=this.labels[b.arg].dataOffset}},
newLabel:function(a){var c=this.labels.length;this.labels.push(new b(a+"_"+c,this.instructions.length,this.data.length));return c},label:function(a){this.labels[a].codeOffset=this.instructions.length;this.labels[a].dataOffset=this.data.length},map:function(a){if(a.line!==this.lastLine)this.lastLine=a.line,this.lineMapping[this.instructions.length]=a},getGotoLabel:function(a){var b;a in this.labelMap?b=this.labelMap[a]:(b=this.newLabel(a),this.labelMap[a]=b);return b},write:function(a,b){var c=QBasic.Instructions[a];
if(c===void 0)throw"Bad instruction: "+a;this.instructions.push(new f(c,b))},visitProgram:function(a){for(var b=0;b<a.subs.length;b++)a.subs[b].accept(this);this.link()},visitDeclareFunction:function(a){this.functionNames[a.name]=true},visitSubroutine:function(a){var b=null;this.map(a.locus);if(a.name!="_main"){b=this.newLabel("skipsub");this.write("JMP",b);this.label(this.getGotoLabel(a.name));for(var c=a.args.length-1;c>=0;c--)this.write("POPVAR",a.args[c].name)}a.statements.accept(this);a.isFunction&&
this.write("PUSHVALUE",a.name);b!==null&&(this.write("RET",null),this.label(b))},visitCallStatement:function(a){this.map(a.locus);for(var b=0;b<a.args.length;b++)a.args[b].accept(this);QBasic.SystemSubroutines[a.name]?(b=QBasic.SystemSubroutines[a.name],b.args!==void 0&&b.minArgs!==void 0&&this.write("PUSHCONST",a.args.length),this.write("SYSCALL",a.name)):a.name=="PRINT"?(this.write("PUSHCONST",a.args.length),this.write("SYSCALL",a.name)):this.write("CALL",this.getGotoLabel(a.name))},visitArgument:function(){},
visitPrintUsingStatement:function(a){for(var b=0;b<a.exprList.length;b++)a.exprList[b].accept(this);this.write("PUSHCONST",a.terminator);this.write("PUSHCONST",a.exprList.length+1);this.write("SYSCALL","__print_using")},visitPrintStatement:function(a){var b=true;this.map(a.locus);for(var c=0;c<a.printItems.length;c++)a.printItems[c].accept(this),a.printItems[c].type===QBasic.AstPrintItem.TAB?this.write("SYSCALL","print_tab"):a.printItems[c].expr&&this.write("SYSCALL","print"),a.printItems[c].terminator==
","?this.write("SYSCALL","print_comma"):b=a.printItems[c].terminator==";"?false:true;b&&(this.write("PUSHCONST","\n"),this.write("SYSCALL","print"))},visitPrintItem:function(a){a.expr&&a.expr.accept(this)},visitInputStatement:function(a){this.map(a.locus);a.promptExpr&&(a.promptExpr.accept(this),this.write("SYSCALL","print"));a.printQuestionMark?this.write("PUSHCONST","? "):this.write("PUSHCONST"," ");this.write("SYSCALL","print");for(var b=0;b<a.identifiers.length;b++)this.write("PUSHREF",a.identifiers[b]);
this.write("PUSHCONST",a.identifiers.length);this.write("SYSCALL","INPUT")},visitNullStatement:function(){},visitEndStatement:function(a){this.map(a.locus);this.write("END",null)},visitForLoop:function(a){this.map(a.locus);var b=this.newLabel("for"),f=this.newLabel("next"),g=this.newLabel("end_for");this.loopStack.push(new c(a.identifier,b,f,g));a.startExpr.accept(this);this.write("POPVAR",a.identifier);a.endExpr.accept(this);a.stepExpr.accept(this);this.label(b);this.write("PUSHVALUE",a.identifier);
this.write("FORLOOP",g)},visitNextStatement:function(a){this.map(a.locus);for(var b=0;b<a.identifiers.length;b++){var c=this.loopStack.pop();this.label(c.nextLabel);this.write("COPYTOP");this.write("PUSHVALUE",c.counter);this.write("+");this.write("POPVAL",c.counter);this.write("JMP",c.forLabel);this.label(c.endLabel)}},visitExitStatement:function(){var a=this.loopStack[this.loopStack.length-1];a.counter&&(this.write("POP"),this.write("POP"));this.write("JMP",a.endLabel)},visitArrayDeref:function(a){this.map(a.locus);
if(a.expr instanceof QBasic.AstVariableReference&&this.functionNames[a.expr.name])a.parameters.accept(this),this.write("CALL",this.getGotoLabel(a.expr.name));else if(a.expr instanceof QBasic.AstVariableReference&&QBasic.SystemFunctions[a.expr.name]){var b=QBasic.SystemFunctions[a.expr.name];a.parameters.accept(this);b.minArgs<b.args.length&&this.write("PUSHCONST",a.parameters.length);a.expr.accept(this)}else a.parameters.accept(this),a.expr.accept(this),a.parameters.length>0&&this.write("ARRAY_DEREF",
a.wantRef)},visitMemberDeref:function(a){this.map(a.locus);a.lhs.accept(this);a.wantRef?this.write("MEMBER_DEREF",a.identifier):this.write("MEMBER_VALUE",a.identifier)},visitVariableReference:function(a){this.map(a.locus);QBasic.SystemFunctions[a.name]?this.write("SYSCALL",a.name):this.functionNames[a.name]?(this.write("CALL",this.getGotoLabel(a.name)),a.wantRef&&this.write("NEW",a.type.name)):a.wantRef||QBasic.IsArrayType(a.type)?this.write("PUSHREF",a.name):this.write("PUSHVALUE",a.name)},visitRange:function(){},
visitDataStatement:function(a){for(var b=0;b<a.data.length;b++)this.data.push(a.data[b].value)},visitReturnStatement:function(a){this.map(a.locus);this.write("RET")},visitRestoreStatement:function(a){this.map(a.locus);var b=0,b=a.label?this.getGotoLabel(a.label):this.getGotoLabel(":top");this.write("RESTORE",b)},visitConstStatement:function(a){this.shared[a.name]=true;a.expr.accept(this);this.write("POPVAL",a.name)},visitDefTypeStatement:function(){},visitDimStatement:function(a){this.map(a.locus);
var b;b=a.typeName?a.typeName:"INTEGER";a.shared&&(this.shared[a.name]=true);if(a.ranges.length>0){for(var c=0;c<a.ranges.length;c++)a.ranges[c].lowerExpr.accept(this),a.ranges[c].upperExpr.accept(this);this.write("PUSHCONST",a.ranges.length);this.write("PUSHTYPE",b);this.write("SYSCALL","alloc_array")}else this.write("PUSHTYPE",b),this.write("SYSCALL","alloc_scalar");this.write("POPVAR",a.name)},visitDoStatement:function(a){this.map(a.locus);var b=this.newLabel("do"),f=this.newLabel("loop");this.label(b);
this.loopStack.push(new c(null,null,null,f));a.statements.accept(this);this.loopStack.pop();switch(a.type){case QBasic.AstDoStatement.UNTIL:a.expr.accept(this);this.write("BZ",b);break;case QBasic.AstDoStatement.WHILE_AT_END:a.expr.accept(this);this.write("BNZ",b);break;case QBasic.AstDoStatement.INFINITE:this.write("JMP",b)}this.label(f)},visitWhileLoop:function(a){this.map(a.locus);var b=this.newLabel("while"),f=this.newLabel("wend");this.label(b);a.expr.accept(this);this.write("BZ",f);this.loopStack.push(new c(null,
null,null,f));a.statements.accept(this);this.loopStack.pop();this.write("JMP",b);this.label(f)},visitIfStatement:function(a){this.map(a.locus);var b=this.newLabel("endif"),c=this.newLabel("else");a.expr.accept(this);this.write("BZ",c);a.statements.accept(this);this.write("JMP",b);this.label(c);a.elseStatements&&(a.elseStatements.accept(this),this.write("JMP",b));this.label(b)},visitSelectStatement:function(a){this.map(a.locus);var b=this.newLabel("end_select");this.selectStack.push(b);a.expr.accept(this);
a.cases.accept(this);this.write("POP");this.label(b);this.selectStack.pop()},visitCaseStatement:function(a){this.map(a.locus);if(a.exprList.length>0){for(var b=this.newLabel("case_okay"),c=this.newLabel("case_skip"),g=0;g<a.exprList.length;g++)this.write("COPYTOP"),a.exprList[g].accept(this),this.write("="),this.write("BNZ",b);this.write("JMP",c);this.label(b);a.statements.accept(this);this.write("JMP",this.selectStack[this.selectStack.length-1]);this.label(c)}else a.statements.accept(this)},visitTypeMember:function(){},
visitUserType:function(){},visitGotoStatement:function(a){this.map(a.locus);this.write("JMP",this.getGotoLabel(a.label))},visitGosub:function(a){this.map(a.locus);this.write("GOSUB",this.getGotoLabel(a.label))},visitLabel:function(a){this.label(this.getGotoLabel(a.label))},visitAssignStatement:function(a){this.map(a.locus);a.expr.accept(this);a.lhs instanceof QBasic.AstVariableReference&&this.functionNames[a.lhs.name]?this.write("POPVAL",a.lhs.name):(a.lhs.accept(this),this.write("ASSIGN"))},visitBinaryOp:function(a){this.map(a.locus);
a.lhs.accept(this);a.rhs.accept(this);this.write(a.op);a.wantRef&&this.write("NEW",a.type.name)},visitUnaryOperator:function(a){this.map(a.locus);a.expr.accept(this);this.write("UNARY_OP",a.op);a.wantRef&&this.write("NEW",a.type.name)},visitConstantExpr:function(a){this.map(a.locus);this.write("PUSHCONST",a.value);a.wantRef&&this.write("NEW",a.type.name)}}})();
(function(){function f(b){this.pc=b;this.variables={}}QBasic.VirtualMachine=function(b){this.stack=[];this.pc=0;this.callstack=[];this.cons=b;this.instructions=[];this.types=[];this.shared={};this.dataPtr=0;this.data=[];this.suspended=false;this.lastRandomNumber=0;this.lastProgram=null};QBasic.VirtualMachine.prototype={loadProgram:function(b){this.pc=this.lastProgram?this.lastProgram.instructions.length:0;this.defaultType=b.defaultType;this.instructions=b.instructions;this.data=b.data;this.shared=
b.shared;this.types=b.types;this.callstack.length==0&&this.callstack.push(new f(this.instructions.length));this.frame=this.callstack[0];this.suspended=false;this.lastProgram=b},run:function(b,c){b instanceof QBasic.Program||(b=new QBasic.Program(b,this.lastProgram));this.loadProgram(b);this.callback=c;this.resume()},suspend:function(){this.suspended=true},resume:function(){for(this.suspended=false;this.pc<this.instructions.length&&!this.suspended;)this.runOneInstruction();this.pc==this.instructions.length&&
this.callback&&this.callback()},runOneInstruction:function(){var b=this.instructions[this.pc++];b.instr.execute(this,b.arg)},setVariable:function(b,c){this.shared[b]?this.callstack[0].variables[b]=c:this.frame.variables[b]=c},getVariable:function(b){var c;c=this.shared[b]?this.callstack[0]:this.frame;if(c.variables[b])return c.variables[b];else{var a=QBasic.DeriveTypeNameFromVariable(b),a=a===null?this.defaultType:this.types[a],a=new QBasic.ScalarVariable(a,a.createInstance());return c.variables[b]=
a}},printStack:function(){for(var b=0;b<this.stack.length;b++){var c=this.stack[b],a=c;a=="ScalarVariable"&&(a+=" "+c.value);console.log("TRACE: stack["+b+"]: "+a)}},pushScalar:function(b,c){this.stack.push(new QBasic.ScalarVariable(this.types[c],b))}};QBasic.SystemFunctions={RND:{type:"SINGLE",args:["INTEGER"],minArgs:0,action:function(b){var c=1;b.stack.pop()==1&&(c=b.stack.pop());if(c!=0)b.lastRandomNumber=Math.random();b.stack.push(b.lastRandomNumber)}},CHR$:{type:"STRING",args:["INTEGER"],minArgs:1,
action:function(b){var c=b.stack.pop();b.stack.push(String.fromCharCode(c))}},INKEY$:{type:"STRING",args:[],minArgs:0,action:function(){}},LEN:{type:"INTEGER",args:["STRING"],minArgs:1,action:function(b){b.stack.push(b.stack.pop().length)}},MID$:{type:"STRING",args:["STRING","INTEGER","INTEGER"],minArgs:2,action:function(b){var c;b.stack.pop()==3&&(c=b.stack.pop());var a=b.stack.pop(),d=b.stack.pop();b.stack.push(d.substr(a-1,c))}},LEFT$:{type:"STRING",args:["STRING","INTEGER"],minArgs:2,action:function(b){var c=
b.stack.pop(),a=b.stack.pop();b.stack.push(a.substr(0,c))}},RIGHT$:{type:"STRING",args:["STRING","INTEGER"],minArgs:2,action:function(b){var c=b.stack.pop(),a=b.stack.pop();b.stack.push(a.substr(a.length-c))}},TIMER:{type:"INTEGER",args:[],minArgs:0,action:function(b){var c=new Date,c=c.getMilliseconds()/1E3+c.getSeconds()+c.getMinutes()*60+c.getHours()*3600;b.stack.push(c)}},PEEK:{type:"INTEGER",args:["INTEGER"],minArgs:1,action:function(b){b.stack.pop();b.stack.push(0)}},LCASE$:{type:"STRING",args:["STRING"],
minArgs:1,action:function(b){var c=b.stack.pop();b.stack.push(c.toLowerCase())}},UCASE$:{type:"STRING",args:["STRING"],minArgs:1,action:function(b){b.stack.push(b.stack.pop().toUpperCase())}},STR$:{type:"STRING",args:["SINGLE"],minArgs:1,action:function(b){var c=b.stack.pop();b.stack.push(""+c)}},SPACE$:{type:"STRING",args:["INTEGER"],minArgs:1,action:function(b){for(var c=b.stack.pop(),a="",d=0;d<c;d++)a+=" ";b.stack.push(a)}},STRING$:{type:"STRING",args:["INTEGER","STRING"],minArgs:2,action:function(b){for(var c=
b.stack.pop(),a=b.stack.pop(),d="",f=0;f<a;f++)d+=c;b.stack.push(d)}},VAL:{type:"SINGLE",args:["STRING"],minArgs:1,action:function(b){b.stack.push(parseFloat(b.stack.pop()))}},INT:{type:"INTEGER",args:["SINGLE"],minArgs:1,action:function(b){b.stack.push(Math.floor(b.stack.pop()))}}};QBasic.SystemSubroutines={RANDOMIZE:{args:["INTEGER"],minArgs:0,action:function(b){var c=b.stack.pop();if(c==0)Math.seed();else if(c==1)Math.seed(b.stack.pop().value);else throw Error("RANDOMIZE takes at most 1 argument.");
}},CLS:{action:function(){}},BEEP:{action:function(){}},PLAY:{args:["STRING"],action:function(b){b.stack.pop()}},SLEEP:{args:["INTEGER"],action:function(b){b.stack.pop()}},SYSTEM:{args:["INTEGER"],action:function(b){b.stack.pop()}},__print_using:{action:function(b){for(var c=b.stack.pop(),a=b.stack.pop(),d=[],f=0;f<c-1;f++)d.unshift(b.stack.pop());for(var c=d.shift().value,f=0,g="",i=0;i<c.length;i++){var j=c.charAt(i);if(j==="#"){if(f===d.length||!QBasic.IsNumericType(d[f].type))throw Error("Type mismatch error.");
for(var k=i,n=0;i<c.length;i++)if(j=c.charAt(i),j==="#")n++;else if(j!==",")break;var e=""+d[f].value;if(e.length>n)e=e.substr(e.length-n);else for(;e.length<n;)e=" "+e;n=0;for(i=k;i<c.length;i++)if(j=c.charAt(i),j==="#")g+=e[n++];else if(j===",")g+=j;else break;f+=1;i-=1}else g+=j}b.cons.print(g);a===","?b.cons.print("\t"):a!==";"&&b.cons.print("\n")}},LOCATE:{args:["INTEGER","INTEGER"],action:function(b){b.stack.pop();b.stack.pop()}},COLOR:{args:["ANY","ANY"],minArgs:1,action:function(b){b.stack.pop();
b.stack.pop()}},READ:{args:["ANY","ANY"],minArgs:1,action:function(b){var c=b.stack.pop(),a=[],d;for(d=0;d<c;d++)a.unshift(b.stack.pop());for(d=0;d<c;d++)if(b.debug&&console.log("READ "+b.data[b.dataPtr]),a[d].value=b.data[b.dataPtr++],a[d].value===null)a[d].value=a[d].type.createInstance()}},SCREEN:{action:function(b){b.stack.pop()}},INPUT:{action:function(b){for(var c=b.stack.pop(),a=[],d=0;d<c;d++)a.unshift(b.stack.pop());b.suspend();var f=0,g=function(d){for(var d=d.split(/\s*,\s*/),j=0;j<d.length;j++){var k=
d[j];switch(a[f].type.name){case "INTEGER":case "LONG":k=parseInt(k,10)||k;break;case "DOUBLE":case "SINGLE":k=parseFloat(k)||k}a[f++].value=k}f<c?b.cons.input(g):b.resume()};b.cons.input(g)}},SWAP:{action:function(b){var c=b.stack.pop(),b=b.stack.pop(),a=c.value;c.value=b.value;b.value=a}},WIDTH:{args:["ANY","ANY"],action:function(b){b.stack.pop();b.stack.pop()}}};QBasic.Instructions={FORLOOP:{name:"forloop",addrLabel:true,execute:function(b,c){var a=b.stack[b.stack.length-1],d=b.stack[b.stack.length-
2],f=b.stack[b.stack.length-3];d<0&&a<f||d>0&&a>f?(b.stack.length-=3,b.pc=c):b.stack.pop()}},COPYTOP:{name:"copytop",numArgs:0,execute:function(b){b.stack.push(b.stack[b.stack.length-1])}},RESTORE:{name:"restore",dataLabel:true,execute:function(b,c){b.debug&&console.log("TRACE: RESTORE to "+c);b.dataPtr=c}},POPVAL:{name:"popval",execute:function(b,c){b.getVariable(c).value=b.stack.pop()}},POP:{name:"pop",numArgs:0,execute:function(b){b.stack.pop()}},PUSHREF:{name:"pushref",execute:function(b,c){b.stack.push(b.getVariable(c))}},
PUSHVALUE:{name:"pushvalue",execute:function(b,c){b.stack.push(b.getVariable(c).value)}},PUSHTYPE:{name:"pushtype",execute:function(b,c){b.stack.push(b.types[c])}},POPVAR:{name:"popvar",execute:function(b,c){b.setVariable(c,b.stack.pop())}},NEW:{name:"new",execute:function(b,c){var a=b.types[c];b.stack.push(new QBasic.ScalarVariable(a,a.copy(b.stack.pop())))}},END:{name:"end",numArgs:0,execute:function(b){b.pc=b.instructions.length}},UNARY_OP:{name:"unary_op",execute:function(b,c){var a=b.stack.pop();
if(c=="NOT")a=~a;else if(c=="-")a=-a;else throw Error("No such unary operator: "+c);b.stack.push(a)}},"=":{name:"=",numArgs:0,execute:function(b){b.stack.push(b.stack.pop()===b.stack.pop()?-1:0)}},"==":{name:"==",numArgs:0,execute:function(b){b.stack.push(b.stack.pop()===b.stack.pop()?-1:0)}},"<":{name:"<",numArgs:0,execute:function(b){var c=b.stack.pop(),a=b.stack.pop();b.stack.push(a<c?-1:0)}},"<=":{name:"<=",numArgs:0,execute:function(b){var c=b.stack.pop(),a=b.stack.pop();b.stack.push(a<=c?-1:
0)}},">":{name:">",numArgs:0,execute:function(b){var c=b.stack.pop(),a=b.stack.pop();b.stack.push(a>c?-1:0)}},">=":{name:">=",numArgs:0,execute:function(b){var c=b.stack.pop(),a=b.stack.pop();b.stack.push(a>=c?-1:0)}},"<>":{name:"<>",numArgs:0,execute:function(b){b.stack.push(b.stack.pop()!==b.stack.pop()?-1:0)}},AND:{name:"and",numArgs:0,execute:function(b){b.stack.push(b.stack.pop()&b.stack.pop())}},OR:{name:"or",numArgs:0,execute:function(b){b.stack.push(b.stack.pop()|b.stack.pop())}},XOR:{name:"xor",
numArgs:0,execute:function(b){b.stack.push(b.stack.pop()^b.stack.pop())}},"+":{name:"+",numArgs:0,execute:function(b){var c=b.stack.pop(),a=b.stack.pop();b.stack.push(a+c)}},"-":{name:"-",numArgs:0,execute:function(b){var c=b.stack.pop(),a=b.stack.pop();b.stack.push(a-c)}},"*":{name:"*",numArgs:0,execute:function(b){b.stack.push(b.stack.pop()*b.stack.pop())}},"/":{name:"/",numArgs:0,execute:function(b){var c=b.stack.pop(),a=b.stack.pop();if(c==0)throw Error("Division by zero.");b.stack.push(a/c)}},
"\\":{name:"\\",numArgs:0,execute:function(b){var c=b.stack.pop(),a=b.stack.pop();if(c==0)throw Error("Division by zero.");b.stack.push(Math.floor(a/c))}},"^":{name:"^",numArgs:0,execute:function(b){var c=b.stack.pop(),a=b.stack.pop();b.stack.push(Math.pow(a,c))}},MOD:{name:"mod",numArgs:0,execute:function(b){var c=b.stack.pop(),a=b.stack.pop();if(c==0)throw Error("Modulus by zero.");b.stack.push(a%c)}},BZ:{name:"bz",addrLabel:true,execute:function(b,c){if(!b.stack.pop())b.pc=c}},BNZ:{name:"bnz",
addrLabel:true,execute:function(b,c){if(b.stack.pop())b.pc=c}},JMP:{name:"jmp",addrLabel:true,execute:function(b,c){b.pc=c}},CALL:{name:"call",addrLabel:true,execute:function(b,c){b.frame=new f(b.pc);b.callstack.push(b.frame);b.pc=c}},GOSUB:{name:"gosub",addrLabel:true,execute:function(b,c){var a=b.frame.variables;b.frame=new f(b.pc);b.frame.variables=a;b.callstack.push(b.frame);b.pc=c}},RET:{name:"ret",numArgs:0,execute:function(b){b.pc=b.callstack.pop().pc;b.frame=b.callstack[b.callstack.length-
1]}},PUSHCONST:{name:"pushconst",execute:function(b,c){b.stack.push(c)}},ARRAY_DEREF:{name:"array_deref",numArgs:1,execute:function(b,c){for(var a=b.stack.pop(),d=[],f=0;f<a.dimensions.length;f++)d.unshift(b.stack.pop());c?b.stack.push(a.access(d)):b.stack.push(a.access(d).value)}},MEMBER_DEREF:{name:"member_deref",execute:function(b,c){var a=b.stack.pop()[c];b.stack.push(a)}},MEMBER_VALUE:{name:"member_value",execute:function(b,c){var a=b.stack.pop()[c];b.stack.push(a.value)}},ASSIGN:{name:"assign",
numArgs:0,execute:function(b){var c=b.stack.pop(),b=b.stack.pop();c.value=c.type.copy(b)}},SYSCALL:{name:"syscall",execute:function(b,c){b.debug&&console.log("TRACE: Execute syscall "+c);if(c=="print")b.cons.print(b.stack.pop().toString());else if(c=="alloc_array"){for(var a=b.stack.pop(),d=b.stack.pop(),f=[],g=0;g<d;g++){var i=b.stack.pop(),j=b.stack.pop();f.unshift(new QBasic.Dimension(j,i))}a=new QBasic.ArrayVariable(a,f);b.stack.push(a)}else c=="print_comma"?b.cons.print("\t"):c=="print_tab"?
(a=b.stack.pop(),a=Array(a).join(" "),b.cons.print(a)):c=="alloc_scalar"?(a=b.stack.pop(),a=new QBasic.ScalarVariable(a,a.createInstance()),b.stack.push(a)):QBasic.SystemFunctions[c]?QBasic.SystemFunctions[c].action(b):QBasic.SystemSubroutines[c]?QBasic.SystemSubroutines[c].action(b):b.cons.print("Unknown syscall: "+c)}}}})();
(function(){function f(a,b){var c=new QBasic.AstSubroutine(b,"_main",[],a[0],false);return new QBasic.AstProgram(b,c)}function b(a,b){var c=new QBasic.AstSubroutine(b,"_main",[],[a[0]],false);return new QBasic.AstProgram(b,c)}function c(a,b){var c=a[0],c=c.match(/^&H/)?parseInt(c.slice(2),16):parseFloat(c);return new QBasic.AstConstantExpr(b,c)}function a(a,b){return new QBasic.AstConstantExpr(b,a[0].substr(1,a[0].length-2))}function d(a,b){return new QBasic.AstBinaryOp(b,a[0],a[1],a[2])}function h(a){return a[1]}
Array.prototype.accept=function(a){for(var b=0;b<this.length;b++)this[b]&&this[b].accept(a)};QBasic.AstProgram=function(a,b){this.locus=a;this.subs=[b]};QBasic.AstProgram.prototype.accept=function(a){a.visitProgram(this)};QBasic.AstArgument=function(a,b,c,d){this.locus=a;this.name=b;this.typeName=c;this.isArray=d;this.type=null};QBasic.AstArgument.prototype.accept=function(a){a.visitArgument(this)};QBasic.AstSubroutine=function(a,b,c,d,f,e){this.locus=a;this.name=b;this.args=c;this.statements=d;this.isFunction=
f;this.isStatic=e};QBasic.AstSubroutine.prototype.accept=function(a){a.visitSubroutine(this)};QBasic.AstDeclareFunction=function(a,b,c,d){this.locus=a;this.name=b;this.args=c;this.isFunction=d;this.type=null;this.used=this.hasBody=false};QBasic.AstDeclareFunction.prototype.accept=function(a){a.visitDeclareFunction(this)};QBasic.AstPrintUsingStatement=function(a,b,c){this.locus=a;this.exprList=b;this.terminator=c};QBasic.AstPrintUsingStatement.prototype.accept=function(a){a.visitPrintUsingStatement(this)};
QBasic.AstPrintStatement=function(a,b){this.locus=a;this.printItems=b};QBasic.AstPrintStatement.prototype.accept=function(a){a.visitPrintStatement(this)};QBasic.AstPrintItem=function(a,b,c,d){this.locus=a;this.type=b;this.expr=c;this.terminator=d};QBasic.AstPrintItem.EXPR=0;QBasic.AstPrintItem.TAB=1;QBasic.AstPrintItem.prototype.accept=function(a){a.visitPrintItem(this)};QBasic.AstInputStatement=function(a,b,c,d){this.locus=a;this.promptExpr=b;this.printQuestionMark=c;this.identifiers=d};QBasic.AstInputStatement.prototype.accept=
function(a){a.visitInputStatement(this)};QBasic.AstNullStatement=function(a){this.locus=a};QBasic.AstNullStatement.prototype.accept=function(a){a.visitNullStatement(this)};QBasic.AstEndStatement=function(a){this.locus=a};QBasic.AstEndStatement.prototype.accept=function(a){a.visitEndStatement(this)};QBasic.AstNextStatement=function(a,b){this.locus=a;this.identifiers=b};QBasic.AstNextStatement.prototype.accept=function(a){a.visitNextStatement(this)};QBasic.AstArrayDeref=function(a,b,c){this.locus=a;
this.expr=b;this.parameters=c;this.type=null};QBasic.AstArrayDeref.prototype.accept=function(a){a.visitArrayDeref(this)};QBasic.AstMemberDeref=function(a,b,c){this.locus=a;this.lhs=b;this.identifier=c};QBasic.AstMemberDeref.prototype.accept=function(a){a.visitMemberDeref(this)};QBasic.AstVariableReference=function(a,b){this.locus=a;this.name=b};QBasic.AstVariableReference.prototype.accept=function(a){a.visitVariableReference(this)};QBasic.AstRange=function(a,b,c){this.locus=a;this.lowerExpr=b;this.upperExpr=
c};QBasic.AstRange.prototype.accept=function(a){a.visitRange(this)};QBasic.AstDataStatement=function(a,b){this.locus=a;this.data=b};QBasic.AstDataStatement.prototype.accept=function(a){a.visitDataStatement(this)};QBasic.AstRestoreStatement=function(a,b){this.locus=a;this.label=b};QBasic.AstRestoreStatement.prototype.accept=function(a){a.visitRestoreStatement(this)};QBasic.AstDimStatement=function(a,b,c,d){this.locus=a;this.name=b;this.ranges=c;this.typeName=d;this.shared=false};QBasic.AstDimStatement.prototype.accept=
function(a){a.visitDimStatement(this)};QBasic.AstDefTypeStatement=function(a,b){this.locus=a;this.typeName=b};QBasic.AstDefTypeStatement.prototype.accept=function(a){a.visitDefTypeStatement(this)};QBasic.AstConstStatement=function(a,b,c){this.locus=a;this.name=b;this.expr=c};QBasic.AstConstStatement.prototype.accept=function(a){a.visitConstStatement(this)};QBasic.AstDoStatement=function(a,b,c,d){this.locus=a;this.statements=b;this.expr=c;this.type=d};QBasic.AstDoStatement.INFINITE=1;QBasic.AstDoStatement.UNTIL=
2;QBasic.AstDoStatement.WHILE_AT_END=3;QBasic.AstDoStatement.prototype.accept=function(a){a.visitDoStatement(this)};QBasic.AstExitStatement=function(a,b){this.locus=a;this.what=b};QBasic.AstExitStatement.prototype.accept=function(a){a.visitExitStatement(this)};QBasic.AstWhileLoop=function(a,b,c){this.locus=a;this.expr=b;this.statements=c};QBasic.AstWhileLoop.prototype.accept=function(a){a.visitWhileLoop(this)};QBasic.AstForLoop=function(a,b,c,d,f){this.locus=a;this.identifier=b;this.startExpr=c;this.endExpr=
d;this.stepExpr=f};QBasic.AstForLoop.prototype.accept=function(a){a.visitForLoop(this)};QBasic.AstIfStatement=function(a,b,c,d){this.locus=a;this.expr=b;this.statements=c;this.elseStatements=d};QBasic.AstIfStatement.prototype.accept=function(a){a.visitIfStatement(this)};QBasic.AstSelectStatement=function(a,b,c){this.locus=a;this.expr=b;this.cases=c};QBasic.AstSelectStatement.prototype.accept=function(a){a.visitSelectStatement(this)};QBasic.AstCaseStatement=function(a,b,c){this.locus=a;this.exprList=
b;this.statements=c};QBasic.AstCaseStatement.prototype.accept=function(a){a.visitCaseStatement(this)};QBasic.AstTypeMember=function(a,b,c){this.locus=a;this.name=b;this.typeName=c};QBasic.AstTypeMember.prototype.accept=function(a){a.visitTypeMember(this)};QBasic.AstUserType=function(a,b,c){this.locus=a;this.name=b;this.members=c};QBasic.AstUserType.prototype.accept=function(a){a.visitUserType(this)};QBasic.AstGotoStatement=function(a,b){this.locus=a;this.label=b};QBasic.AstGotoStatement.prototype.accept=
function(a){a.visitGotoStatement(this)};QBasic.AstGosubStatement=function(a,b){this.locus=a;this.label=b};QBasic.AstGosubStatement.prototype.accept=function(a){a.visitGosub(this)};QBasic.AstLabel=function(a,b){this.locus=a;this.label=b};QBasic.AstLabel.prototype.accept=function(a){a.visitLabel(this)};QBasic.AstCallStatement=function(a,b,c){this.locus=a;this.name=b;this.args=c};QBasic.AstCallStatement.prototype.accept=function(a){a.visitCallStatement(this)};QBasic.AstAssignStatement=function(a,b,c){this.locus=
a;this.lhs=b;this.expr=c};QBasic.AstAssignStatement.prototype.accept=function(a){a.visitAssignStatement(this)};QBasic.AstBinaryOp=function(a,b,c,d){this.locus=a;this.lhs=b;this.op=c;this.rhs=d};QBasic.AstBinaryOp.prototype.accept=function(a){a.visitBinaryOp(this)};QBasic.AstUnaryOperator=function(a,b,c){this.locus=a;this.op=b;this.expr=c};QBasic.AstUnaryOperator.prototype.accept=function(a){a.visitUnaryOperator(this)};QBasic.AstConstantExpr=function(a,b){this.locus=a;this.value=b};QBasic.AstConstantExpr.prototype.accept=
function(a){a.visitConstantExpr(this)};QBasic.AstReturnStatement=function(a,b){this.locus=a;this.value=b};QBasic.AstReturnStatement.prototype.accept=function(a){a.visitReturnStatement(this)};QBasic.Program=function(a,b){this.errors=[];this.createParser(this.errors);a+="\n";var c=QBasic.Program.parser.parse(a);if(c===null)throw this.errors=QBasic.Program.parser.errors,Error("Parse failed: "+this.errors[0]);b=b||{};this.typeChecker=new QBasic.TypeChecker(b.typeChecker,this.errors);c.accept(this.typeChecker);
if(this.errors.length>0)throw Error("There were errors.");this.codeGenerator=new QBasic.CodeGenerator(b.codeGenerator);c.accept(this.codeGenerator);this.sourcecode=a;this.instructions=this.codeGenerator.instructions.slice();this.types=this.typeChecker.types;this.defaultType=this.typeChecker.defaultType;this.data=this.codeGenerator.data.slice();this.shared=this.codeGenerator.shared;this.lineMap=this.codeGenerator.lineMapping};QBasic.Program.parser=null;QBasic.Program.prototype.getByteCodeAsString=
function(){if(!this.instructions)return"";for(var a=this.sourcecode.split("\n"),b=[],c=0;c<this.instructions.length;c++){var d=this.lineMap[c];d&&b.push("   ' L"+(d.line+1)+" "+a[d.line]);b.push("["+c+"] "+this.instructions[c])}return b.join("\n")};QBasic.Program.prototype.createParser=function(g){function i(a){return a[1]}function j(a){return a[0]}function k(a){a[0].push(a[1]);return a[0]}function n(a){a[1].unshift(a[0]);return a[1]}if(!QBasic.Program.parser){var e=new QBasic.RuleParser;e.addRule("start: program");
e.addToken("AND","AND");e.addToken("AS","AS");e.addToken("CASE","CASE");e.addToken("CONST","CONST");e.addToken("DATA","DATA");e.addToken("DECLARE","DECLARE");e.addToken("DEF","DEF");e.addToken("DEFINT","DEFINT");e.addToken("DIM","DIM");e.addToken("DO","DO");e.addToken("ELSE","ELSE");e.addToken("END","END");e.addToken("EXIT","EXIT");e.addToken("FOR","FOR");e.addToken("FUNCTION","FUNCTION");e.addToken("GOSUB","GOSUB");e.addToken("GOTO","GOTO");e.addToken("IF","IF");e.addToken("INPUT","INPUT");e.addToken("LINE",
"LINE");e.addToken("LOOP","LOOP");e.addToken("MOD","MOD");e.addToken("NEXT","NEXT");e.addToken("NOT","NOT");e.addToken("OR","OR");e.addToken("POKE","POKE");e.addToken("PRINT","PRINT");e.addToken("RESTORE","RESTORE");e.addToken("RETURN","RETURN");e.addToken("SEG","SEG");e.addToken("SELECT","SELECT");e.addToken("SHARED","SHARED");e.addToken("STATIC","STATIC");e.addToken("STEP","STEP");e.addToken("SUB","SUB");e.addToken("TAB","TAB");e.addToken("THEN","THEN");e.addToken("TO","TO");e.addToken("TYPE","TYPE");
e.addToken("UNTIL","UNTIL");e.addToken("USING","USING");e.addToken("VIEW","VIEW");e.addToken("WEND","WEND");e.addToken("WHILE","WHILE");e.addToken("XOR","XOR");e.addToken("minus","\\-");e.addToken("endl","\\n");e.addToken("comment","'.*$");e.addToken("hexconstant","\\&H[\\da-fA-F]+");e.addToken("floatconstant","\\d*\\.\\d+");e.addToken("intconstant","\\d+");e.addToken("stringconstant",'"[^"]*"');e.addToken("label","^([a-zA-Z][a-zA-Z0-9_]*:|\\d+)");e.addToken("identifier","[a-zA-Z_][a-zA-Z0-9_]*(\\$|%|#|&|!)?");
e.addRule("program: statements",f);e.addRule("program: repl_expr endl",b);e.addRule("statements: statement*");e.addRule("statement: label istatement separator",function(a,b){var c=a[0];c.substr(-1)==":"&&(c=c.substr(0,c.length-1));return[new QBasic.AstLabel(b,c),a[1]]});e.addRule("statement: label",function(a,b){var c=a[0];c.substr(-1)==":"&&(c=c.substr(0,c.length-1));return new QBasic.AstLabel(b,c)});e.addRule("statement: istatement ? separator");e.addRule("istatement: CONST identifier '=' expr",
function(a,b){return new QBasic.AstConstStatement(b,a[1],a[3])});e.addRule("istatement: DECLARE FUNCTION identifier ArgList",function(a,b){return new QBasic.AstDeclareFunction(b,a[2],a[3],true)});e.addRule("istatement: DECLARE SUB identifier ArgList",function(a,b){return new QBasic.AstDeclareFunction(b,a[2],a[3],false)});e.addRule("istatement: SUB identifier ArgList STATIC? statements END SUB",function(a,b){return new QBasic.AstSubroutine(b,a[1],a[2],a[4],false,a[3]!==null)});e.addRule("istatement: FUNCTION identifier ArgList statements END FUNCTION",
function(a,b){return new QBasic.AstSubroutine(b,a[1],a[2],a[3],true)});e.addRule("istatement: DEF SEG ('=' expr)?",function(a,b){return new QBasic.AstNullStatement(b)});e.addRule("istatement: DEF identifier ArgList '=' expr",function(a,b){return new QBasic.AstNullStatement(b)});e.addRule("istatement: DEFINT identifier minus identifier",function(a,b){return new QBasic.AstDefTypeStatement(b,"INTEGER")});e.addRule("istatement: VIEW PRINT",function(a,b){return new QBasic.AstNullStatement(b)});e.addRule("istatement: DIM DimList",
i);e.addRule("istatement: DIM SHARED DimList",function(a){for(var b=0;b<a[2].length;b++)a[2][b].shared=true;return a[2]});e.addRule("istatement: WHILE expr separator statements WEND",function(a,b){return new QBasic.AstWhileLoop(b,a[1],a[3])});e.addRule("istatement: DO separator statements LOOP",function(a,b){return new QBasic.AstDoStatement(b,a[2],null,QBasic.AstDoStatement.INFINITE)});e.addRule("istatement: DO separator statements LOOP WHILE expr",function(a,b){return new QBasic.AstDoStatement(b,
a[2],a[5],QBasic.AstDoStatement.WHILE_AT_END)});e.addRule("istatement: DO separator statements LOOP UNTIL expr",function(a,b){return new QBasic.AstDoStatement(b,a[2],a[5],QBasic.AstDoStatement.UNTIL)});e.addRule("istatement: DO WHILE expr separator statements LOOP",function(a,b){return new QBasic.AstWhileLoop(b,a[2],a[4])});e.addRule("istatement: FOR identifier '=' expr TO expr",function(a,b){return new QBasic.AstForLoop(b,a[1],a[3],a[5],new QBasic.AstConstantExpr(b,1))});e.addRule("istatement: FOR identifier '=' expr TO expr STEP expr",
function(a,b){return new QBasic.AstForLoop(b,a[1],a[3],a[5],a[7])});e.addRule("istatement: NEXT identifiers?",function(a,b){a[1]===null&&(a[1]=[]);return new QBasic.AstNextStatement(b,a[1])});e.addRule("istatement: EXIT (FOR|DO)",function(a,b){return new QBasic.AstExitStatement(b,a[1])});e.addRule("identifiers: MoreIdentifiers* identifier",k);e.addRule("MoreIdentifiers: identifier ','",j);e.addRule("istatement: END",function(a,b){return new QBasic.AstEndStatement(b)});e.addRule("istatement: GOSUB identifier",
function(a,b){return new QBasic.AstGosubStatement(b,a[1])});e.addRule("istatement: GOTO identifier",function(a,b){return new QBasic.AstGotoStatement(b,a[1])});e.addRule("istatement: IF expr THEN istatement",function(a,b){return new QBasic.AstIfStatement(b,a[1],a[3],null)});e.addRule("istatement: IF expr THEN separator statements ElseClause END IF",function(a,b){return new QBasic.AstIfStatement(b,a[1],a[4],a[5])});e.addRule("ElseClause: ELSE IF expr THEN separator statements ElseClause",function(a,
b){return new QBasic.AstIfStatement(b,a[2],a[5],a[6])});e.addRule("ElseClause: ELSE statements",i);e.addRule("ElseClause:",function(a,b){return new QBasic.AstNullStatement(b)});e.addRule("istatement: SELECT CASE expr separator case* END SELECT",function(a,b){return new QBasic.AstSelectStatement(b,a[2],a[4])});e.addRule("case: CASE exprList separator statements",function(a,b){return new QBasic.AstCaseStatement(b,a[1],a[3])});e.addRule("case: CASE ELSE separator statements",function(a,b){return new QBasic.AstCaseStatement(b,
[],a[3])});e.addRule("exprList: moreExpr* expr",k);e.addRule("moreExpr: expr ','",j);e.addRule("istatement: INPUT constant? (';'|',') identifiers",function(a,b){return new QBasic.AstInputStatement(b,a[1],a[2]==";",a[3])});e.addRule("istatement: LINE? INPUT identifiers",function(a,b){return new QBasic.AstInputStatement(b,null,false,a[2])});e.addRule("istatement: POKE expr ',' expr",function(a,b){return new QBasic.AstNullStatement(b)});e.addRule("istatement: PRINT",function(a,b){return new QBasic.AstPrintStatement(b,
[])});e.addRule("istatement: PRINT PrintItems",function(a,b){return new QBasic.AstPrintStatement(b,a[1])});e.addRule("istatement: PRINT USING [expr,';'] (';'|',')?",function(a,b){return new QBasic.AstPrintUsingStatement(b,a[2],a[3])});e.addRule("PrintItems: PrintItem",function(a){return a});e.addRule("PrintItems: MorePrintItems* PrintItem (';'|',')?",function(a){a[1].terminator=a[2];a[0].push(a[1]);return a[0]});e.addRule("MorePrintItems: PrintItem (';'|',')",function(a){a[0].terminator=a[1];return a[0]});
e.addRule("PrintItem: expr",function(a,b){return new QBasic.AstPrintItem(b,QBasic.AstPrintItem.EXPR,a[0],null)});e.addRule("PrintItem: TAB '\\(' expr '\\)'",function(a,b){return new QBasic.AstPrintItem(b,QBasic.AstPrintItem.TAB,a[2],null)});e.addRule("PrintItem:",function(a,b){return new QBasic.AstPrintItem(b,QBasic.AstPrintItem.EXPR,null,null)});e.addRule("istatement: RESTORE identifier?",function(a,b){return new QBasic.AstRestoreStatement(b,a[1])});e.addRule("istatement: RETURN",function(a,b){return new QBasic.AstReturnStatement(b)});
e.addRule("istatement: DATA [DataConstant,',']",function(a,b){return new QBasic.AstDataStatement(b,a[1])});e.addRule("DataConstant: identifier",function(a,b){return new QBasic.AstConstantExpr(b,a[0])});e.addRule("DataConstant: constant");e.addRule("DataConstant:",function(a,b){return new QBasic.AstConstantExpr(b,null)});e.addRule("istatement: TYPE identifier separator TypeMembers END TYPE",function(a,b){return new QBasic.AstUserType(b,a[1],a[3])});e.addRule("istatement: AssignStatement");e.addRule("AssignStatement: ReferenceList '=' expr2",
function(a,b){return new QBasic.AstAssignStatement(b,a[0],a[2])});e.addRule("istatement: identifier Parameters",function(a,b){return new QBasic.AstCallStatement(b,a[0],a[1])});e.addRule("Parameters: ",function(){return[]});e.addRule("Parameters: '\\(' ParameterList '\\)'",i);e.addRule("Parameters: ParameterList");e.addRule("ParameterList: [Parameter,',']");e.addRule("Parameter: expr");e.addRule("Parameter:",function(a,b){return new QBasic.AstConstantExpr(b,null)});e.addRule("DimList: Dim MoreDims*",
n);e.addRule("MoreDims: ',' Dim",i);e.addRule("Dim: identifier AsType?",function(a,b){return new QBasic.AstDimStatement(b,a[0],[],a[1])});e.addRule("Dim: identifier '\\(' RangeList '\\)' AsType?",function(a,b){return new QBasic.AstDimStatement(b,a[0],a[2],a[4])});e.addRule("AsType: AS identifier",i);e.addRule("RangeList:",function(){return null});e.addRule("RangeList: Range MoreRanges*",n);e.addRule("MoreRanges: ',' Range",i);e.addRule("Range: expr EndRange?",function(a,b){return a[1]?new QBasic.AstRange(b,
a[0],a[1]):new QBasic.AstRange(b,new QBasic.AstConstantExpr(b,0),a[0])});e.addRule("EndRange: TO expr",i);e.addRule("TypeMembers: TypeMember*");e.addRule("TypeMember: identifier AS identifier separator",function(a,b){return new QBasic.AstTypeMember(b,a[0],a[2])});e.addRule("ArgList:",function(){return[]});e.addRule("ArgList: '\\(' [ Argument , ',' ] '\\)'",function(a){return a[1]});e.addRule("Argument: identifier OptParen? AS identifier",function(a,b){return new QBasic.AstArgument(b,a[0],a[3],a[1]!==
null)});e.addRule("Argument: identifier OptParen?",function(a,b){return new QBasic.AstArgument(b,a[0],null,a[1]!==null)});e.addRule("OptParen: '\\(' '\\)'");e.addRule("expr: expr2");e.addRule("expr2: expr2 OR expr3",d);e.addRule("expr2: expr2 XOR expr3",d);e.addRule("expr2: expr3");e.addRule("expr3: expr3 AND expr4",d);e.addRule("expr3: expr4");e.addRule("expr4: expr4 '=' expr5",d);e.addRule("expr4: expr4 '<>' expr5",d);e.addRule("expr4: expr4 '>' expr5",d);e.addRule("expr4: expr4 '<' expr5",d);e.addRule("expr4: expr4 '<=' expr5",
d);e.addRule("expr4: expr4 '>=' expr5",d);e.addRule("expr4: expr5");e.addRule("repl_expr: repl_expr2");e.addRule("repl_expr2: repl_expr2 OR repl_expr3",d);e.addRule("repl_expr2: repl_expr2 XOR repl_expr3",d);e.addRule("repl_expr2: repl_expr3");e.addRule("repl_expr3: repl_expr3 AND repl_expr4",d);e.addRule("repl_expr3: repl_expr4");e.addRule("repl_expr4: repl_expr4 '==' expr5",d);e.addRule("repl_expr4: repl_expr4 '<>' expr5",d);e.addRule("repl_expr4: repl_expr4 '>' expr5",d);e.addRule("repl_expr4: repl_expr4 '<' expr5",
d);e.addRule("repl_expr4: repl_expr4 '<=' expr5",d);e.addRule("repl_expr4: repl_expr4 '>=' expr5",d);e.addRule("repl_expr4: expr5");e.addRule("expr5: expr5 MOD expr6",d);e.addRule("expr5: expr6");e.addRule("expr6: expr6 '\\+' expr7",d);e.addRule("expr6: expr6 '\\-' expr7",d);e.addRule("expr6: expr7");e.addRule("expr7: expr7 '\\*' expr7b",d);e.addRule("expr7: expr7 '\\/' expr7b",d);e.addRule("expr7: expr7 '\\\\' expr7b",d);e.addRule("expr7: expr7b");e.addRule("expr7b: expr7b '\\^' expr8",d);e.addRule("expr7b: expr8");
e.addRule("expr8: '\\(' expr '\\)'",h);e.addRule("expr8: NOT expr9",function(a,b){return new QBasic.AstUnaryOperator(b,"NOT",a[1])});e.addRule("expr8: '\\-' expr9",function(a,b){return new QBasic.AstUnaryOperator(b,"-",a[1])});e.addRule("expr8: expr9");e.addRule("expr9: constant");e.addRule("expr9: expr10");e.addRule("expr10: ReferenceList");e.addRule("constant: hexconstant",c);e.addRule("constant: intconstant",c);e.addRule("constant: floatconstant",c);e.addRule("constant: stringconstant",a);e.addRule("ReferenceList: ReferenceList '\\.' identifier",
function(a,b){return new QBasic.AstMemberDeref(b,a[0],a[2])});e.addRule("ReferenceList: ReferenceList '\\(' ParameterList '\\)'",function(a,b){return new QBasic.AstArrayDeref(b,a[0],a[2])});e.addRule("ReferenceList: Reference");e.addRule("Reference: identifier",function(a,b){return new QBasic.AstVariableReference(b,a[0])});e.addRule("separator: endl+");e.addRule("separator: comment endl");e.addRule("separator: ':'");g=g||[];e.buildSet.check(g);for(var l=0;l<g.length;l++)console.log(g[l]);e.buildSet.finalize();
QBasic.Program.parser=new QBasic.EarleyParser(e.buildSet)}}})();
